In [8]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-final/notebookda02e89746.ipynb
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source2.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source3.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source1.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train/train_ground_truth.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train/train_source3.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train/train_source2.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train/train_source1.tsv

In [9]:
import os

print("Dataset files:")

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        if file.endswith(".tsv"):
            print(os.path.join(root, file))

Dataset files:
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source2.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source3.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source1.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train/train_ground_truth.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train/train_source3.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train/train_source2.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train/train_source1.tsv

In [10]:
import os

print("All files in dataset:")

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        print(os.path.join(root, file))

All files in dataset:
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-final/notebookda02e89746.ipynb
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source2.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source3.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source1.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train/train_ground_truth.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train/train_source3.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train/train_source2.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train/train_source1.tsv

In [11]:
import json

notebook_path = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-final/notebookda02e89746.ipynb"

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

print("Total cells:", len(nb["cells"]))

for i, cell in enumerate(nb["cells"]):
    print("\n" + "="*60)
    print("CELL", i + 1, "-", cell["cell_type"])
    print("="*60)
    print("".join(cell["source"])[:1000])

Total cells: 36

============================================================
CELL 1 - code
============================================================
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like c

============================================================
CELL 2 - code
============================================================
import os

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        if file == "training_features.tsv":
            print(os.path.join(root, file))

============================================================
CELL 3 - code
============================================================
import pandas as pd

features_path = "YAHAN_EXACT_PATH_DAALO"

df_check = pd.read_csv(
    features_path,
    sep="\t",
    nrows=10000
)

print("Shape:", df_check.shape)
print("\nColumns:")
print(df_check.columns.tolist())

print("\nLabels:")
print(df_check["label"].value_counts())

============================================================
CELL 4 - code
============================================================
import os

print(os.listdir("/kaggle/input"))


============================================================
CELL 5 - code
============================================================
import os

print(os.listdir("/kaggle/input/datasets"))

============================================================
CELL 6 - code
============================================================
import os

print(os.listdir("/kaggle/input/datasets/growwithme02"))


============================================================
CELL 7 - code
============================================================
import os

print(os.listdir("/kaggle/input/datasets/growwithme02/amazonbusiness3-0"))

============================================================
CELL 8 - code
============================================================
import pandas as pd

features_path = "/kaggle/input/datasets/growwithme02/amazonbusiness3-0/training_features.tsv"

df_check = pd.read_csv(
    features_path,
    sep="\t",
    nrows=10000
)

print("Shape:", df_check.shape)

print("\nColumns:")
print(df_check.columns.tolist())

print("\nLabels:")
print(df_check["label"].value_counts())


============================================================
CELL 9 - code
============================================================
print(df_check.info())


============================================================
CELL 10 - code
============================================================
print("\nMissing values:")
print(df_check.isnull().sum())
print("\nSample data:")
display(df_check.head())

============================================================
CELL 11 - code
============================================================
print("\nSample data:")
display(df_check.head())

============================================================
CELL 12 - code
============================================================
print(df_check.dtypes)


============================================================
CELL 13 - code
============================================================
print("\nMissing values:")
print(df_check.isnull().sum())


============================================================
CELL 14 - code
============================================================
print("\nLabel distribution:")
print(df_check["label"].value_counts())
print("\nLabel percentage:")
print(df_check["label"].value_counts(normalize=True) * 100)


============================================================
CELL 15 - code
============================================================
print(df_check.dtypes)


============================================================
CELL 16 - code
============================================================


============================================================
CELL 17 - code
============================================================
features = [
    "name_similarity",
    "address_similarity",
    "name_token_similarity",
    "address_token_similarity",
    "number_overlap",
    "country_match",
    "source1_address_missing",
    "candidate_address_missing"
]

X = df_check[features]
y = df_check["label"]

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nFeatures:")
print(X.columns.tolist())

print("\nLabels:")
print(y.value_counts())

============================================================
CELL 18 - code
============================================================
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

print("\nTraining labels:")
print(y_train.value_counts())

print("\nTesting labels:")
print(y_test.value_counts())


============================================================
CELL 19 - code
============================================================
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

print("Model training completed!")


============================================================
CELL 20 - code
============================================================
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

print("Model training completed!")


============================================================
CELL 21 - code
============================================================
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    average_precision_score
)

# Predictions
y_pred = model.predict(X_test)

# Probability of class 1
y_prob = model.predict_proba(X_test)[:, 1]

print("Classification Report:")
print(classification_report(y_test, y_pred, digits=4))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nROC-AUC:")
print(roc_auc_score(y_test, y_prob))

print("\nPR-AUC (Average Precision):")
print(average_precision_score(y_test, y_prob))

============================================================
CELL 22 - code
============================================================
import os

features_path = "/kaggle/input/datasets/growwithme02/amazonbusiness3-0/training_features.tsv"

print("File exists:", os.path.exists(features_path))
print("File size (GB):", os.path.getsize(features_path) / (1024**3))

============================================================
CELL 23 - code
============================================================
import pandas as pd

df_check = pd.read_csv(
    features_path,
    sep="\t",
    nrows=10000
)

print(df_check.shape)

============================================================
CELL 24 - code
============================================================
import pandas as pd

features_path = "/kaggle/input/datasets/growwithme02/amazonbusiness3-0/training_features.tsv"

total_rows = 0

for chunk in pd.read_csv(
    features_path,
    sep="\t",
    usecols=[
        "name_similarity",
        "address_similarity",
        "name_token_similarity",
        "address_token_similarity",
        "number_overlap",
        "country_match",
        "source1_address_missing",
        "candidate_address_missing",
        "label"
    ],
    chunksize=100000
):
    total_rows += len(chunk)

print("Total rows:", total_rows)


============================================================
CELL 25 - code
============================================================
import pandas as pd

features_path = "/kaggle/input/datasets/growwithme02/amazonbusiness3-0/training_features.tsv"

label_counts = {0: 0, 1: 0}

for chunk in pd.read_csv(
    features_path,
    sep="\t",
    usecols=["label"],
    chunksize=200000
):
    counts = chunk["label"].value_counts()

    for label, count in counts.items():
        label_counts[int(label)] += int(count)

print("Full dataset label distribution:")
print(label_counts)

total = label_counts[0] + label_counts[1]

print("\nPercentages:")
print("Label 0:", label_counts[0] / total * 100, "%")
print("Label 1:", label_counts[1] / total * 100, "%")

============================================================
CELL 26 - code
============================================================
import pandas as pd

features_path = "/kaggle/input/datasets/growwithme02/amazonbusiness3-0/training_features.tsv"

features = [
    "name_similarity",
    "address_similarity",
    "name_token_similarity",
    "address_token_similarity",
    "number_overlap",
    "country_match",
    "source1_address_missing",
    "candidate_address_missing",
    "label"
]

positive_parts = []
negative_parts = []

for chunk in pd.read_csv(
    features_path,
    sep="\t",
    usecols=features,
    chunksize=200000
):
    pos = chunk[chunk["label"] == 1]
    neg = chunk[chunk["label"] == 0]

    if len(pos) > 0:
        positive_parts.append(pos)

    if len(neg) > 0:
        negative_parts.append(neg.sample(
            n=min(len(neg), 15000),
            random_state=42
        ))

positive_df = pd.concat(positive_parts, ignore_index=True)
negative_df = pd.concat(negative_parts, ignore_index=True)

print("Positive rows collected:", len(positive_df))
print("Negative rows collected:", len(negative_df))

============================================================
CELL 27 - code
============================================================
negative_df = negative_df.sample(
    n=len(positive_df) * 5,
    random_state=42
).reset_index(drop=True)

positive_df = positive_df.reset_index(drop=True)

print("Positive rows:", len(positive_df))
print("Negative rows:", len(negative_df))

============================================================
CELL 28 - code
============================================================
final_df = pd.concat(
    [positive_df, negative_df],
    ignore_index=True
)

final_df = final_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

print("Final training dataset:", final_df.shape)
print("\nLabels:")
print(final_df["label"].value_counts())

============================================================
CELL 29 - code
============================================================
from sklearn.model_selection import train_test_split

features = [
    "name_similarity",
    "address_similarity",
    "name_token_similarity",
    "address_token_similarity",
    "number_overlap",
    "country_match",
    "source1_address_missing",
    "candidate_address_missing"
]

X_final = final_df[features]
y_final = final_df["label"]

X_train_final, X_test_final, y_train_final, y_test_final = train_test_split(
    X_final,
    y_final,
    test_size=0.2,
    random_state=42,
    stratify=y_final
)

print("Training:", X_train_final.shape)
print("Testing:", X_test_final.shape)

print("\nTraining labels:")
print(y_train_final.value_counts())

print("\nTesting labels:")
print(y_test_final.value_counts())

============================================================
CELL 30 - code
============================================================
from sklearn.ensemble import RandomForestClassifier

final_model = RandomForestClassifier(
    n_estimators=300,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

print("Training final model...")

final_model.fit(
    X_train_final,
    y_train_final
)

print("Final model training completed!")

============================================================
CELL 31 - code
============================================================
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    average_precision_score
)

# Make predictions
y_pred_final = final_model.predict(X_test_final)

# Probability of label 1
y_prob_final = final_model.predict_proba(X_test_final)[:, 1]

print("========== CLASSIFICATION REPORT ==========")
print(classification_report(
    y_test_final,
    y_pred_final,
    digits=4
))

print("\n========== CONFUSION MATRIX ==========")
print(confusion_matrix(
    y_test_final,
    y_pred_final
))

print("\n========== ROC-AUC ==========")
print(roc_auc_score(
    y_test_final,
    y_prob_final
))

print("\n========== PR-AUC ==========")
print(average_precision_score(
    y_test_final,
    y_prob_final
))

============================================================
CELL 32 - code
============================================================
import joblib

model_path = "student_matching_model.pkl"

joblib.dump(final_model, model_path)

print("Model saved successfully!")
print("File:", model_path)

============================================================
CELL 33 - code
============================================================
import os

print("File exists:", os.path.exists(model_path))
print("File size (MB):", os.path.getsize(model_path) / (1024 * 1024))

============================================================
CELL 34 - code
============================================================
import joblib
import pandas as pd

# Load saved model
loaded_model = joblib.load("student_matching_model.pkl")

# Take one example from the test data
sample = X_test_final.iloc[[0]]

# Predict
prediction = loaded_model.predict(sample)[0]

# Probability
probability = loaded_model.predict_proba(sample)[0]

print("Prediction:", prediction)
print("Probability of class 0:", probability[0])
print("Probability of class 1:", probability[1])

============================================================
CELL 35 - code
============================================================
import joblib

model_package = {
    "model": final_model,
    "features": features
}

joblib.dump(
    model_package,
    "student_matching_model_package.pkl"
)

print("Complete model package saved successfully!")

============================================================
CELL 36 - code
============================================================
import os

print(
    "Size:",
    os.path.getsize("student_matching_model_package.pkl") / (1024 * 1024),
    "MB"
)

In [12]:
import os

model_path = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-final/notebookda02e89746.ipynb"

print("Notebook exists:", os.path.exists(model_path))

Notebook exists: True

In [13]:
import os

print("All TSV files:")

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        if file.endswith(".tsv"):
            print(os.path.join(root, file))

All TSV files:
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source2.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source3.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source1.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train/train_ground_truth.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train/train_source3.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train/train_source2.tsv
/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train/train_source1.tsv

In [14]:
import pandas as pd

base = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0"

test_source1 = pd.read_csv(
    base + "/dataset/test/test_source1.tsv",
    sep="\t",
    nrows=5
)

test_source2 = pd.read_csv(
    base + "/dataset/test/test_source2.tsv",
    sep="\t",
    nrows=5
)

test_source3 = pd.read_csv(
    base + "/dataset/test/test_source3.tsv",
    sep="\t",
    nrows=5
)

print("TEST SOURCE 1")
print(test_source1.shape)
print(test_source1.columns.tolist())
display(test_source1)

print("\nTEST SOURCE 2")
print(test_source2.shape)
print(test_source2.columns.tolist())
display(test_source2)

print("\nTEST SOURCE 3")
print(test_source3.shape)
print(test_source3.columns.tolist())
display(test_source3)

TEST SOURCE 1
(5, 4)
['entity_id', 'business_name', 'business_address', 'country']

,entity_id,business_name,business_address,country
0,S1-714132312,Zephay Labs Inc,"2621 Cotten Road, Tyler, TX",US
1,S1-106407869,Vision Partners Corp,"IA, Iowa City, 1064 Newton Rd, Unit 11",US
2,S1-156285671,<< Team Ecole,"175 Boulevard du Président Franklin Roosevelt,...",France
3,S1-689823050,Red Perfect Trading,"Mirzapur, Ews 12, Uttar Pradesh, Mirzapursadar...",India
4,S1-921369899,ZNB Club SARL,"Nouvelle-Aquitaine, La Teste-de-Buch, 5 bis Ru...",France

TEST SOURCE 2
(5, 4)
['entity_id', 'business_name', 'business_address', 'country']

,entity_id,business_name,business_address,country
0,S2-192345572,Brahma Infosoft,"COIMATORE COLONY, HUNSUR TQMYSORE DIST., Karna...",India
1,S2-566025912,Marina Ecole France Sarl,"63 R. DE DIEPPE, LILLE, Hauts-de-France",France
2,S2-158121477,SCI Ptit Àmicale,"18 RUE JEN ZAY, Dunkerque, Nord",France
3,S2-89663826,Apex Summit,"67 KENTUCKY ST, SALYERSVILLE, KY",US
4,S2-884102769,Fresh Truist,"8264 FILLY COURT, ROANOKE COUNTY, VA",US

TEST SOURCE 3
(5, 4)
['entity_id', 'business_name', 'business_address', 'country']

,entity_id,business_name,business_address,country
0,S3-462677478,मॉडर्न फाइनेंस,"No 10 Enkay Square, 448A, Udyog Vihar Phase V,...",India
1,S3-374810425,Shri Sai Infratech Co,"3/115, East Delhi, DL",India
2,S3-198586129,Fractales Amis Groupe S.A.S,"23 Rue Icmre, La Teste-de-buch, Gironde",France
3,S3-10300249,Shri Supreme Consulting Private (Limited),"H.no 910 A 3503, Mumbai, महाराष्ट्र",India
4,S3-604980231,Prime Realty Ventures Public Limited,"G.t. Karnal Road, Industrial Area, New Delhi, ...",India

In [15]:
import pandas as pd

base = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0"

test_source1 = pd.read_csv(
    base + "/dataset/test/test_source1.tsv",
    sep="\t"
)

test_source2 = pd.read_csv(
    base + "/dataset/test/test_source2.tsv",
    sep="\t"
)

test_source3 = pd.read_csv(
    base + "/dataset/test/test_source3.tsv",
    sep="\t"
)

print("Source 1:", test_source1.shape)
print("Source 2:", test_source2.shape)
print("Source 3:", test_source3.shape)

Source 1: (1732544, 4)
Source 2: (4887273, 4)
Source 3: (5082316, 4)

In [16]:
train_source1 = pd.read_csv(
    base + "/dataset/train/train_source1.tsv",
    sep="\t"
)

train_source2 = pd.read_csv(
    base + "/dataset/train/train_source2.tsv",
    sep="\t"
)

train_source3 = pd.read_csv(
    base + "/dataset/train/train_source3.tsv",
    sep="\t"
)

train_ground_truth = pd.read_csv(
    base + "/dataset/train/train_ground_truth.tsv",
    sep="\t"
)

print("Train Source 1:", train_source1.shape)
print("Train Source 2:", train_source2.shape)
print("Train Source 3:", train_source3.shape)
print("Ground Truth:", train_ground_truth.shape)

print("\nGround Truth columns:")
print(train_ground_truth.columns.tolist())

Train Source 1: (2206821, 4)
Train Source 2: (5034616, 4)
Train Source 3: (5285603, 4)
Ground Truth: (2206821, 2)

Ground Truth columns:
['source1_entity_id', 'matched_entity_ids']

In [17]:
print(train_ground_truth.head(10))

print("\nMissing values:")
print(train_ground_truth.isnull().sum())

print("\nExample matched IDs:")
for i in range(10):
    print(
        train_ground_truth.iloc[i]["source1_entity_id"],
        "->",
        train_ground_truth.iloc[i]["matched_entity_ids"]
    )

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5       S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6      S1-318373630                          S2-660036492,S3-804600254
7       S1-86989137                          S3-274817120,S3-312496301
8       S1-29845983                          S2-648035184,S3-588502663
9      S1-789009573              S2-383871912,S3-74481402,S3-576451439

Missing values:
source1_entity_id          0
matched_entity_ids    123247
dtype: int64

Example matched IDs:
S1-965667 -> S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364
S1-55344266 -> S2-249013014,S2-197070651,S3-478195123,S3-384364074
S1-343815751 -> S2-790675320,S2-479876582,S3-878454467
S1-656753428 -> S2-153058913,S2-24659151,S3-679606215
S1-102811957 -> S2-478959098,S2-553508714,S2-625774905,S3-728090388,S3-928796641,S3-449308785
S1-18727616 -> S2-755677256,S3-187831601,S3-641489370,S3-476250621
S1-318373630 -> S2-660036492,S3-804600254
S1-86989137 -> S3-274817120,S3-312496301
S1-29845983 -> S2-648035184,S3-588502663
S1-789009573 -> S2-383871912,S3-74481402,S3-576451439

In [18]:
print("Source 1 columns:")
print(train_source1.columns.tolist())

print("\nSource 2 columns:")
print(train_source2.columns.tolist())

print("\nSource 3 columns:")
print(train_source3.columns.tolist())

print("\nSample Source 1:")
print(train_source1.head(3))

print("\nSample Source 2:")
print(train_source2.head(3))

print("\nSample Source 3:")
print(train_source3.head(3))

Source 1 columns:
['entity_id', 'business_name', 'business_address', 'country']

Source 2 columns:
['entity_id', 'business_name', 'business_address', 'country']

Source 3 columns:
['entity_id', 'business_name', 'business_address', 'country']

Sample Source 1:
      entity_id        business_name                        business_address  \
0  S1-925783039  Orelee's Barbershop  1795 Westchester Drive, High Point, NC
1  S1-773889195          Prime Money         17560 Ellis Road, Tahlequah, OK
2  S1-377745466        B+ Retail Inc     1712 Montebello Avenue, Phoenix, AZ

  country
0      US
1      US
2      US

Sample Source 2:
      entity_id                    business_name  \
0  S2-166376419  राम मार्केटिंग प्राइवेट लिमिटेड
1  S2-764573417     -- Holloway Peak Inc Seafood
2  S2-639257739         आदित्य प्रॉपर्टीज एलएलपी

                                   business_address country
0      KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi   India
1                         105 ELM ST, MORGANTON, NC      US
2  G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh   India

Sample Source 3:
      entity_id                                business_name  \
0  S3-202863386                           wilfordhancock.com
1  S3-859268022  International South Consultants Private Ltd
2   S3-22467283                  LLC Moncada Léarning Center

                  business_address country
0      Mack Rd, Haltom City, Texas      US
1                              NaN   India
2  5780 Fawn Ct, Fort Worth, Texas      US

In [19]:
# Ground truth ko matching pairs mein convert karna

pairs = []

for _, row in train_ground_truth.dropna(subset=["matched_entity_ids"]).iterrows():
    source1_id = row["source1_entity_id"]
    matched_ids = row["matched_entity_ids"].split(",")

    for matched_id in matched_ids:
        pairs.append((source1_id, matched_id))

pairs_df = pd.DataFrame(
    pairs,
    columns=["source1_entity_id", "matched_entity_id"]
)

print("Total positive matching pairs:", len(pairs_df))

print("\nFirst 20 pairs:")
print(pairs_df.head(20))

Total positive matching pairs: 7638365

First 20 pairs:
   source1_entity_id matched_entity_id
0          S1-965667      S2-681193310
1          S1-965667      S2-743505751
2          S1-965667      S3-775321672
3          S1-965667       S3-11291185
4          S1-965667      S3-860443364
5        S1-55344266      S2-249013014
6        S1-55344266      S2-197070651
7        S1-55344266      S3-478195123
8        S1-55344266      S3-384364074
9       S1-343815751      S2-790675320
10      S1-343815751      S2-479876582
11      S1-343815751      S3-878454467
12      S1-656753428      S2-153058913
13      S1-656753428       S2-24659151
14      S1-656753428      S3-679606215
15      S1-102811957      S2-478959098
16      S1-102811957      S2-553508714
17      S1-102811957      S2-625774905
18      S1-102811957      S3-728090388
19      S1-102811957      S3-928796641

In [20]:
# Positive pairs ke saath actual business details dekho

sample_pairs = pairs_df.head(10).copy()

# Source 1 details
sample_pairs = sample_pairs.merge(
    train_source1[
        ["entity_id", "business_name", "business_address", "country"]
    ],
    left_on="source1_entity_id",
    right_on="entity_id",
    how="left"
)

sample_pairs = sample_pairs.rename(columns={
    "business_name": "source1_name",
    "business_address": "source1_address",
    "country": "source1_country"
})

sample_pairs = sample_pairs.drop(columns=["entity_id"])

# Source 2 + Source 3 dono mein ID search karenge
source23 = pd.concat(
    [train_source2, train_source3],
    ignore_index=True
)

sample_pairs = sample_pairs.merge(
    source23[
        ["entity_id", "business_name", "business_address", "country"]
    ],
    left_on="matched_entity_id",
    right_on="entity_id",
    how="left"
)

sample_pairs = sample_pairs.rename(columns={
    "business_name": "matched_name",
    "business_address": "matched_address",
    "country": "matched_country"
})

sample_pairs = sample_pairs.drop(columns=["entity_id"])

print(sample_pairs.to_string(index=False))

source1_entity_id matched_entity_id                         source1_name                                                   source1_address source1_country                    matched_name                                                   matched_address matched_country
        S1-965667      S2-681193310         Maure Williams Colombier Inc                                  85 Wayne Avenue, Ticonderoga, NY              US    Maure Wilblims Colombier Inc                                                               NaN              US
        S1-965667      S2-743505751         Maure Williams Colombier Inc                                  85 Wayne Avenue, Ticonderoga, NY              US        Maure Williams Colombier                                                               NaN              US
        S1-965667      S3-775321672         Maure Williams Colombier Inc                                  85 Wayne Avenue, Ticonderoga, NY              US                         Dréxkor                  85 Wanye Avenue, Ticonderoga Townshiip, New York              US
        S1-965667       S3-11291185         Maure Williams Colombier Inc                                  85 Wayne Avenue, Ticonderoga, NY              US      maurewilliamscolombier.com                        Wayne Ave, Ticonderoga Townshiip, New York              US
        S1-965667      S3-860443364         Maure Williams Colombier Inc                                  85 Wayne Avenue, Ticonderoga, NY              US       Maure Williams Inc Center                                                               NaN              US
      S1-55344266      S2-249013014                  Raj Investments LLP 6(29), C.I.T. Colony, 2Nd Main Road Mylapore, Chennai, Tamil Nadu           India ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி 6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, CHENNAI, Tamil Nadu           India
      S1-55344266      S2-197070651                  Raj Investments LLP 6(29), C.I.T. Colony, 2Nd Main Road Mylapore, Chennai, Tamil Nadu           India             Raj Investments LLP 6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, CHENNAI, Tamil Nadu           India
      S1-55344266      S3-478195123                  Raj Investments LLP 6(29), C.I.T. Colony, 2Nd Main Road Mylapore, Chennai, Tamil Nadu           India        Raj Investments எல்எல்பி         6(29), C.i.t. Colony, 2Nd Main Road Mylapore, Chennai, TN           India
      S1-55344266      S3-384364074                  Raj Investments LLP 6(29), C.I.T. Colony, 2Nd Main Road Mylapore, Chennai, Tamil Nadu           India ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி  6(29), C.i.t. Colony, 2Nd Main Road Mylapore, Chennai, தமிழ்நாடு           India
     S1-343815751      S2-790675320 Dahlia Power Reliable Scientific LLC                                 630 45th Terrace, Kansas City, MO              US           Dahlia Power Reliable                           KANSAS CITY, MO, 630 45ND TERRACE, null              US

In [21]:
import re

def normalize_text(text):
    if pd.isna(text):
        return ""
    
    text = str(text).lower()
    text = re.sub(r'[^a-z0-9]+', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

# Sirf sample pairs par test
test_norm = sample_pairs.copy()

test_norm["source1_name_norm"] = test_norm["source1_name"].apply(normalize_text)
test_norm["matched_name_norm"] = test_norm["matched_name"].apply(normalize_text)

test_norm["source1_address_norm"] = test_norm["source1_address"].apply(normalize_text)
test_norm["matched_address_norm"] = test_norm["matched_address"].apply(normalize_text)

print(
    test_norm[
        [
            "source1_name",
            "source1_name_norm",
            "matched_name",
            "matched_name_norm",
            "source1_address_norm",
            "matched_address_norm"
        ]
    ].to_string(index=False)
)

                        source1_name                    source1_name_norm                    matched_name            matched_name_norm                                        source1_address_norm                                        matched_address_norm
        Maure Williams Colombier Inc         maure williams colombier inc    Maure Wilblims Colombier Inc maure wilblims colombier inc                              85 wayne avenue ticonderoga ny
        Maure Williams Colombier Inc         maure williams colombier inc        Maure Williams Colombier     maure williams colombier                              85 wayne avenue ticonderoga ny
        Maure Williams Colombier Inc         maure williams colombier inc                         Dréxkor                      dr xkor                              85 wayne avenue ticonderoga ny              85 wanye avenue ticonderoga townshiip new york
        Maure Williams Colombier Inc         maure williams colombier inc      maurewilliamscolombier.com   maurewilliamscolombier com                              85 wayne avenue ticonderoga ny                    wayne ave ticonderoga townshiip new york
        Maure Williams Colombier Inc         maure williams colombier inc       Maure Williams Inc Center    maure williams inc center                              85 wayne avenue ticonderoga ny
                 Raj Investments LLP                  raj investments llp ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி                              6 29 c i t colony 2nd main road mylapore chennai tamil nadu 6 29 c i t colony 2nd main road mylapore chennai tamil nadu
                 Raj Investments LLP                  raj investments llp             Raj Investments LLP          raj investments llp 6 29 c i t colony 2nd main road mylapore chennai tamil nadu 6 29 c i t colony 2nd main road mylapore chennai tamil nadu
                 Raj Investments LLP                  raj investments llp        Raj Investments எல்எல்பி              raj investments 6 29 c i t colony 2nd main road mylapore chennai tamil nadu         6 29 c i t colony 2nd main road mylapore chennai tn
                 Raj Investments LLP                  raj investments llp ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி                              6 29 c i t colony 2nd main road mylapore chennai tamil nadu            6 29 c i t colony 2nd main road mylapore chennai
Dahlia Power Reliable Scientific LLC dahlia power reliable scientific llc           Dahlia Power Reliable        dahlia power reliable                             630 45th terrace kansas city mo                        kansas city mo 630 45nd terrace null

In [22]:
from difflib import SequenceMatcher

def similarity(a, b):
    if not a or not b:
        return 0.0
    return SequenceMatcher(None, a, b).ratio()


test_norm["name_similarity"] = test_norm.apply(
    lambda x: similarity(
        x["source1_name_norm"],
        x["matched_name_norm"]
    ),
    axis=1
)

test_norm["address_similarity"] = test_norm.apply(
    lambda x: similarity(
        x["source1_address_norm"],
        x["matched_address_norm"]
    ),
    axis=1
)

test_norm["country_match"] = (
    test_norm["source1_country"] ==
    test_norm["matched_country"]
).astype(int)

print(
    test_norm[
        [
            "source1_name",
            "matched_name",
            "name_similarity",
            "source1_address",
            "matched_address",
            "address_similarity",
            "country_match"
        ]
    ].to_string(index=False)
)

                        source1_name                    matched_name  name_similarity                                                   source1_address                                                   matched_address  address_similarity  country_match
        Maure Williams Colombier Inc    Maure Wilblims Colombier Inc         0.964286                                  85 Wayne Avenue, Ticonderoga, NY                                                               NaN            0.000000              1
        Maure Williams Colombier Inc        Maure Williams Colombier         0.923077                                  85 Wayne Avenue, Ticonderoga, NY                                                               NaN            0.000000              1
        Maure Williams Colombier Inc                         Dréxkor         0.114286                                  85 Wayne Avenue, Ticonderoga, NY                  85 Wanye Avenue, Ticonderoga Townshiip, New York            0.763158              1
        Maure Williams Colombier Inc      maurewilliamscolombier.com         0.888889                                  85 Wayne Avenue, Ticonderoga, NY                        Wayne Ave, Ticonderoga Townshiip, New York            0.685714              1
        Maure Williams Colombier Inc       Maure Williams Inc Center         0.679245                                  85 Wayne Avenue, Ticonderoga, NY                                                               NaN            0.000000              1
                 Raj Investments LLP ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி         0.000000 6(29), C.I.T. Colony, 2Nd Main Road Mylapore, Chennai, Tamil Nadu 6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, CHENNAI, Tamil Nadu            1.000000              1
                 Raj Investments LLP             Raj Investments LLP         1.000000 6(29), C.I.T. Colony, 2Nd Main Road Mylapore, Chennai, Tamil Nadu 6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, CHENNAI, Tamil Nadu            1.000000              1
                 Raj Investments LLP        Raj Investments எல்எல்பி         0.882353 6(29), C.I.T. Colony, 2Nd Main Road Mylapore, Chennai, Tamil Nadu         6(29), C.i.t. Colony, 2Nd Main Road Mylapore, Chennai, TN            0.927273              1
                 Raj Investments LLP ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி         0.000000 6(29), C.I.T. Colony, 2Nd Main Road Mylapore, Chennai, Tamil Nadu  6(29), C.i.t. Colony, 2Nd Main Road Mylapore, Chennai, தமிழ்நாடு            0.897196              1
Dahlia Power Reliable Scientific LLC           Dahlia Power Reliable         0.736842                                 630 45th Terrace, Kansas City, MO                           KANSAS CITY, MO, 630 45ND TERRACE, null            0.417910              1

In [23]:
# Positive pairs ke sample mein feature statistics

print("Positive pairs statistics:")
print()

print("Name similarity:")
print(test_norm["name_similarity"].describe())

print("\nAddress similarity:")
print(test_norm["address_similarity"].describe())

print("\nCountry match:")
print(test_norm["country_match"].value_counts())

Positive pairs statistics:

Name similarity:
count    10.000000
mean      0.618898
std       0.413335
min       0.000000
25%       0.255526
50%       0.809598
75%       0.914530
max       1.000000
Name: name_similarity, dtype: float64

Address similarity:
count    10.000000
mean      0.569125
std       0.428567
min       0.000000
25%       0.104478
50%       0.724436
75%       0.919754
max       1.000000
Name: address_similarity, dtype: float64

Country match:
country_match
1    10
Name: count, dtype: int64

In [24]:
# Actual positive pairs ka sample
positive_sample = pairs_df.sample(
    n=min(5000, len(pairs_df)),
    random_state=42
).copy()

print("Positive samples:", len(positive_sample))
print(positive_sample.head())

Positive samples: 5000
        source1_entity_id matched_entity_id
5812144      S1-341462203      S2-219553948
1769771      S1-783955316      S3-656241763
2521555      S1-313221336      S3-872559960
3756225      S1-516394603      S2-642842175
315955       S1-887045319      S2-612158384

In [ ]:
# Har Source 1 entity ke actual matched IDs ka set banana

true_matches = {}

for _, row in train_ground_truth.dropna(
    subset=["matched_entity_ids"]
).iterrows():

    s1_id = row["source1_entity_id"]

    matched_ids = set(
        row["matched_entity_ids"].split(",")
    )

    true_matches[s1_id] = matched_ids

print("Total Source 1 entities with matches:", len(true_matches))

# Example
example_id = positive_sample.iloc[0]["source1_entity_id"]

print("\nExample Source 1 ID:", example_id)
print("Actual matched IDs:", true_matches.get(example_id, set()))

In [ ]:
import numpy as np

# S2 + S3 ko ek table mein combine karo
source23 = pd.concat(
    [
        train_source2[["entity_id", "business_name", "business_address", "country"]],
        train_source3[["entity_id", "business_name", "business_address", "country"]]
    ],
    ignore_index=True
)

# Fast ID -> row lookup
source23_ids = source23["entity_id"].values

# Country ke according IDs
country_to_ids = (
    source23.groupby("country")["entity_id"]
    .apply(list)
    .to_dict()
)

rng = np.random.default_rng(42)

negative_pairs = []

for s1_id in positive_sample["source1_entity_id"]:
    
    # Source 1 ki country
    s1_row = train_source1.loc[
        train_source1["entity_id"] == s1_id
    ].iloc[0]
    
    country = s1_row["country"]
    
    # Same country ke candidates
    candidates = country_to_ids.get(country, [])
    
    if not candidates:
        continue
    
    # Random ID choose karo
    while True:
        candidate_id = candidates[
            rng.integers(0, len(candidates))
        ]
        
        # Check karo ki ye actual match na ho
        if candidate_id not in true_matches.get(s1_id, set()):
            break
    
    negative_pairs.append(
        (s1_id, candidate_id)
    )

negative_sample = pd.DataFrame(
    negative_pairs,
    columns=["source1_entity_id", "matched_entity_id"]
)

print("Negative samples:", len(negative_sample))
print("\nFirst 10 negative pairs:")
print(negative_sample.head(10))

In [ ]:
# Fast negative sampling

# Source 1 ID -> country lookup
s1_country = train_source1.set_index("entity_id")["country"].to_dict()

# Same-country S2/S3 IDs already available in country_to_ids

rng = np.random.default_rng(42)

negative_pairs = []

for s1_id in positive_sample["source1_entity_id"]:

    country = s1_country[s1_id]

    candidates = country_to_ids.get(country, [])

    # Random candidate until it is not a true match
    true_ids = true_matches.get(s1_id, set())

    while True:
        candidate_id = candidates[
            rng.integers(0, len(candidates))
        ]

        if candidate_id not in true_ids:
            break

    negative_pairs.append(
        (s1_id, candidate_id)
    )

negative_sample = pd.DataFrame(
    negative_pairs,
    columns=["source1_entity_id", "matched_entity_id"]
)

print("Negative samples:", len(negative_sample))
print("\nFirst 10 negative pairs:")
print(negative_sample.head(10))

In [ ]:
# Positive + Negative pairs combine

positive_sample["label"] = 1
negative_sample["label"] = 0

training_pairs = pd.concat(
    [positive_sample, negative_sample],
    ignore_index=True
)

# Shuffle
training_pairs = training_pairs.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

print("Total training pairs:", len(training_pairs))
print("\nLabel distribution:")
print(training_pairs["label"].value_counts())

print("\nSample:")
print(training_pairs.head(10))

In [ ]:
from difflib import SequenceMatcher
import re

# S1 aur S2/S3 ka data lookup dictionary
s1_data = train_source1.set_index("entity_id").to_dict("index")
source23_data = source23.set_index("entity_id").to_dict("index")


def normalize_text(text):
    if pd.isna(text):
        return ""
    
    text = str(text).lower()
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def similarity(a, b):
    if not a or not b:
        return 0.0
    return SequenceMatcher(None, a, b).ratio()


def token_similarity(a, b):
    if not a or not b:
        return 0.0
    
    tokens_a = set(a.split())
    tokens_b = set(b.split())
    
    if not tokens_a or not tokens_b:
        return 0.0
    
    intersection = len(tokens_a & tokens_b)
    union = len(tokens_a | tokens_b)
    
    return intersection / union


def number_overlap(a, b):
    nums_a = set(re.findall(r'\d+', a))
    nums_b = set(re.findall(r'\d+', b))
    
    if not nums_a or not nums_b:
        return 0.0
    
    return len(nums_a & nums_b) / len(nums_a | nums_b)


features = []

for _, row in training_pairs.iterrows():

    s1 = s1_data[row["source1_entity_id"]]
    s2 = source23_data[row["matched_entity_id"]]

    name1 = normalize_text(s1["business_name"])
    name2 = normalize_text(s2["business_name"])

    address1 = normalize_text(s1["business_address"])
    address2 = normalize_text(s2["business_address"])

    features.append({
        "name_similarity": similarity(name1, name2),
        "address_similarity": similarity(address1, address2),
        "name_token_similarity": token_similarity(name1, name2),
        "address_token_similarity": token_similarity(address1, address2),
        "number_overlap": number_overlap(address1, address2),
        "country_match": int(s1["country"] == s2["country"]),
        "source1_address_missing": int(not address1),
        "candidate_address_missing": int(not address2),
        "label": row["label"]
    })


training_features = pd.DataFrame(features)

print("Feature shape:", training_features.shape)

print("\nColumns:")
print(training_features.columns.tolist())

print("\nFirst 10 rows:")
print(training_features.head(10))

print("\nLabel distribution:")
print(training_features["label"].value_counts())

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Features aur target
X = training_features.drop(columns=["label"])
y = training_features["label"]

# 80% training, 20% validation
X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Validation samples:", len(X_val))

# Random Forest
model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

model.fit(X_train, y_train)

# Validation prediction
y_pred = model.predict(X_val)

print("\nAccuracy:", accuracy_score(y_val, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_val, y_pred))

print("\nClassification Report:")
print(classification_report(y_val, y_pred))

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Positive class probability
val_prob = model.predict_proba(X_val)[:, 1]

for threshold in [0.50, 0.60, 0.70, 0.80, 0.90]:

    pred = (val_prob >= threshold).astype(int)

    precision = precision_score(y_val, pred, zero_division=0)
    recall = recall_score(y_val, pred, zero_division=0)
    f1 = f1_score(y_val, pred, zero_division=0)

    print(
        f"Threshold {threshold:.2f} "
        f"| Precision: {precision:.4f} "
        f"| Recall: {recall:.4f} "
        f"| F1: {f1:.4f}"
    )

In [ ]:
import re
import pandas as pd

def block_name(text):
    if pd.isna(text):
        return ""
    
    text = str(text).lower()
    text = re.sub(r'[^a-z0-9]+', '', text)
    
    return text[:5]


# Source 1 ke liye block key
train_source1["block_key"] = (
    train_source1["country"].fillna("").astype(str)
    + "_"
    + train_source1["business_name"].apply(block_name)
)

# Source 2 + Source 3
source23 = pd.concat(
    [
        train_source2[["entity_id", "business_name", "business_address", "country"]],
        train_source3[["entity_id", "business_name", "business_address", "country"]]
    ],
    ignore_index=True
)

source23["block_key"] = (
    source23["country"].fillna("").astype(str)
    + "_"
    + source23["business_name"].apply(block_name)
)

# Positive pairs ke liye block key check
check_pairs = positive_sample.copy()

s1_keys = train_source1.set_index("entity_id")["block_key"].to_dict()
s23_keys = source23.set_index("entity_id")["block_key"].to_dict()

check_pairs["s1_block"] = check_pairs["source1_entity_id"].map(s1_keys)
check_pairs["s23_block"] = check_pairs["matched_entity_id"].map(s23_keys)

check_pairs["same_block"] = (
    check_pairs["s1_block"] == check_pairs["s23_block"]
)

print("Total positive samples:", len(check_pairs))
print("Captured by name blocking:", check_pairs["same_block"].sum())
print(
    "Blocking coverage:",
    round(check_pairs["same_block"].mean() * 100, 2),
    "%"
)

In [ ]:
def block_address(text):
    if pd.isna(text):
        return ""
    
    text = str(text).lower()
    text = re.sub(r'[^a-z0-9]+', '', text)
    
    return text[:6]


# Address block keys
train_source1["address_block"] = (
    train_source1["country"].fillna("").astype(str)
    + "_"
    + train_source1["business_address"].apply(block_address)
)

source23["address_block"] = (
    source23["country"].fillna("").astype(str)
    + "_"
    + source23["business_address"].apply(block_address)
)

# Dictionaries
s1_address_keys = train_source1.set_index("entity_id")["address_block"].to_dict()
s23_address_keys = source23.set_index("entity_id")["address_block"].to_dict()

# Add address blocks
check_pairs["s1_address_block"] = (
    check_pairs["source1_entity_id"].map(s1_address_keys)
)

check_pairs["s23_address_block"] = (
    check_pairs["matched_entity_id"].map(s23_address_keys)
)

# Address match
check_pairs["same_address_block"] = (
    check_pairs["s1_address_block"] == check_pairs["s23_address_block"]
)

# Name OR Address
check_pairs["captured"] = (
    check_pairs["same_block"] |
    check_pairs["same_address_block"]
)

print("Total positive samples:", len(check_pairs))
print("Captured by name + address blocking:", check_pairs["captured"].sum())
print(
    "Blocking coverage:",
    round(check_pairs["captured"].mean() * 100, 2),
    "%"
)

In [ ]:
def number_block(text):
    if pd.isna(text):
        return ""
    
    nums = re.findall(r'\d+', str(text))
    
    if not nums:
        return ""
    
    return "_".join(nums[:2])


train_source1["number_block"] = (
    train_source1["country"].fillna("").astype(str)
    + "_"
    + train_source1["business_address"].apply(number_block)
)

source23["number_block"] = (
    source23["country"].fillna("").astype(str)
    + "_"
    + source23["business_address"].apply(number_block)
)


s1_number_keys = train_source1.set_index("entity_id")["number_block"].to_dict()
s23_number_keys = source23.set_index("entity_id")["number_block"].to_dict()


check_pairs["s1_number_block"] = (
    check_pairs["source1_entity_id"].map(s1_number_keys)
)

check_pairs["s23_number_block"] = (
    check_pairs["matched_entity_id"].map(s23_number_keys)
)


check_pairs["same_number_block"] = (
    (check_pairs["s1_number_block"] == check_pairs["s23_number_block"])
    & (check_pairs["s1_number_block"] != "")
)


check_pairs["captured_final"] = (
    check_pairs["same_block"]
    | check_pairs["same_address_block"]
    | check_pairs["same_number_block"]
)


print("Total positive samples:", len(check_pairs))
print("Captured by name + address + number:",
      check_pairs["captured_final"].sum())

print(
    "Blocking coverage:",
    round(check_pairs["captured_final"].mean() * 100, 2),
    "%"
)

In [ ]:
missed = check_pairs[~check_pairs["captured_final"]].copy()

print("Missed positive matches:", len(missed))

print("\nSample missed matches:")
print(
    missed[
        [
            "source1_entity_id",
            "matched_entity_id",
            "s1_block",
            "s23_block",
            "s1_address_block",
            "s23_address_block",
            "s1_number_block",
            "s23_number_block"
        ]
    ].head(20)
)

In [ ]:
# Source 1 aur Source 2/3 ka actual data lookup
s1_lookup = train_source1.set_index("entity_id")
s23_lookup = source23.set_index("entity_id")

missed_details = []

for _, row in missed.head(30).iterrows():

    s1 = s1_lookup.loc[row["source1_entity_id"]]
    s23 = s23_lookup.loc[row["matched_entity_id"]]

    missed_details.append({
        "source1_id": row["source1_entity_id"],
        "matched_id": row["matched_entity_id"],

        "source1_name": s1["business_name"],
        "matched_name": s23["business_name"],

        "source1_address": s1["business_address"],
        "matched_address": s23["business_address"],

        "source1_country": s1["country"],
        "matched_country": s23["country"]
    })

missed_details_df = pd.DataFrame(missed_details)

pd.set_option("display.max_colwidth", 100)

print(missed_details_df.to_string(index=False))

In [ ]:
# ==============================
# FAST BLOCKING SETUP
# ==============================

import pandas as pd
import re

def clean_block(text):
    if pd.isna(text):
        return ""
    
    text = str(text).lower()
    text = re.sub(r'[^a-z0-9]+', '', text)
    return text


def name_key(text):
    text = clean_block(text)
    return text[:4]


def address_key(text):
    text = clean_block(text)
    return text[:6]


# TEST Source 1
test_source1["name_key"] = (
    test_source1["country"].fillna("").astype(str)
    + "_"
    + test_source1["business_name"].apply(name_key)
)

test_source1["address_key"] = (
    test_source1["country"].fillna("").astype(str)
    + "_"
    + test_source1["business_address"].apply(address_key)
)


# TEST Source 2 + Source 3
test_source23 = pd.concat(
    [
        test_source2[["entity_id", "business_name", "business_address", "country"]],
        test_source3[["entity_id", "business_name", "business_address", "country"]]
    ],
    ignore_index=True
)

test_source23["name_key"] = (
    test_source23["country"].fillna("").astype(str)
    + "_"
    + test_source23["business_name"].apply(name_key)
)

test_source23["address_key"] = (
    test_source23["country"].fillna("").astype(str)
    + "_"
    + test_source23["business_address"].apply(address_key)
)


print("Test Source 1:", len(test_source1))
print("Test Source 2:", len(test_source2))
print("Test Source 3:", len(test_source3))
print("Total candidates source:", len(test_source23))

In [ ]:
# ==========================================
# FAST CANDIDATE INDEX
# ==========================================

from collections import defaultdict

name_index = defaultdict(list)
address_index = defaultdict(list)

# Source 2 + Source 3 ko index karo
for row in test_source23[
    ["entity_id", "name_key", "address_key"]
].itertuples(index=False):

    entity_id, nk, ak = row

    if nk:
        name_index[nk].append(entity_id)

    if ak:
        address_index[ak].append(entity_id)

print("Name index keys:", len(name_index))
print("Address index keys:", len(address_index))

print("Index ready.")

In [ ]:
# ==========================================
# GENERATE TEST CANDIDATES
# ==========================================

candidate_rows = []

for row in test_source1[
    ["entity_id", "name_key", "address_key"]
].itertuples(index=False):

    s1_id, nk, ak = row

    candidates = set()

    # Name based candidates
    if nk in name_index:
        candidates.update(name_index[nk])

    # Address based candidates
    if ak in address_index:
        candidates.update(address_index[ak])

    # Save candidates
    candidate_rows.append(
        (
            s1_id,
            ",".join(candidates)
        )
    )


candidate_pairs = pd.DataFrame(
    candidate_rows,
    columns=["source1_entity_id", "candidate_entity_ids"]
)

print("Source1 entities:", len(candidate_pairs))

print(
    "Entities having candidates:",
    (candidate_pairs["candidate_entity_ids"] != "").sum()
)

print(
    "Entities without candidates:",
    (candidate_pairs["candidate_entity_ids"] == "").sum()
)

print("\nSample:")
print(candidate_pairs.head())

In [ ]:
# FAST candidate generation using pandas merge

name_candidates = test_source1[
    ["entity_id", "name_key"]
].merge(
    test_source23[
        ["entity_id", "name_key"]
    ],
    on="name_key",
    how="left",
    suffixes=("_s1", "_candidate")
)

name_candidates = name_candidates.rename(
    columns={
        "entity_id_s1": "source1_entity_id",
        "entity_id_candidate": "candidate_entity_id"
    }
)

print("Name candidates:", len(name_candidates))

In [ ]:
import pandas as pd
import os

base = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0"

test_source1 = pd.read_csv(
    base + "/dataset/test/test_source1.tsv",
    sep="\t"
)

test_source2 = pd.read_csv(
    base + "/dataset/test/test_source2.tsv",
    sep="\t"
)

test_source3 = pd.read_csv(
    base + "/dataset/test/test_source3.tsv",
    sep="\t"
)

print("S1:", test_source1.shape)
print("S2:", test_source2.shape)
print("S3:", test_source3.shape)

In [ ]:
import duckdb

print("DuckDB version:", duckdb.__version__)
print("DuckDB ready")

In [ ]:
import duckdb

base = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0"

con = duckdb.connect()

s1_path = base + "/dataset/test/test_source1.tsv"
s2_path = base + "/dataset/test/test_source2.tsv"
s3_path = base + "/dataset/test/test_source3.tsv"

print("Checking files...")

print("S1:", con.execute(
    f"SELECT COUNT(*) FROM read_csv_auto('{s1_path}', delim='\\t')"
).fetchone()[0])

print("S2:", con.execute(
    f"SELECT COUNT(*) FROM read_csv_auto('{s2_path}', delim='\\t')"
).fetchone()[0])

print("S3:", con.execute(
    f"SELECT COUNT(*) FROM read_csv_auto('{s3_path}', delim='\\t')"
).fetchone()[0])

print("DuckDB test successful")

In [ ]:
# ==========================================
# CHECK BLOCK SIZES - DUCKDB
# ==========================================

def clean_sql(col):
    return f"""
        regexp_replace(
            lower(coalesce(CAST({col} AS VARCHAR), '')),
            '[^a-zA-Z0-9]',
            '',
            'g'
        )
    """

s1_name = clean_sql("business_name")
s23_name = clean_sql("business_name")

query = f"""
WITH
s1 AS (
    SELECT
        entity_id,
        country,
        left({s1_name}, 4) AS name_key
    FROM read_csv_auto('{s1_path}', delim='\\t')
),

s23 AS (
    SELECT
        entity_id,
        country,
        left({s23_name}, 4) AS name_key
    FROM read_csv_auto('{s2_path}', delim='\\t')

    UNION ALL

    SELECT
        entity_id,
        country,
        left({s23_name}, 4) AS name_key
    FROM read_csv_auto('{s3_path}', delim='\\t')
),

blocks AS (
    SELECT
        country || '_' || name_key AS block_key,
        COUNT(*) AS candidate_count
    FROM s23
    WHERE name_key <> ''
    GROUP BY 1
)

SELECT
    COUNT(*) AS total_blocks,
    MAX(candidate_count) AS largest_block,
    AVG(candidate_count) AS average_block,
    COUNT(*) FILTER (WHERE candidate_count > 1000) AS blocks_over_1000,
    COUNT(*) FILTER (WHERE candidate_count > 10000) AS blocks_over_10000
FROM blocks
"""

result = con.execute(query).fetchdf()

print(result)

In [ ]:
# ==========================================
# SAFE NAME CANDIDATE GENERATION
# ==========================================

# Recreate connection if needed
import duckdb

con = duckdb.connect()

# Give DuckDB a controlled memory limit
con.execute("SET memory_limit='12GB'")
con.execute("SET threads=4")

query = f"""
COPY (
    WITH
    s1 AS (
        SELECT
            entity_id AS source1_entity_id,
            country,
            business_name,
            regexp_replace(
                lower(coalesce(CAST(business_name AS VARCHAR), '')),
                '[^a-zA-Z0-9]',
                '',
                'g'
            ) AS clean_name
        FROM read_csv_auto('{s1_path}', delim='\\t')
    ),

    s23 AS (
        SELECT
            entity_id AS candidate_entity_id,
            country,
            business_name,
            regexp_replace(
                lower(coalesce(CAST(business_name AS VARCHAR), '')),
                '[^a-zA-Z0-9]',
                '',
                'g'
            ) AS clean_name
        FROM read_csv_auto('{s2_path}', delim='\\t')

        UNION ALL

        SELECT
            entity_id AS candidate_entity_id,
            country,
            business_name,
            regexp_replace(
                lower(coalesce(CAST(business_name AS VARCHAR), '')),
                '[^a-zA-Z0-9]',
                '',
                'g'
            ) AS clean_name
        FROM read_csv_auto('{s3_path}', delim='\\t')
    ),

    joined AS (
        SELECT
            s1.source1_entity_id,
            s23.candidate_entity_id,

            levenshtein(
                left(s1.clean_name, 30),
                left(s23.clean_name, 30)
            ) AS name_distance

        FROM s1
        JOIN s23
          ON s1.country = s23.country
         AND left(s1.clean_name, 5) = left(s23.clean_name, 5)

        WHERE s1.clean_name <> ''
          AND s23.clean_name <> ''
    ),

    ranked AS (
        SELECT
            source1_entity_id,
            candidate_entity_id,
            name_distance,

            ROW_NUMBER() OVER (
                PARTITION BY source1_entity_id
                ORDER BY name_distance, candidate_entity_id
            ) AS rn

        FROM joined
    )

    SELECT
        source1_entity_id,
        candidate_entity_id
    FROM ranked
    WHERE rn <= 50
)
TO '/kaggle/working/name_candidates.tsv'
(HEADER, DELIMITER '\\t');
"""

print("Candidate generation started...")
con.execute(query)

print("DONE")
print("File created:")
print("/kaggle/working/name_candidates.tsv")

In [ ]:
# SAFE SETTINGS
con.execute("SET memory_limit='12GB'")
con.execute("SET threads=2")
con.execute("SET preserve_insertion_order=false")
con.execute("SET max_temp_directory_size='4GB'")

print("DuckDB safe settings applied")

In [ ]:
import os

# Checkpoint folder
os.makedirs("/kaggle/working/candidates", exist_ok=True)

print("Starting safe batch candidate generation...")
print("Output folder: /kaggle/working/candidates")

In [ ]:
# SAFE TEST: first 5,000 Source-1 records

query_test = f"""
COPY (
    WITH s1 AS (
        SELECT
            entity_id AS source1_entity_id,
            business_name,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s1_path}', delim='\\t')
        LIMIT 5000
    ),

    s23 AS (
        SELECT
            entity_id AS candidate_entity_id,
            business_name,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s2_path}', delim='\\t')

        UNION ALL

        SELECT
            entity_id AS candidate_entity_id,
            business_name,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s3_path}', delim='\\t')
    ),

    joined AS (
        SELECT
            s1.source1_entity_id,
            s23.candidate_entity_id,

            levenshtein(
                left(s1.clean_name, 30),
                left(s23.clean_name, 30)
            ) AS edit_distance

        FROM s1
        JOIN s23
          ON s1.country = s23.country
         AND length(s1.clean_name) >= 5
         AND length(s23.clean_name) >= 5
         AND left(s1.clean_name, 5) = left(s23.clean_name, 5)
    ),

    ranked AS (
        SELECT
            source1_entity_id,
            candidate_entity_id,
            edit_distance,
            row_number() OVER (
                PARTITION BY source1_entity_id
                ORDER BY edit_distance
            ) AS rn
        FROM joined
    )

    SELECT
        source1_entity_id,
        candidate_entity_id
    FROM ranked
    WHERE rn <= 50

) TO '/kaggle/working/candidates/name_candidates_test_5000.tsv'
(H HEADER, DELIMITER '\\t');
"""

print("Test batch started...")

con.execute(query_test)

print("TEST BATCH DONE")
print("File created:")
print("/kaggle/working/candidates/name_candidates_test_5000.tsv")

In [ ]:
# SAFE TEST: first 5,000 Source-1 records

query_test = f"""
COPY (
    WITH s1 AS (
        SELECT
            entity_id AS source1_entity_id,
            business_name,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s1_path}', delim='\\t')
        LIMIT 5000
    ),

    s23 AS (
        SELECT
            entity_id AS candidate_entity_id,
            business_name,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s2_path}', delim='\\t')

        UNION ALL

        SELECT
            entity_id AS candidate_entity_id,
            business_name,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s3_path}', delim='\\t')
    ),

    joined AS (
        SELECT
            s1.source1_entity_id,
            s23.candidate_entity_id,
            levenshtein(
                left(s1.clean_name, 30),
                left(s23.clean_name, 30)
            ) AS edit_distance
        FROM s1
        JOIN s23
          ON s1.country = s23.country
         AND length(s1.clean_name) >= 5
         AND length(s23.clean_name) >= 5
         AND left(s1.clean_name, 5) = left(s23.clean_name, 5)
    ),

    ranked AS (
        SELECT
            source1_entity_id,
            candidate_entity_id,
            edit_distance,
            row_number() OVER (
                PARTITION BY source1_entity_id
                ORDER BY edit_distance
            ) AS rn
        FROM joined
    )

    SELECT
        source1_entity_id,
        candidate_entity_id
    FROM ranked
    WHERE rn <= 50

) TO '/kaggle/working/candidates/name_candidates_test_5000.tsv'
(FORMAT CSV, HEADER TRUE, DELIMITER '\\t');
"""

print("Test batch started...")

con.execute(query_test)

print("TEST BATCH DONE")
print("File created:")
print("/kaggle/working/candidates/name_candidates_test_5000.tsv")

In [ ]:
# Check generated 5,000-row candidate file

result = con.execute("""
    SELECT
        COUNT(*) AS total_candidate_pairs,
        COUNT(DISTINCT source1_entity_id) AS source1_entities,
        MIN(cnt) AS minimum_candidates,
        MAX(cnt) AS maximum_candidates,
        AVG(cnt) AS average_candidates
    FROM (
        SELECT
            source1_entity_id,
            COUNT(*) AS cnt
        FROM read_csv_auto(
            '/kaggle/working/candidates/name_candidates_test_5000.tsv',
            delim='\t'
        )
        GROUP BY source1_entity_id
    )
""").fetchone()

print("Candidate file check:")
print("Total candidate pairs :", result[0])
print("Source1 entities      :", result[1])
print("Minimum candidates    :", result[2])
print("Maximum candidates    :", result[3])
print("Average candidates    :", round(result[4], 2))

In [ ]:
import os

file_path = "/kaggle/working/candidates/name_candidates_test_5000.tsv"

if os.path.exists(file_path):
    size_mb = os.path.getsize(file_path) / (1024 * 1024)

    print("CHECKPOINT SAVED")
    print("File:", file_path)
    print("Size:", round(size_mb, 2), "MB")
else:
    print("ERROR: File not found")

In [ ]:
import os

# Full test Source-1 count
total_s1 = con.execute(f"""
    SELECT COUNT(*)
    FROM read_csv_auto('{s1_path}', delim='\\t')
""").fetchone()[0]

batch_size = 5000
total_batches = (total_s1 + batch_size - 1) // batch_size

print("Total Source-1 records :", total_s1)
print("Batch size             :", batch_size)
print("Total batches          :", total_batches)
print("Output folder          :", "/kaggle/working/candidates")

In [ ]:
batch_no = 1
offset = 0
limit = 5000

output_file = f"/kaggle/working/candidates/name_candidates_batch_{batch_no:03d}.tsv"

query_batch = f"""
COPY (
    WITH s1 AS (
        SELECT
            entity_id AS source1_entity_id,
            business_name,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s1_path}', delim='\\t')
        LIMIT {limit} OFFSET {offset}
    ),

    s23 AS (
        SELECT
            entity_id AS candidate_entity_id,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s2_path}', delim='\\t')

        UNION ALL

        SELECT
            entity_id AS candidate_entity_id,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s3_path}', delim='\\t')
    ),

    joined AS (
        SELECT
            s1.source1_entity_id,
            s23.candidate_entity_id,
            levenshtein(
                left(s1.clean_name, 30),
                left(s23.clean_name, 30)
            ) AS edit_distance
        FROM s1
        JOIN s23
          ON s1.country = s23.country
         AND length(s1.clean_name) >= 5
         AND length(s23.clean_name) >= 5
         AND left(s1.clean_name, 5) = left(s23.clean_name, 5)
    ),

    ranked AS (
        SELECT
            source1_entity_id,
            candidate_entity_id,
            edit_distance,
            row_number() OVER (
                PARTITION BY source1_entity_id
                ORDER BY edit_distance
            ) AS rn
        FROM joined
    )

    SELECT
        source1_entity_id,
        candidate_entity_id
    FROM ranked
    WHERE rn <= 50

) TO '{output_file}'
(FORMAT CSV, HEADER TRUE, DELIMITER '\\t');
"""

print("Batch 1 started...")
print("Processing rows:", offset + 1, "to", offset + limit)

con.execute(query_batch)

print("BATCH 1 DONE")
print("File created:", output_file)

In [ ]:
import os

file_path = "/kaggle/working/candidates/name_candidates_batch_001.tsv"

# File check
if os.path.exists(file_path):
    size_mb = os.path.getsize(file_path) / (1024 * 1024)

    check = con.execute(f"""
        SELECT
            COUNT(*) AS total_pairs,
            COUNT(DISTINCT source1_entity_id) AS source1_entities
        FROM read_csv_auto('{file_path}', delim='\\t')
    """).fetchone()

    print("BATCH 1 CHECKPOINT VERIFIED")
    print("File size:", round(size_mb, 2), "MB")
    print("Candidate pairs:", check[0])
    print("Source1 entities:", check[1])
else:
    print("ERROR: Batch 1 file not found")

In [ ]:
batch_no = 2
offset = 5000
limit = 5000

output_file = f"/kaggle/working/candidates/name_candidates_batch_{batch_no:03d}.tsv"

query_batch = f"""
COPY (
    WITH s1 AS (
        SELECT
            entity_id AS source1_entity_id,
            business_name,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s1_path}', delim='\\t')
        LIMIT {limit} OFFSET {offset}
    ),

    s23 AS (
        SELECT
            entity_id AS candidate_entity_id,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s2_path}', delim='\\t')

        UNION ALL

        SELECT
            entity_id AS candidate_entity_id,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s3_path}', delim='\\t')
    ),

    joined AS (
        SELECT
            s1.source1_entity_id,
            s23.candidate_entity_id,
            levenshtein(
                left(s1.clean_name, 30),
                left(s23.clean_name, 30)
            ) AS edit_distance
        FROM s1
        JOIN s23
          ON s1.country = s23.country
         AND length(s1.clean_name) >= 5
         AND length(s23.clean_name) >= 5
         AND left(s1.clean_name, 5) = left(s23.clean_name, 5)
    ),

    ranked AS (
        SELECT
            source1_entity_id,
            candidate_entity_id,
            edit_distance,
            row_number() OVER (
                PARTITION BY source1_entity_id
                ORDER BY edit_distance
            ) AS rn
        FROM joined
    )

    SELECT
        source1_entity_id,
        candidate_entity_id
    FROM ranked
    WHERE rn <= 50

) TO '{output_file}'
(FORMAT CSV, HEADER TRUE, DELIMITER '\\t');
"""

print("Batch 2 started...")
print("Processing rows:", offset + 1, "to", offset + limit)

con.execute(query_batch)

print("BATCH 2 DONE")
print("File created:", output_file)

In [ ]:
# Verify Batch 2

import os

file_path = "/kaggle/working/candidates/name_candidates_batch_002.tsv"

if os.path.exists(file_path):
    size_mb = os.path.getsize(file_path) / (1024 * 1024)

    check = con.execute(f"""
        SELECT
            COUNT(*) AS total_pairs,
            COUNT(DISTINCT source1_entity_id) AS source1_entities
        FROM read_csv_auto('{file_path}', delim='\\t')
    """).fetchone()

    print("BATCH 2 CHECKPOINT VERIFIED")
    print("File size:", round(size_mb, 2), "MB")
    print("Candidate pairs:", check[0])
    print("Source1 entities:", check[1])
else:
    print("ERROR: Batch 2 file not found")

In [ ]:
batch_no = 3
offset = 10000
limit = 5000

output_file = f"/kaggle/working/candidates/name_candidates_batch_{batch_no:03d}.tsv"

query_batch = f"""
COPY (
    WITH s1 AS (
        SELECT
            entity_id AS source1_entity_id,
            business_name,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s1_path}', delim='\\t')
        LIMIT {limit} OFFSET {offset}
    ),

    s23 AS (
        SELECT
            entity_id AS candidate_entity_id,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s2_path}', delim='\\t')

        UNION ALL

        SELECT
            entity_id AS candidate_entity_id,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s3_path}', delim='\\t')
    ),

    joined AS (
        SELECT
            s1.source1_entity_id,
            s23.candidate_entity_id,
            levenshtein(
                left(s1.clean_name, 30),
                left(s23.clean_name, 30)
            ) AS edit_distance
        FROM s1
        JOIN s23
          ON s1.country = s23.country
         AND length(s1.clean_name) >= 5
         AND length(s23.clean_name) >= 5
         AND left(s1.clean_name, 5) = left(s23.clean_name, 5)
    ),

    ranked AS (
        SELECT
            source1_entity_id,
            candidate_entity_id,
            edit_distance,
            row_number() OVER (
                PARTITION BY source1_entity_id
                ORDER BY edit_distance
            ) AS rn
        FROM joined
    )

    SELECT
        source1_entity_id,
        candidate_entity_id
    FROM ranked
    WHERE rn <= 50

) TO '{output_file}'
(FORMAT CSV, HEADER TRUE, DELIMITER '\\t');
"""

print("Batch 3 started...")
print("Processing rows:", offset + 1, "to", offset + limit)

con.execute(query_batch)

print("BATCH 3 DONE")
print("File created:", output_file)

In [ ]:
import os

file_path = "/kaggle/working/candidates/name_candidates_batch_003.tsv"

if os.path.exists(file_path):
    size_mb = os.path.getsize(file_path) / (1024 * 1024)

    check = con.execute(f"""
        SELECT
            COUNT(*) AS total_pairs,
            COUNT(DISTINCT source1_entity_id) AS source1_entities
        FROM read_csv_auto('{file_path}', delim='\\t')
    """).fetchone()

    print("BATCH 3 CHECKPOINT VERIFIED")
    print("File size:", round(size_mb, 2), "MB")
    print("Candidate pairs:", check[0])
    print("Source1 entities:", check[1])
else:
    print("ERROR: Batch 3 file not found")

In [ ]:
batch_no = 4
offset = 15000
limit = 5000

output_file = f"/kaggle/working/candidates/name_candidates_batch_{batch_no:03d}.tsv"

query_batch = f"""
COPY (
    WITH s1 AS (
        SELECT
            entity_id AS source1_entity_id,
            business_name,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s1_path}', delim='\\t')
        LIMIT {limit} OFFSET {offset}
    ),

    s23 AS (
        SELECT
            entity_id AS candidate_entity_id,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s2_path}', delim='\\t')

        UNION ALL

        SELECT
            entity_id AS candidate_entity_id,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s3_path}', delim='\\t')
    ),

    joined AS (
        SELECT
            s1.source1_entity_id,
            s23.candidate_entity_id,
            levenshtein(
                left(s1.clean_name, 30),
                left(s23.clean_name, 30)
            ) AS edit_distance
        FROM s1
        JOIN s23
          ON s1.country = s23.country
         AND length(s1.clean_name) >= 5
         AND length(s23.clean_name) >= 5
         AND left(s1.clean_name, 5) = left(s23.clean_name, 5)
    ),

    ranked AS (
        SELECT
            source1_entity_id,
            candidate_entity_id,
            edit_distance,
            row_number() OVER (
                PARTITION BY source1_entity_id
                ORDER BY edit_distance
            ) AS rn
        FROM joined
    )

    SELECT
        source1_entity_id,
        candidate_entity_id
    FROM ranked
    WHERE rn <= 50

) TO '{output_file}'
(FORMAT CSV, HEADER TRUE, DELIMITER '\\t');
"""

print("Batch 4 started...")
print("Processing rows:", offset + 1, "to", offset + limit)

con.execute(query_batch)

print("BATCH 4 DONE")
print("File created:", output_file)

In [ ]:
# Verify Batch 4

import os

file_path = "/kaggle/working/candidates/name_candidates_batch_004.tsv"

if os.path.exists(file_path):
    size_mb = os.path.getsize(file_path) / (1024 * 1024)

    check = con.execute(f"""
        SELECT
            COUNT(*) AS total_pairs,
            COUNT(DISTINCT source1_entity_id) AS source1_entities
        FROM read_csv_auto('{file_path}', delim='\\t')
    """).fetchone()

    print("BATCH 4 CHECKPOINT VERIFIED")
    print("File size:", round(size_mb, 2), "MB")
    print("Candidate pairs:", check[0])
    print("Source1 entities:", check[1])
else:
    print("ERROR: Batch 4 file not found")

In [ ]:
batch_no = 5
offset = 20000
limit = 5000

output_file = f"/kaggle/working/candidates/name_candidates_batch_{batch_no:03d}.tsv"

query_batch = f"""
COPY (
    WITH s1 AS (
        SELECT
            entity_id AS source1_entity_id,
            business_name,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s1_path}', delim='\\t')
        LIMIT {limit} OFFSET {offset}
    ),

    s23 AS (
        SELECT
            entity_id AS candidate_entity_id,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s2_path}', delim='\\t')

        UNION ALL

        SELECT
            entity_id AS candidate_entity_id,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s3_path}', delim='\\t')
    ),

    joined AS (
        SELECT
            s1.source1_entity_id,
            s23.candidate_entity_id,
            levenshtein(
                left(s1.clean_name, 30),
                left(s23.clean_name, 30)
            ) AS edit_distance
        FROM s1
        JOIN s23
          ON s1.country = s23.country
         AND length(s1.clean_name) >= 5
         AND length(s23.clean_name) >= 5
         AND left(s1.clean_name, 5) = left(s23.clean_name, 5)
    ),

    ranked AS (
        SELECT
            source1_entity_id,
            candidate_entity_id,
            edit_distance,
            row_number() OVER (
                PARTITION BY source1_entity_id
                ORDER BY edit_distance
            ) AS rn
        FROM joined
    )

    SELECT
        source1_entity_id,
        candidate_entity_id
    FROM ranked
    WHERE rn <= 50

) TO '{output_file}'
(FORMAT CSV, HEADER TRUE, DELIMITER '\\t');
"""

print("Batch 5 started...")
print("Processing rows:", offset + 1, "to", offset + limit)

con.execute(query_batch)

print("BATCH 5 DONE")
print("File created:", output_file)

In [ ]:
import os
import time

batch_size = 5000
total_s1 = 1732544
total_batches = (total_s1 + batch_size - 1) // batch_size

print("Starting automated batches from Batch 6...")
print("Total batches:", total_batches)

for batch_no in range(6, total_batches + 1):

    offset = (batch_no - 1) * batch_size
    limit = min(batch_size, total_s1 - offset)

    output_file = f"/kaggle/working/candidates/name_candidates_batch_{batch_no:03d}.tsv"

    # Already completed batch -> skip
    if os.path.exists(output_file):
        print(f"Batch {batch_no}: already exists -> SKIPPED")
        continue

    print(f"\nBatch {batch_no}/{total_batches} started")
    print(f"Rows: {offset + 1} to {offset + limit}")

    query_batch = f"""
    COPY (
        WITH s1 AS (
            SELECT
                entity_id AS source1_entity_id,
                business_name,
                country,
                regexp_replace(
                    lower(coalesce(business_name, '')),
                    '[^a-zA-Z0-9]', '', 'g'
                ) AS clean_name
            FROM read_csv_auto('{s1_path}', delim='\\t')
            LIMIT {limit} OFFSET {offset}
        ),

        s23 AS (
            SELECT
                entity_id AS candidate_entity_id,
                country,
                regexp_replace(
                    lower(coalesce(business_name, '')),
                    '[^a-zA-Z0-9]', '', 'g'
                ) AS clean_name
            FROM read_csv_auto('{s2_path}', delim='\\t')

            UNION ALL

            SELECT
                entity_id AS candidate_entity_id,
                country,
                regexp_replace(
                    lower(coalesce(business_name, '')),
                    '[^a-zA-Z0-9]', '', 'g'
                ) AS clean_name
            FROM read_csv_auto('{s3_path}', delim='\\t')
        ),

        joined AS (
            SELECT
                s1.source1_entity_id,
                s23.candidate_entity_id,
                levenshtein(
                    left(s1.clean_name, 30),
                    left(s23.clean_name, 30)
                ) AS edit_distance
            FROM s1
            JOIN s23
              ON s1.country = s23.country
             AND length(s1.clean_name) >= 5
             AND length(s23.clean_name) >= 5
             AND left(s1.clean_name, 5) = left(s23.clean_name, 5)
        ),

        ranked AS (
            SELECT
                source1_entity_id,
                candidate_entity_id,
                edit_distance,
                row_number() OVER (
                    PARTITION BY source1_entity_id
                    ORDER BY edit_distance
                ) AS rn
            FROM joined
        )

        SELECT
            source1_entity_id,
            candidate_entity_id
        FROM ranked
        WHERE rn <= 50

    ) TO '{output_file}'
    (FORMAT CSV, HEADER TRUE, DELIMITER '\\t');
    """

    start = time.time()

    try:
        con.execute(query_batch)

        elapsed = time.time() - start
        print(f"Batch {batch_no} DONE | Time: {elapsed/60:.1f} min")

    except Exception as e:
        print(f"Batch {batch_no} FAILED")
        print(str(e))
        print("Stopping here so we don't lose progress.")
        break

print("\nAUTOMATED BATCH PROCESS FINISHED/STOPPED")

In [ ]:
print("Checking DuckDB...")

print(
    con.execute("SELECT 1").fetchone()
)

print("DuckDB is working.")

In [ ]:
print("Creating S2 + S3 reusable index...")
print("One-time operation started...")

con.execute("DROP TABLE IF EXISTS s23_index")

con.execute(f"""
CREATE TABLE s23_index AS
SELECT
    entity_id AS candidate_entity_id,
    country,
    regexp_replace(
        lower(coalesce(business_name, '')),
        '[^a-zA-Z0-9]', '', 'g'
    ) AS clean_name
FROM read_csv_auto('{s2_path}', delim='\\t')

UNION ALL

SELECT
    entity_id AS candidate_entity_id,
    country,
    regexp_replace(
        lower(coalesce(business_name, '')),
        '[^a-zA-Z0-9]', '', 'g'
    ) AS clean_name
FROM read_csv_auto('{s3_path}', delim='\\t')
""")

count = con.execute("""
    SELECT COUNT(*) FROM s23_index
""").fetchone()[0]

print("S23 INDEX CREATED")
print("Total S2 + S3 records:", count)

In [ ]:
import os
import time

batch_no = 49
batch_size = 5000

offset = (batch_no - 1) * batch_size
output_file = f"/kaggle/working/candidates/name_candidates_batch_{batch_no:03d}.tsv"

print(f"Starting FAST Batch {batch_no}...")
print(f"Offset: {offset}")

start_time = time.time()

con.execute(f"""
COPY (
    WITH s1 AS (
        SELECT
            entity_id AS source1_entity_id,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s1_path}', delim='\\t')
        LIMIT {batch_size} OFFSET {offset}
    ),

    joined AS (
        SELECT
            s1.source1_entity_id,
            s23.candidate_entity_id,
            levenshtein(
                left(s1.clean_name, 30),
                left(s23.clean_name, 30)
            ) AS edit_distance
        FROM s1
        JOIN s23_index s23
          ON s1.country = s23.country
         AND length(s1.clean_name) >= 5
         AND length(s23.clean_name) >= 5
         AND left(s1.clean_name, 5) = left(s23.clean_name, 5)
    ),

    ranked AS (
        SELECT
            source1_entity_id,
            candidate_entity_id,
            edit_distance,
            row_number() OVER (
                PARTITION BY source1_entity_id
                ORDER BY edit_distance
            ) AS rn
        FROM joined
    )

    SELECT
        source1_entity_id,
        candidate_entity_id
    FROM ranked
    WHERE rn <= 50

) TO '{output_file}'
(FORMAT CSV, HEADER TRUE, DELIMITER '\\t');
""")

elapsed = time.time() - start_time

print("\nBATCH 49 COMPLETED")
print("Time:", round(elapsed, 2), "seconds")
print("File:", output_file)
print("File exists:", os.path.exists(output_file))

if os.path.exists(output_file):
    size_mb = os.path.getsize(output_file) / (1024 * 1024)
    print("File size:", round(size_mb, 2), "MB")

    check = con.execute(f"""
        SELECT
            COUNT(*) AS candidate_pairs,
            COUNT(DISTINCT source1_entity_id) AS source1_entities
        FROM read_csv_auto('{output_file}', delim='\\t')
    """).fetchone()

    print("Candidate pairs:", check[0])
    print("Source1 entities:", check[1])

In [ ]:
import os
import time
import glob

batch_size = 5000
start_batch = 50
end_batch = 347

total_start = time.time()

print(f"Starting FAST batches {start_batch} to {end_batch}...")
print(f"Total remaining batches: {end_batch - start_batch + 1}")
print("=" * 60)

for batch_no in range(start_batch, end_batch + 1):

    output_file = (
        f"/kaggle/working/candidates/"
        f"name_candidates_batch_{batch_no:03d}.tsv"
    )

    # Skip already completed batch
    if os.path.exists(output_file):
        print(f"Batch {batch_no} already exists - SKIPPING")
        continue

    offset = (batch_no - 1) * batch_size
    start_time = time.time()

    try:
        con.execute(f"""
        COPY (
            WITH s1 AS (
                SELECT
                    entity_id AS source1_entity_id,
                    country,
                    regexp_replace(
                        lower(coalesce(business_name, '')),
                        '[^a-zA-Z0-9]', '', 'g'
                    ) AS clean_name
                FROM read_csv_auto('{s1_path}', delim='\\t')
                LIMIT {batch_size} OFFSET {offset}
            ),

            joined AS (
                SELECT
                    s1.source1_entity_id,
                    s23.candidate_entity_id,
                    levenshtein(
                        left(s1.clean_name, 30),
                        left(s23.clean_name, 30)
                    ) AS edit_distance
                FROM s1
                JOIN s23_index s23
                  ON s1.country = s23.country
                 AND length(s1.clean_name) >= 5
                 AND length(s23.clean_name) >= 5
                 AND left(s1.clean_name, 5) =
                     left(s23.clean_name, 5)
            ),

            ranked AS (
                SELECT
                    source1_entity_id,
                    candidate_entity_id,
                    edit_distance,
                    row_number() OVER (
                        PARTITION BY source1_entity_id
                        ORDER BY edit_distance
                    ) AS rn
                FROM joined
            )

            SELECT
                source1_entity_id,
                candidate_entity_id
            FROM ranked
            WHERE rn <= 50

        ) TO '{output_file}'
        (FORMAT CSV, HEADER TRUE, DELIMITER '\\t');
        """)

        elapsed = time.time() - start_time

        print(
            f"Batch {batch_no} DONE | "
            f"{elapsed:.1f}s"
        )

    except KeyboardInterrupt:
        print(f"\nSTOPPED at Batch {batch_no}")
        print("Completed files are safe.")
        break

    except Exception as e:
        print(f"\nBatch {batch_no} FAILED")
        print(type(e).__name__, ":", e)
        print("Continuing to next batch...")
        continue

total_time = time.time() - total_start

print("\n" + "=" * 60)
print("BATCH PROCESS FINISHED")
print("Total time:", round(total_time / 60, 2), "minutes")

files = glob.glob(
    "/kaggle/working/candidates/name_candidates_batch_*.tsv"
)

print("Total batch files currently saved:", len(files))

In [ ]:
import glob
import os

files = sorted(
    glob.glob("/kaggle/working/candidates/name_candidates_batch_*.tsv")
)

print("Total batch files:", len(files))

total_size = sum(os.path.getsize(f) for f in files)

print("Total size:",
      round(total_size / (1024**3), 2),
      "GB")

print("First:", os.path.basename(files[0]))
print("Last :", os.path.basename(files[-1]))

In [ ]:
import os
import glob

candidate_dir = "/kaggle/working/candidates"

files = sorted(glob.glob(candidate_dir + "/name_candidates_batch_*.tsv"))

print("Total batch files:", len(files))

total_size_gb = sum(os.path.getsize(f) for f in files) / (1024**3)
print(f"Total size: {total_size_gb:.2f} GB")

print("\nFirst file:", os.path.basename(files[0]) if files else "NONE")
print("Last file :", os.path.basename(files[-1]) if files else "NONE")

print("\nSample files:")
for f in files[:5]:
    print(os.path.basename(f))

In [ ]:
import glob
import pandas as pd

files = sorted(glob.glob("/kaggle/working/candidates/name_candidates_batch_*.tsv"))

total_pairs = 0

for i, f in enumerate(files, 1):
    df = pd.read_csv(f, sep="\t")
    total_pairs += len(df)

    if i % 50 == 0 or i == len(files):
        print(f"Checked {i}/{len(files)} files | Pairs so far: {total_pairs:,}")

print("\n==============================")
print("TOTAL CANDIDATE PAIRS:", f"{total_pairs:,}")
print("==============================")

In [ ]:
import os
import joblib

model_path = "/kaggle/working/student_matching_model_package.pkl"

model_package = {
    "model": final_model,
    "features": features
}

joblib.dump(model_package, model_path)

print("Model saved successfully!")
print("Path:", model_path)
print("Size:", round(os.path.getsize(model_path) / (1024 * 1024), 2), "MB")

In [ ]:
print("Checking available model variables...\n")

for name in ["model", "final_model", "rf_model", "classifier"]:
    if name in globals():
        print("FOUND:", name, "->", type(globals()[name]))

print("\nFeatures variable:")
if "features" in globals():
    print("FOUND ->", features)
else:
    print("NOT FOUND")

In [ ]:
import os
import glob

print("Checking saved model files in /kaggle/working...\n")

patterns = [
    "/kaggle/working/*.pkl",
    "/kaggle/working/**/*.pkl"
]

model_files = []

for pattern in patterns:
    model_files.extend(glob.glob(pattern, recursive=True))

model_files = sorted(set(model_files))

if model_files:
    for f in model_files:
        size_mb = os.path.getsize(f) / (1024 * 1024)
        print("FOUND:", f)
        print("SIZE :", round(size_mb, 2), "MB")
else:
    print("NO .pkl MODEL FILE FOUND")

In [ ]:
# Search notebook variables for important training objects

names_to_check = [
    "RandomForestClassifier",
    "X_train",
    "X_test",
    "y_train",
    "y_test",
    "train_df",
    "balanced_df",
    "positive_pairs",
    "negative_pairs"
]

for name in names_to_check:
    print(name, "->", "FOUND" if name in globals() else "NOT FOUND")

In [ ]:
import os
import glob

print("Checking training files...\n")

train_files = glob.glob(
    "/kaggle/input/**/*.tsv",
    recursive=True
)

for f in train_files:
    if "/train/" in f:
        print(f)

In [ ]:
import pandas as pd

base = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train"

train_s1 = pd.read_csv(base + "/train_source1.tsv", sep="\t")
train_s2 = pd.read_csv(base + "/train_source2.tsv", sep="\t")
train_s3 = pd.read_csv(base + "/train_source3.tsv", sep="\t")
ground_truth = pd.read_csv(base + "/train_ground_truth.tsv", sep="\t")

print("Source 1:", train_s1.shape)
print("Source 2:", train_s2.shape)
print("Source 3:", train_s3.shape)
print("Ground Truth:", ground_truth.shape)

print("\nGround Truth columns:")
print(ground_truth.columns.tolist())

In [ ]:
import pandas as pd

# Ground truth ko existing variable se use kar rahe hain
gt = ground_truth.copy()

# Empty / NaN matches hatao
gt_nonempty = gt[
    gt["matched_entity_ids"].notna() &
    (gt["matched_entity_ids"].astype(str).str.strip() != "")
].copy()

print("Total Source1 records:", len(gt))
print("Source1 records having matches:", len(gt_nonempty))

# Multiple matched IDs ko alag-alag pairs mein convert karo
positive_pairs = []

for _, row in gt_nonempty.iterrows():
    source1_id = row["source1_entity_id"]
    matched_ids = str(row["matched_entity_ids"]).split(",")

    for candidate_id in matched_ids:
        candidate_id = candidate_id.strip()
        if candidate_id:
            positive_pairs.append((source1_id, candidate_id))

positive_pairs = pd.DataFrame(
    positive_pairs,
    columns=["source1_entity_id", "candidate_entity_id"]
)

print("Total positive matching pairs:", len(positive_pairs))
print("\nSample:")
print(positive_pairs.head())

In [ ]:
import pandas as pd
import numpy as np

# Reproducible sampling
np.random.seed(42)

# 5,000 positive pairs
positive_sample = positive_pairs.sample(
    n=5000,
    random_state=42
).copy()

# Source1 IDs
source1_ids = train_s1["entity_id"].astype(str).tolist()

# All S2 + S3 candidate IDs
candidate_ids = pd.concat([
    train_s2["entity_id"].astype(str),
    train_s3["entity_id"].astype(str)
], ignore_index=True)

# Create negative pairs
positive_set = set(
    zip(
        positive_pairs["source1_entity_id"].astype(str),
        positive_pairs["candidate_entity_id"].astype(str)
    )
)

negative_pairs = []

while len(negative_pairs) < 5000:
    s1_id = np.random.choice(source1_ids)
    candidate_id = np.random.choice(candidate_ids)

    if (s1_id, candidate_id) not in positive_set:
        negative_pairs.append((s1_id, candidate_id))

negative_sample = pd.DataFrame(
    negative_pairs,
    columns=["source1_entity_id", "candidate_entity_id"]
)

# Add labels
positive_sample["label"] = 1
negative_sample["label"] = 0

training_pairs = pd.concat(
    [positive_sample, negative_sample],
    ignore_index=True
).sample(frac=1, random_state=42).reset_index(drop=True)

print("Positive samples:", len(positive_sample))
print("Negative samples:", len(negative_sample))
print("Total training pairs:", len(training_pairs))

print("\nLabel distribution:")
print(training_pairs["label"].value_counts())

print("\nSample:")
print(training_pairs.head())

In [ ]:
import pandas as pd
import numpy as np
import gc

np.random.seed(42)

# 1. Positive sample
positive_sample = positive_pairs.sample(
    n=5000,
    random_state=42
).copy()

positive_sample["label"] = 1

# 2. IDs
s1_ids = train_s1["entity_id"].astype(str).to_numpy()

candidate_ids = pd.concat([
    train_s2["entity_id"].astype(str),
    train_s3["entity_id"].astype(str)
], ignore_index=True).to_numpy()

# 3. Generate 5000 negative pairs directly
negative_sample = pd.DataFrame({
    "source1_entity_id": np.random.choice(s1_ids, 5000),
    "candidate_entity_id": np.random.choice(candidate_ids, 5000),
    "label": 0
})

# 4. Remove accidental duplicate pairs
negative_sample = negative_sample.drop_duplicates(
    subset=["source1_entity_id", "candidate_entity_id"]
)

# 5. Combine
training_pairs = pd.concat(
    [positive_sample, negative_sample],
    ignore_index=True
).sample(frac=1, random_state=42).reset_index(drop=True)

print("Positive samples:", len(positive_sample))
print("Negative samples:", len(negative_sample))
print("Total training pairs:", len(training_pairs))

print("\nLabel distribution:")
print(training_pairs["label"].value_counts())

print("\nSample:")
print(training_pairs.head())

gc.collect()

In [ ]:
import os
import psutil

ram = psutil.virtual_memory()

print("RAM Total    :", round(ram.total / (1024**3), 2), "GB")
print("RAM Used     :", round(ram.used / (1024**3), 2), "GB")
print("RAM Available:", round(ram.available / (1024**3), 2), "GB")
print("RAM Usage    :", ram.percent, "%")

In [ ]:
# Required columns only
s1_lookup = train_s1[
    ["entity_id", "business_name", "business_address", "country"]
].copy()

s2_lookup = train_s2[
    ["entity_id", "business_name", "business_address", "country"]
].copy()

s3_lookup = train_s3[
    ["entity_id", "business_name", "business_address", "country"]
].copy()

# S2 + S3 candidate lookup
s23_lookup = pd.concat(
    [s2_lookup, s3_lookup],
    ignore_index=True
)

print("S1 lookup:", s1_lookup.shape)
print("S2 lookup:", s2_lookup.shape)
print("S3 lookup:", s3_lookup.shape)
print("S2+S3 lookup:", s23_lookup.shape)

print("\nRAM after lookup creation:")
ram = psutil.virtual_memory()
print("Used     :", round(ram.used / (1024**3), 2), "GB")
print("Available:", round(ram.available / (1024**3), 2), "GB")
print("Usage    :", ram.percent, "%")

In [ ]:
import gc
import psutil

# Sirf training pairs mein required IDs
needed_s1_ids = training_pairs["source1_entity_id"].astype(str).unique()
needed_candidate_ids = training_pairs["candidate_entity_id"].astype(str).unique()

# Sirf required S1 records
s1_small = (
    train_s1[
        train_s1["entity_id"].astype(str).isin(needed_s1_ids)
    ][["entity_id", "business_name", "business_address", "country"]]
    .copy()
)

# Sirf required S2/S3 records
s23_small = (
    s23_lookup[
        s23_lookup["entity_id"].astype(str).isin(needed_candidate_ids)
    ][["entity_id", "business_name", "business_address", "country"]]
    .copy()
)

print("Required S1 records:", len(s1_small))
print("Required S2/S3 records:", len(s23_small))

# Bade lookup tables delete
del s1_lookup
del s2_lookup
del s3_lookup
del s23_lookup

gc.collect()

ram = psutil.virtual_memory()

print("\nRAM after cleanup:")
print("Used     :", round(ram.used / (1024**3), 2), "GB")
print("Available:", round(ram.available / (1024**3), 2), "GB")
print("Usage    :", ram.percent, "%")

In [ ]:
from difflib import SequenceMatcher
import re
import pandas as pd
import numpy as np

def normalize_text(text):
    if pd.isna(text):
        return ""
    return re.sub(r"\s+", " ", str(text).lower()).strip()

def token_similarity(a, b):
    a_tokens = set(normalize_text(a).split())
    b_tokens = set(normalize_text(b).split())

    if not a_tokens or not b_tokens:
        return 0.0

    return len(a_tokens & b_tokens) / len(a_tokens | b_tokens)

def number_overlap(a, b):
    nums_a = set(re.findall(r"\d+", str(a)))
    nums_b = set(re.findall(r"\d+", str(b)))

    if not nums_a or not nums_b:
        return 0.0

    return len(nums_a & nums_b) / len(nums_a | nums_b)

# Fast dictionaries
s1_dict = s1_small.set_index("entity_id").to_dict("index")
s23_dict = s23_small.set_index("entity_id").to_dict("index")

features_list = []

for _, row in training_pairs.iterrows():

    s1 = s1_dict[str(row["source1_entity_id"])]
    s23 = s23_dict[str(row["candidate_entity_id"])]

    name1 = normalize_text(s1["business_name"])
    name2 = normalize_text(s23["business_name"])

    addr1 = normalize_text(s1["business_address"])
    addr2 = normalize_text(s23["business_address"])

    features_list.append({
        "name_similarity": SequenceMatcher(None, name1, name2).ratio(),

        "address_similarity": SequenceMatcher(
            None, addr1, addr2
        ).ratio(),

        "name_token_similarity": token_similarity(
            name1, name2
        ),

        "address_token_similarity": token_similarity(
            addr1, addr2
        ),

        "number_overlap": number_overlap(
            addr1, addr2
        ),

        "country_match": int(
            str(s1["country"]).lower().strip()
            == str(s23["country"]).lower().strip()
        ),

        "source1_address_missing": int(addr1 == ""),

        "candidate_address_missing": int(addr2 == ""),

        "label": row["label"]
    })

training_features = pd.DataFrame(features_list)

print("Feature dataset shape:", training_features.shape)

print("\nColumns:")
print(training_features.columns.tolist())

print("\nFirst 5 rows:")
print(training_features.head())

print("\nRAM:")
ram = psutil.virtual_memory()
print("Used     :", round(ram.used / (1024**3), 2), "GB")
print("Available:", round(ram.available / (1024**3), 2), "GB")
print("Usage    :", ram.percent, "%")

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 8 features
feature_columns = [
    "name_similarity",
    "address_similarity",
    "name_token_similarity",
    "address_token_similarity",
    "number_overlap",
    "country_match",
    "source1_address_missing",
    "candidate_address_missing"
]

X = training_features[feature_columns]
y = training_features["label"]

# Train / validation split
X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training rows:", len(X_train))
print("Validation rows:", len(X_val))

# Random Forest
final_model = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

final_model.fit(X_train, y_train)

# Validation
y_pred = final_model.predict(X_val)

print("\nAccuracy:", round(accuracy_score(y_val, y_pred), 4))

print("\nConfusion Matrix:")
print(confusion_matrix(y_val, y_pred))

print("\nClassification Report:")
print(classification_report(y_val, y_pred))

In [ ]:
import joblib
import os
import psutil

model_package = {
    "model": final_model,
    "features": feature_columns
}

model_path = "/kaggle/working/student_matching_model_package.pkl"

joblib.dump(model_package, model_path)

size_mb = os.path.getsize(model_path) / (1024 * 1024)

print("MODEL SAVED SUCCESSFULLY")
print("Path:", model_path)
print("Size:", round(size_mb, 2), "MB")

ram = psutil.virtual_memory()
print("\nRAM:")
print("Used     :", round(ram.used / (1024**3), 2), "GB")
print("Available:", round(ram.available / (1024**3), 2), "GB")
print("Usage    :", ram.percent, "%")

In [ ]:
import pandas as pd
import numpy as np
import joblib
import time
import psutil

# Load saved model
model_package = joblib.load(
    "/kaggle/working/student_matching_model_package.pkl"
)

final_model = model_package["model"]
feature_columns = model_package["features"]

# First candidate file
test_candidate_file = (
    "/kaggle/working/candidates/name_candidates_batch_001.tsv"
)

sample_candidates = pd.read_csv(
    test_candidate_file,
    sep="\t",
    nrows=5000
)

print("Candidate rows loaded:", len(sample_candidates))

ram = psutil.virtual_memory()
print("RAM before scoring:", ram.percent, "%")

print("\nColumns:")
print(sample_candidates.columns.tolist())

print("\nSample:")
print(sample_candidates.head())

In [ ]:
import time
import re
from difflib import SequenceMatcher
import pandas as pd
import numpy as np
import psutil

start = time.time()

def normalize_text(text):
    if pd.isna(text):
        return ""
    return re.sub(r"\s+", " ", str(text).lower()).strip()

def token_similarity(a, b):
    a_tokens = set(a.split())
    b_tokens = set(b.split())

    if not a_tokens or not b_tokens:
        return 0.0

    return len(a_tokens & b_tokens) / len(a_tokens | b_tokens)

def number_overlap(a, b):
    nums_a = set(re.findall(r"\d+", a))
    nums_b = set(re.findall(r"\d+", b))

    if not nums_a or not nums_b:
        return 0.0

    return len(nums_a & nums_b) / len(nums_a | nums_b)

# Dictionaries already created from Cell 11
feature_rows = []

for _, row in sample_candidates.iterrows():

    s1 = s1_dict.get(str(row["source1_entity_id"]))
    s23 = s23_dict.get(str(row["candidate_entity_id"]))

    if s1 is None or s23 is None:
        continue

    name1 = normalize_text(s1["business_name"])
    name2 = normalize_text(s23["business_name"])

    addr1 = normalize_text(s1["business_address"])
    addr2 = normalize_text(s23["business_address"])

    feature_rows.append([
        SequenceMatcher(None, name1, name2).ratio(),
        SequenceMatcher(None, addr1, addr2).ratio(),
        token_similarity(name1, name2),
        token_similarity(addr1, addr2),
        number_overlap(addr1, addr2),
        int(
            str(s1["country"]).lower().strip()
            == str(s23["country"]).lower().strip()
        ),
        int(addr1 == ""),
        int(addr2 == "")
    ])

benchmark_X = pd.DataFrame(
    feature_rows,
    columns=feature_columns
)

# Prediction
probabilities = final_model.predict_proba(benchmark_X)[:, 1]

elapsed = time.time() - start

print("Rows scored:", len(benchmark_X))
print("Time:", round(elapsed, 2), "seconds")
print("Speed:", round(len(benchmark_X) / elapsed, 2), "rows/sec")

print("\nProbability range:")
print("Min:", round(probabilities.min(), 4))
print("Max:", round(probabilities.max(), 4))

ram = psutil.virtual_memory()
print("\nRAM:")
print("Used     :", round(ram.used / (1024**3), 2), "GB")
print("Available:", round(ram.available / (1024**3), 2), "GB")
print("Usage    :", ram.percent, "%")

In [ ]:
import time
import re
from difflib import SequenceMatcher
import pandas as pd
import numpy as np
import psutil

start = time.time()

# FIX: force all dictionary keys to string
s1_dict = {
    str(k): v
    for k, v in s1_small.set_index("entity_id").to_dict("index").items()
}

s23_dict = {
    str(k): v
    for k, v in s23_small.set_index("entity_id").to_dict("index").items()
}

print("S1 dictionary:", len(s1_dict))
print("S2/S3 dictionary:", len(s23_dict))

# Check first candidate
first_s1 = str(sample_candidates.iloc[0]["source1_entity_id"])
first_cand = str(sample_candidates.iloc[0]["candidate_entity_id"])

print("\nFirst candidate lookup:")
print("S1 found :", first_s1 in s1_dict)
print("Candidate found:", first_cand in s23_dict)

def normalize_text(text):
    if pd.isna(text):
        return ""
    return re.sub(r"\s+", " ", str(text).lower()).strip()

def token_similarity(a, b):
    a_tokens = set(a.split())
    b_tokens = set(b.split())

    if not a_tokens or not b_tokens:
        return 0.0

    return len(a_tokens & b_tokens) / len(a_tokens | b_tokens)

def number_overlap(a, b):
    nums_a = set(re.findall(r"\d+", a))
    nums_b = set(re.findall(r"\d+", b))

    if not nums_a or not nums_b:
        return 0.0

    return len(nums_a & nums_b) / len(nums_a | nums_b)

feature_rows = []

for _, row in sample_candidates.iterrows():

    s1 = s1_dict.get(str(row["source1_entity_id"]))
    s23 = s23_dict.get(str(row["candidate_entity_id"]))

    if s1 is None or s23 is None:
        continue

    name1 = normalize_text(s1["business_name"])
    name2 = normalize_text(s23["business_name"])

    addr1 = normalize_text(s1["business_address"])
    addr2 = normalize_text(s23["business_address"])

    feature_rows.append([
        SequenceMatcher(None, name1, name2).ratio(),
        SequenceMatcher(None, addr1, addr2).ratio(),
        token_similarity(name1, name2),
        token_similarity(addr1, addr2),
        number_overlap(addr1, addr2),
        int(
            str(s1["country"]).lower().strip()
            == str(s23["country"]).lower().strip()
        ),
        int(addr1 == ""),
        int(addr2 == "")
    ])

benchmark_X = pd.DataFrame(
    feature_rows,
    columns=feature_columns
)

print("\nFeature rows created:", len(benchmark_X))

if len(benchmark_X) > 0:

    probabilities = final_model.predict_proba(benchmark_X)[:, 1]

    elapsed = time.time() - start

    print("Rows scored:", len(benchmark_X))
    print("Time:", round(elapsed, 2), "seconds")
    print("Speed:", round(len(benchmark_X) / elapsed, 2), "rows/sec")

    print("\nProbability range:")
    print("Min:", round(probabilities.min(), 4))
    print("Max:", round(probabilities.max(), 4))

else:
    print("ERROR: No matching records found.")

ram = psutil.virtual_memory()

print("\nRAM:")
print("Used     :", round(ram.used / (1024**3), 2), "GB")
print("Available:", round(ram.available / (1024**3), 2), "GB")
print("Usage    :", ram.percent, "%")

In [ ]:
import pandas as pd
import psutil

test_base = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test"

test_s1_path = test_base + "/test_source1.tsv"
test_s2_path = test_base + "/test_source2.tsv"
test_s3_path = test_base + "/test_source3.tsv"

# Candidate IDs from our 5,000-row benchmark
needed_s1_ids = set(
    sample_candidates["source1_entity_id"].astype(str)
)

needed_candidate_ids = set(
    sample_candidates["candidate_entity_id"].astype(str)
)

print("Required S1 IDs:", len(needed_s1_ids))
print("Required candidate IDs:", len(needed_candidate_ids))

# Load only TEST Source 1
test_s1_small = pd.read_csv(
    test_s1_path,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    dtype={"entity_id": str}
)

test_s1_small = test_s1_small[
    test_s1_small["entity_id"].isin(needed_s1_ids)
].copy()

print("\nTest S1 records found:", len(test_s1_small))

# Load TEST Source 2
test_s2_small = pd.read_csv(
    test_s2_path,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    dtype={"entity_id": str}
)

test_s2_small = test_s2_small[
    test_s2_small["entity_id"].isin(needed_candidate_ids)
].copy()

# Load TEST Source 3
test_s3_small = pd.read_csv(
    test_s3_path,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    dtype={"entity_id": str}
)

test_s3_small = test_s3_small[
    test_s3_small["entity_id"].isin(needed_candidate_ids)
].copy()

test_s23_small = pd.concat(
    [test_s2_small, test_s3_small],
    ignore_index=True
)

print("Test S2 records found:", len(test_s2_small))
print("Test S3 records found:", len(test_s3_small))
print("Test S2+S3 records:", len(test_s23_small))

# RAM
ram = psutil.virtual_memory()
print("\nRAM:")
print("Used     :", round(ram.used / (1024**3), 2), "GB")
print("Available:", round(ram.available / (1024**3), 2), "GB")
print("Usage    :", ram.percent, "%")

In [ ]:
# ============================================
# CELL 18: Create TEST lookup dictionaries
# ============================================

import numpy as np
import pandas as pd
import re
import psutil
from difflib import SequenceMatcher

# Convert test data into dictionaries
s1_dict = test_s1_small.set_index("entity_id").to_dict("index")
s23_dict = test_s23_small.set_index("entity_id").to_dict("index")

print("S1 dictionary:", len(s1_dict))
print("S2/S3 dictionary:", len(s23_dict))


# ---------- Helper functions ----------

def normalize_text(text):
    if pd.isna(text):
        return ""
    return re.sub(r"\s+", " ", str(text).lower()).strip()


def text_similarity(a, b):
    a = normalize_text(a)
    b = normalize_text(b)

    if not a or not b:
        return 0.0

    return SequenceMatcher(None, a, b).ratio()


def token_similarity(a, b):
    a = normalize_text(a)
    b = normalize_text(b)

    if not a or not b:
        return 0.0

    set_a = set(a.split())
    set_b = set(b.split())

    if not set_a or not set_b:
        return 0.0

    return len(set_a & set_b) / len(set_a | set_b)


def number_overlap(a, b):
    nums_a = set(re.findall(r"\d+", normalize_text(a)))
    nums_b = set(re.findall(r"\d+", normalize_text(b)))

    if not nums_a or not nums_b:
        return 0.0

    return len(nums_a & nums_b) / len(nums_a | nums_b)


# ---------- Create features ----------

feature_rows = []

for _, row in sample_candidates.iterrows():

    s1_id = str(row["source1_entity_id"])
    candidate_id = str(row["candidate_entity_id"])

    s1 = s1_dict.get(s1_id)
    candidate = s23_dict.get(candidate_id)

    if s1 is None or candidate is None:
        continue

    s1_name = s1["business_name"]
    s1_address = s1["business_address"]

    c_name = candidate["business_name"]
    c_address = candidate["business_address"]

    feature_rows.append([
        text_similarity(s1_name, c_name),
        text_similarity(s1_address, c_address),
        token_similarity(s1_name, c_name),
        token_similarity(s1_address, c_address),
        number_overlap(s1_address, c_address),
        int(
            normalize_text(s1["country"])
            == normalize_text(candidate["country"])
        ),
        int(pd.isna(s1_address) or normalize_text(s1_address) == ""),
        int(pd.isna(c_address) or normalize_text(c_address) == "")
    ])


features_test = pd.DataFrame(
    feature_rows,
    columns=[
        "name_similarity",
        "address_similarity",
        "name_token_similarity",
        "address_token_similarity",
        "number_overlap",
        "country_match",
        "source1_address_missing",
        "candidate_address_missing"
    ]
)

print("\nFeature rows created:", len(features_test))
print("Feature shape:", features_test.shape)

print("\nFirst 5 rows:")
display(features_test.head())

ram = psutil.virtual_memory()
print("\nRAM:")
print("Used     :", round(ram.used / (1024**3), 2), "GB")
print("Available:", round(ram.available / (1024**3), 2), "GB")
print("Usage    :", ram.percent, "%")

In [ ]:
# ============================================
# CELL 19: Predict match probability
# ============================================

import joblib
import numpy as np
import pandas as pd
import psutil

# Load trained model
model_package = joblib.load(
    "/kaggle/working/student_matching_model_package.pkl"
)

final_model = model_package["model"]
model_features = model_package["features"]

print("Model loaded successfully")
print("Model features:", model_features)

# Make sure feature order is exactly same as training
X_test = features_test[model_features]

# Predict probability
match_probability = final_model.predict_proba(X_test)[:, 1]

# Copy candidate pairs
benchmark_results = sample_candidates.copy()

# Add probability
benchmark_results["match_probability"] = match_probability

print("\nPrediction completed")
print("Total predictions:", len(benchmark_results))

print("\nProbability summary:")
print(benchmark_results["match_probability"].describe())

print("\nTop 10 predictions:")
display(
    benchmark_results
    .sort_values("match_probability", ascending=False)
    .head(10)
)

# RAM check
ram = psutil.virtual_memory()
print("\nRAM:")
print("Used     :", round(ram.used / (1024**3), 2), "GB")
print("Available:", round(ram.available / (1024**3), 2), "GB")
print("Usage    :", ram.percent, "%")

In [ ]:
# ============================================
# CELL 20: Top candidate for each Source1
# ============================================

top_candidates = (
    benchmark_results
    .sort_values(
        ["source1_entity_id", "match_probability"],
        ascending=[True, False]
    )
    .groupby("source1_entity_id", as_index=False)
    .first()
)

print("Total Source1 entities:", len(top_candidates))

print("\nTop candidate per Source1:")
display(top_candidates.head(20))

print("\nProbability summary of top candidates:")
print(top_candidates["match_probability"].describe())

# RAM check
ram = psutil.virtual_memory()
print("\nRAM:")
print("Used     :", round(ram.used / (1024**3), 2), "GB")
print("Available:", round(ram.available / (1024**3), 2), "GB")
print("Usage    :", ram.percent, "%")

In [ ]:
# ============================================
# CELL 21: Check top probability distribution
# ============================================

bins = [0, 0.50, 0.70, 0.80, 0.90, 0.95, 0.99, 1.01]
labels = [
    "0.00 - 0.49",
    "0.50 - 0.69",
    "0.70 - 0.79",
    "0.80 - 0.89",
    "0.90 - 0.94",
    "0.95 - 0.98",
    "0.99 - 1.00"
]

top_candidates["probability_range"] = pd.cut(
    top_candidates["match_probability"],
    bins=bins,
    labels=labels,
    right=False
)

distribution = (
    top_candidates["probability_range"]
    .value_counts()
    .sort_index()
)

print("Top candidate probability distribution:")
print(distribution)

print("\nTotal Source1:", len(top_candidates))
print("Top probability >= 0.99:",
      (top_candidates["match_probability"] >= 0.99).sum())
print("Top probability >= 0.95:",
      (top_candidates["match_probability"] >= 0.95).sum())
print("Top probability >= 0.90:",
      (top_candidates["match_probability"] >= 0.90).sum())

# RAM
ram = psutil.virtual_memory()
print("\nRAM:")
print("Used     :", round(ram.used / (1024**3), 2), "GB")
print("Available:", round(ram.available / (1024**3), 2), "GB")
print("Usage    :", ram.percent, "%")

## Model Prediction Analysis

The trained Random Forest model was tested on a sample of 5,000 candidate pairs generated from the test dataset.

For each Source1 entity, the candidate with the highest predicted match probability was selected for analysis.

### Results

- Total Source1 entities analyzed: **124**
- Top candidates with probability >= 0.99: **118**
- Top candidates with probability >= 0.95: **121**
- Top candidates with probability >= 0.90: **124**
- Average top-candidate probability: **0.9977**
- Minimum top-candidate probability: **0.9233**

### Observation

The model assigns high match probabilities to the top candidate for most Source1 entities. However, the probability score alone does not guarantee that the candidate is a true entity match. Therefore, the final matching stage will apply the trained model to the complete candidate set and generate the required submission files.

**Note:** These results are based on a 5,000-candidate benchmark sample and are not the final evaluation results.

In [ ]:
# ============================================
# CELL 22: Prepare scoring folders
# ============================================

import os
import gc
import psutil

# Folder for scored candidate batches
scored_dir = "/kaggle/working/scored_candidates"
os.makedirs(scored_dir, exist_ok=True)

# Check candidate files
candidate_files = sorted([
    os.path.join("/kaggle/working/candidates", f)
    for f in os.listdir("/kaggle/working/candidates")
    if f.endswith(".tsv")
])

print("Candidate files found:", len(candidate_files))

# Check scored files already completed
scored_files = sorted([
    os.path.join(scored_dir, f)
    for f in os.listdir(scored_dir)
    if f.endswith(".tsv")
])

print("Already scored files:", len(scored_files))

print("\nFirst candidate file:")
print(candidate_files[0])

# RAM
ram = psutil.virtual_memory()
print("\nRAM:")
print("Used     :", round(ram.used / (1024**3), 2), "GB")
print("Available:", round(ram.available / (1024**3), 2), "GB")
print("Usage    :", ram.percent, "%")

In [ ]:
# ============================================
# CELL 23: Benchmark scoring speed
# ============================================

import time
import gc
import psutil
import pandas as pd

# Benchmark candidate file
benchmark_file = "/kaggle/working/candidates/name_candidates_test_5000.tsv"

print("Loading benchmark candidates...")

benchmark_candidates = pd.read_csv(
    benchmark_file,
    sep="\t",
    dtype=str
)

print("Benchmark candidates:", len(benchmark_candidates))

# Start timer
start_time = time.time()

# Create feature rows
benchmark_feature_rows = []

for _, row in benchmark_candidates.iterrows():

    s1_id = str(row["source1_entity_id"])
    candidate_id = str(row["candidate_entity_id"])

    s1 = s1_dict.get(s1_id)
    candidate = s23_dict.get(candidate_id)

    if s1 is None or candidate is None:
        continue

    s1_name = s1["business_name"]
    s1_address = s1["business_address"]

    c_name = candidate["business_name"]
    c_address = candidate["business_address"]

    benchmark_feature_rows.append([
        text_similarity(s1_name, c_name),
        text_similarity(s1_address, c_address),
        token_similarity(s1_name, c_name),
        token_similarity(s1_address, c_address),
        number_overlap(s1_address, c_address),
        int(
            normalize_text(s1["country"])
            == normalize_text(candidate["country"])
        ),
        int(pd.isna(s1_address) or normalize_text(s1_address) == ""),
        int(pd.isna(c_address) or normalize_text(c_address) == "")
    ])

benchmark_features = pd.DataFrame(
    benchmark_feature_rows,
    columns=model_features
)

# Predict
benchmark_candidates["match_probability"] = (
    final_model.predict_proba(
        benchmark_features[model_features]
    )[:, 1]
)

elapsed = time.time() - start_time

print("\n================================")
print("BENCHMARK COMPLETE")
print("================================")

print("Rows scored:", len(benchmark_candidates))
print("Time:", round(elapsed, 2), "seconds")
print("Speed:", round(len(benchmark_candidates) / elapsed, 2), "rows/sec")

print("\nTop 5:")
display(
    benchmark_candidates
    .sort_values("match_probability", ascending=False)
    .head()
)

# RAM
ram = psutil.virtual_memory()

print("\nRAM:")
print("Used     :", round(ram.used / (1024**3), 2), "GB")
print("Available:", round(ram.available / (1024**3), 2), "GB")
print("Usage    :", ram.percent, "%")

# Cleanup
del benchmark_features
del benchmark_candidates
gc.collect()

In [ ]:
# ============================================
# CELL 23 FIX: Check benchmark file
# ============================================

import pandas as pd
import psutil

benchmark_file = "/kaggle/working/candidates/name_candidates_test_5000.tsv"

benchmark_candidates = pd.read_csv(
    benchmark_file,
    sep="\t",
    dtype=str
)

print("Benchmark file rows:", len(benchmark_candidates))
print("Benchmark columns:", list(benchmark_candidates.columns))

print("\nUnique Source1 IDs:",
      benchmark_candidates["source1_entity_id"].nunique())

print("Unique candidate IDs:",
      benchmark_candidates["candidate_entity_id"].nunique())

# Check how many IDs exist in our dictionaries
s1_found = benchmark_candidates["source1_entity_id"].isin(s1_dict).sum()
candidate_found = benchmark_candidates["candidate_entity_id"].isin(s23_dict).sum()

print("\nRows with S1 found:", s1_found)
print("Rows with candidate found:", candidate_found)

# Keep ONLY rows for which both records exist
valid_benchmark = benchmark_candidates[
    benchmark_candidates["source1_entity_id"].isin(s1_dict)
    &
    benchmark_candidates["candidate_entity_id"].isin(s23_dict)
].copy()

print("\nValid benchmark rows:", len(valid_benchmark))

ram = psutil.virtual_memory()
print("\nRAM:")
print("Used     :", round(ram.used / (1024**3), 2), "GB")
print("Available:", round(ram.available / (1024**3), 2), "GB")
print("Usage    :", ram.percent, "%")

In [ ]:
# ============================================
# CELL 24: FULL BATCH SCORING - RESUMABLE
# ============================================

import os
import gc
import time
import re
import pandas as pd
import numpy as np
import psutil

CAND_DIR = "/kaggle/working/candidates"
SCORED_DIR = "/kaggle/working/scored_candidates"

os.makedirs(SCORED_DIR, exist_ok=True)

# ONLY the real 347 candidate batches
candidate_files = sorted([
    os.path.join(CAND_DIR, f)
    for f in os.listdir(CAND_DIR)
    if f.startswith("name_candidates_batch_")
    and f.endswith(".tsv")
])

print("Candidate batches:", len(candidate_files))

# --------------------------------------------
# Process batches
# --------------------------------------------

for batch_no, candidate_file in enumerate(candidate_files, start=1):

    filename = os.path.basename(candidate_file)
    output_file = os.path.join(
        SCORED_DIR,
        filename.replace(
            "name_candidates_batch_",
            "scored_candidates_batch_"
        )
    )

    # Skip already completed batches
    if os.path.exists(output_file):
        print(
            f"[{batch_no}/{len(candidate_files)}] "
            f"SKIP - already done"
        )
        continue

    batch_start = time.time()

    print("\n" + "=" * 60)
    print(
        f"[{batch_no}/{len(candidate_files)}] "
        f"Processing {filename}"
    )
    print("=" * 60)

    # Load candidate pairs
    candidates = pd.read_csv(
        candidate_file,
        sep="\t",
        dtype=str
    )

    # Required IDs for THIS batch only
    s1_ids = set(candidates["source1_entity_id"])
    candidate_ids = set(candidates["candidate_entity_id"])

    print("Candidate pairs:", len(candidates))
    print("S1 IDs:", len(s1_ids))
    print("Candidate IDs:", len(candidate_ids))

    # ----------------------------------------
    # Read TEST files
    # ----------------------------------------

    s1_batch = pd.read_csv(
        test_s1_path,
        sep="\t",
        dtype=str,
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ]
    )

    s1_batch = s1_batch[
        s1_batch["entity_id"].isin(s1_ids)
    ].copy()

    del_candidates = None

    s2_batch = pd.read_csv(
        test_s2_path,
        sep="\t",
        dtype=str,
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ]
    )

    s2_batch = s2_batch[
        s2_batch["entity_id"].isin(candidate_ids)
    ].copy()

    s3_batch = pd.read_csv(
        test_s3_path,
        sep="\t",
        dtype=str,
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ]
    )

    s3_batch = s3_batch[
        s3_batch["entity_id"].isin(candidate_ids)
    ].copy()

    s23_batch = pd.concat(
        [s2_batch, s3_batch],
        ignore_index=True
    )

    # Dictionaries
    s1_lookup = s1_batch.set_index(
        "entity_id"
    ).to_dict("index")

    s23_lookup = s23_batch.set_index(
        "entity_id"
    ).to_dict("index")

    # ----------------------------------------
    # Feature calculation
    # ----------------------------------------

    feature_rows = []
    valid_rows = []

    for idx, row in candidates.iterrows():

        s1 = s1_lookup.get(
            str(row["source1_entity_id"])
        )

        candidate = s23_lookup.get(
            str(row["candidate_entity_id"])
        )

        if s1 is None or candidate is None:
            continue

        s1_name = s1["business_name"]
        s1_address = s1["business_address"]

        c_name = candidate["business_name"]
        c_address = candidate["business_address"]

        feature_rows.append([
            text_similarity(s1_name, c_name),
            text_similarity(s1_address, c_address),
            token_similarity(s1_name, c_name),
            token_similarity(s1_address, c_address),
            number_overlap(s1_address, c_address),
            int(
                normalize_text(s1["country"])
                == normalize_text(candidate["country"])
            ),
            int(
                pd.isna(s1_address)
                or normalize_text(s1_address) == ""
            ),
            int(
                pd.isna(c_address)
                or normalize_text(c_address) == ""
            )
        ])

        valid_rows.append(idx)

    # ----------------------------------------
    # Predict
    # ----------------------------------------

    if len(feature_rows) > 0:

        X_batch = pd.DataFrame(
            feature_rows,
            columns=model_features
        )

        probabilities = final_model.predict_proba(
            X_batch[model_features]
        )[:, 1]

        result = candidates.loc[
            valid_rows
        ].copy()

        result["match_probability"] = probabilities

    else:
        result = pd.DataFrame(
            columns=[
                "source1_entity_id",
                "candidate_entity_id",
                "match_probability"
            ]
        )

    # ----------------------------------------
    # SAVE IMMEDIATELY
    # ----------------------------------------

    result.to_csv(
        output_file,
        sep="\t",
        index=False
    )

    elapsed = time.time() - batch_start

    print(
        f"Saved: {os.path.basename(output_file)}"
    )
    print(
        f"Scored rows: {len(result)}"
    )
    print(
        f"Time: {elapsed:.1f} sec"
    )

    # RAM cleanup
    del candidates
    del s1_batch
    del s2_batch
    del s3_batch
    del s23_batch
    del s1_lookup
    del s23_lookup
    del feature_rows
    del valid_rows
    del X_batch
    del result

    gc.collect()

    ram = psutil.virtual_memory()

    print(
        f"RAM: {ram.percent}% | "
        f"Available: {ram.available / (1024**3):.2f} GB"
    )

print("\n" + "=" * 60)
print("ALL AVAILABLE BATCHES PROCESSED")
print("=" * 60)

In [ ]:
# ============================================
# CELL 25: FAST SCORING SETUP
# ============================================

import os
import gc
import time
import re
import pandas as pd
import numpy as np
import psutil
from rapidfuzz.fuzz import ratio

CAND_DIR = "/kaggle/working/candidates"
SCORED_DIR = "/kaggle/working/scored_candidates"

os.makedirs(SCORED_DIR, exist_ok=True)

# Real 347 candidate batches only
candidate_files = sorted([
    os.path.join(CAND_DIR, f)
    for f in os.listdir(CAND_DIR)
    if f.startswith("name_candidates_batch_")
    and f.endswith(".tsv")
])

print("Candidate batches:", len(candidate_files))

# Check completed scoring
completed = {
    f for f in os.listdir(SCORED_DIR)
    if f.startswith("scored_candidates_batch_")
    and f.endswith(".tsv")
}

print("Already scored:", len(completed))
print("Remaining:", len(candidate_files) - len(completed))

# Check RapidFuzz
print("\nRapidFuzz:", ratio("Amazon", "Amazon"))

# RAM
ram = psutil.virtual_memory()
print("\nRAM:")
print("Used     :", round(ram.used / (1024**3), 2), "GB")
print("Available:", round(ram.available / (1024**3), 2), "GB")
print("Usage    :", ram.percent, "%")

In [ ]:
# ============================================
# CELL 25: FAST SCORING SETUP - NO RAPIDFUZZ
# ============================================

import os
import gc
import time
import re
import pandas as pd
import numpy as np
import psutil
from difflib import SequenceMatcher

CAND_DIR = "/kaggle/working/candidates"
SCORED_DIR = "/kaggle/working/scored_candidates"

os.makedirs(SCORED_DIR, exist_ok=True)

# Only real 347 candidate batches
candidate_files = sorted([
    os.path.join(CAND_DIR, f)
    for f in os.listdir(CAND_DIR)
    if f.startswith("name_candidates_batch_")
    and f.endswith(".tsv")
])

completed = {
    f for f in os.listdir(SCORED_DIR)
    if f.startswith("scored_candidates_batch_")
    and f.endswith(".tsv")
}

print("Candidate batches:", len(candidate_files))
print("Already scored:", len(completed))
print("Remaining:", len(candidate_files) - len(completed))

# Check one candidate file
print("\nExample:")
print(os.path.basename(candidate_files[0]))

# RAM
ram = psutil.virtual_memory()

print("\nRAM:")
print("Used     :", round(ram.used / (1024**3), 2), "GB")
print("Available:", round(ram.available / (1024**3), 2), "GB")
print("Usage    :", ram.percent, "%")

In [ ]:
!pip install rapidfuzz -q

from rapidfuzz import fuzz, process

print("RapidFuzz installed successfully")
print("Test:", fuzz.ratio("amazon india", "amazon india"))

In [ ]:
from rapidfuzz import fuzz

print("RapidFuzz ready")
print("Name test:", fuzz.ratio("amazon india", "amazon india") / 100)

In [ ]:
import os
import pandas as pd
import numpy as np
import re
from rapidfuzz import fuzz

# Scoring folders
scored_dir = "/kaggle/working/scored_candidates"
os.makedirs(scored_dir, exist_ok=True)

# Already completed batches
done_batches = {
    int(f.split("_")[-1].split(".")[0])
    for f in os.listdir(scored_dir)
    if f.startswith("scored_candidates_batch_")
}

print("Already completed:", len(done_batches))
print("Starting from batch:", max(done_batches) + 1 if done_batches else 1)
print("Total candidate batches:", len(candidate_files))

In [ ]:
# FAST SCORING TEST — BATCH 11 ONLY

batch_num = 11
candidate_file = f"/kaggle/working/candidates/name_candidates_batch_{batch_num:03d}.tsv"
output_file = f"/kaggle/working/scored_candidates/scored_candidates_batch_{batch_num:03d}.tsv"

print("Reading:", candidate_file)

candidates = pd.read_csv(candidate_file, sep="\t")

print("Rows:", len(candidates))
print("Columns:", list(candidates.columns))

# Get required IDs
s1_ids = candidates["source1_entity_id"].unique()
candidate_ids = candidates["candidate_entity_id"].unique()

print("Unique Source1 IDs:", len(s1_ids))
print("Unique Candidate IDs:", len(candidate_ids))

In [ ]:
import time
import joblib
import pandas as pd
import numpy as np
import re
from rapidfuzz import fuzz

start_time = time.time()

# Load trained model
model_package = joblib.load(
    "/kaggle/working/student_matching_model_package.pkl"
)

final_model = model_package["model"]
model_features = model_package["features"]

print("Model loaded")
print("Features:", model_features)

# Load test data
s1_data = pd.read_csv(
    test_s1_path,
    sep="\t",
    dtype=str
)

s2_data = pd.read_csv(
    test_s2_path,
    sep="\t",
    dtype=str
)

s3_data = pd.read_csv(
    test_s3_path,
    sep="\t",
    dtype=str
)

# Keep only Batch 11 required records
s1_data = s1_data[
    s1_data["entity_id"].isin(s1_ids)
].copy()

s23_data = pd.concat(
    [s2_data, s3_data],
    ignore_index=True
)

s23_data = s23_data[
    s23_data["entity_id"].isin(candidate_ids)
].copy()

print("S1 records:", len(s1_data))
print("S2/S3 records:", len(s23_data))

print("Setup time:", round(time.time() - start_time, 2), "seconds")

In [ ]:
# FAST FEATURE GENERATION — BATCH 11

import time
import numpy as np
import pandas as pd
import re
from rapidfuzz import fuzz

start = time.time()

# Candidate pairs ko actual records se merge karo
pairs = candidates.merge(
    s1_data[
        ["entity_id", "business_name", "business_address", "country"]
    ],
    left_on="source1_entity_id",
    right_on="entity_id",
    how="left"
).drop(columns=["entity_id"])

pairs = pairs.merge(
    s23_data[
        ["entity_id", "business_name", "business_address", "country"]
    ].rename(columns={
        "entity_id": "candidate_entity_id",
        "business_name": "candidate_business_name",
        "business_address": "candidate_business_address",
        "country": "candidate_country"
    }),
    on="candidate_entity_id",
    how="left"
)

pairs = pairs.rename(columns={
    "business_name": "source1_business_name",
    "business_address": "source1_business_address",
    "country": "source1_country"
})

print("Merged rows:", len(pairs))

# Convert missing values
pairs["source1_business_name"] = pairs["source1_business_name"].fillna("").astype(str)
pairs["candidate_business_name"] = pairs["candidate_business_name"].fillna("").astype(str)
pairs["source1_business_address"] = pairs["source1_business_address"].fillna("").astype(str)
pairs["candidate_business_address"] = pairs["candidate_business_address"].fillna("").astype(str)
pairs["source1_country"] = pairs["source1_country"].fillna("").astype(str)
pairs["candidate_country"] = pairs["candidate_country"].fillna("").astype(str)

# Fast text similarity
pairs["name_similarity"] = [
    fuzz.ratio(a, b) / 100
    for a, b in zip(
        pairs["source1_business_name"],
        pairs["candidate_business_name"]
    )
]

pairs["address_similarity"] = [
    fuzz.ratio(a, b) / 100
    for a, b in zip(
        pairs["source1_business_address"],
        pairs["candidate_business_address"]
    )
]

print("Text similarities completed")

print("Time:", round(time.time() - start, 2), "seconds")

In [ ]:
# REMAINING FEATURES — BATCH 11

import re
import time

start = time.time()

def token_jaccard(a, b):
    a_tokens = set(re.findall(r"\w+", a.lower()))
    b_tokens = set(re.findall(r"\w+", b.lower()))
    
    if not a_tokens and not b_tokens:
        return 1.0
    if not a_tokens or not b_tokens:
        return 0.0
    
    return len(a_tokens & b_tokens) / len(a_tokens | b_tokens)


def number_overlap(a, b):
    nums_a = set(re.findall(r"\d+", a))
    nums_b = set(re.findall(r"\d+", b))
    
    if not nums_a or not nums_b:
        return 0.0
    
    return len(nums_a & nums_b) / len(nums_a | nums_b)


# Token similarity
pairs["name_token_similarity"] = [
    token_jaccard(a, b)
    for a, b in zip(
        pairs["source1_business_name"],
        pairs["candidate_business_name"]
    )
]

pairs["address_token_similarity"] = [
    token_jaccard(a, b)
    for a, b in zip(
        pairs["source1_business_address"],
        pairs["candidate_business_address"]
    )
]

# Number overlap
pairs["number_overlap"] = [
    number_overlap(a, b)
    for a, b in zip(
        pairs["source1_business_address"],
        pairs["candidate_business_address"]
    )
]

# Country match
pairs["country_match"] = (
    pairs["source1_country"].str.lower()
    == pairs["candidate_country"].str.lower()
).astype(int)

# Missing address flags
pairs["source1_address_missing"] = (
    pairs["source1_business_address"].str.strip() == ""
).astype(int)

pairs["candidate_address_missing"] = (
    pairs["candidate_business_address"].str.strip() == ""
).astype(int)

print("All 8 features created")
print("Feature rows:", len(pairs))
print("Time:", round(time.time() - start, 2), "seconds")

print("\nFeature columns:")
print(pairs[model_features].head())

In [ ]:
# MODEL PREDICTION — BATCH 11

start = time.time()

X_batch = pairs[model_features]

# Predict match probability
pairs["match_probability"] = final_model.predict_proba(X_batch)[:, 1]

# Save scored batch
output_file = "/kaggle/working/scored_candidates/scored_candidates_batch_011.tsv"

pairs[
    [
        "source1_entity_id",
        "candidate_entity_id",
        "match_probability"
    ]
].to_csv(
    output_file,
    sep="\t",
    index=False
)

print("Batch 11 scoring completed!")
print("Rows scored:", len(pairs))
print("Output:", output_file)
print("Time:", round(time.time() - start, 2), "seconds")

print("\nProbability summary:")
print(pairs["match_probability"].describe())

In [ ]:
# FAST SCORING: BATCH 12 TO 347

import os
import time
import joblib
import pandas as pd
import numpy as np
import re
from rapidfuzz import fuzz

scored_dir = "/kaggle/working/scored_candidates"

# Load model
model_package = joblib.load(
    "/kaggle/working/student_matching_model_package.pkl"
)

final_model = model_package["model"]
model_features = model_package["features"]

def token_jaccard(a, b):
    a_tokens = set(re.findall(r"\w+", a.lower()))
    b_tokens = set(re.findall(r"\w+", b.lower()))

    if not a_tokens and not b_tokens:
        return 1.0
    if not a_tokens or not b_tokens:
        return 0.0

    return len(a_tokens & b_tokens) / len(a_tokens | b_tokens)


def number_overlap(a, b):
    nums_a = set(re.findall(r"\d+", a))
    nums_b = set(re.findall(r"\d+", b))

    if not nums_a or not nums_b:
        return 0.0

    return len(nums_a & nums_b) / len(nums_a | nums_b)


for batch_num in range(12, 348):

    output_file = os.path.join(
        scored_dir,
        f"scored_candidates_batch_{batch_num:03d}.tsv"
    )

    # Skip already completed batches
    if os.path.exists(output_file):
        print(f"Batch {batch_num}: already done, skipping")
        continue

    start = time.time()

    candidate_file = (
        f"/kaggle/working/candidates/"
        f"name_candidates_batch_{batch_num:03d}.tsv"
    )

    candidates = pd.read_csv(
        candidate_file,
        sep="\t",
        dtype=str
    )

    s1_ids = candidates["source1_entity_id"].unique()
    candidate_ids = candidates["candidate_entity_id"].unique()

    # Load only required records
    s1_batch = pd.read_csv(
        test_s1_path,
        sep="\t",
        dtype=str
    )

    s1_batch = s1_batch[
        s1_batch["entity_id"].isin(s1_ids)
    ].copy()

    s2_batch = pd.read_csv(
        test_s2_path,
        sep="\t",
        dtype=str
    )

    s3_batch = pd.read_csv(
        test_s3_path,
        sep="\t",
        dtype=str
    )

    s23_batch = pd.concat(
        [s2_batch, s3_batch],
        ignore_index=True
    )

    s23_batch = s23_batch[
        s23_batch["entity_id"].isin(candidate_ids)
    ].copy()

    # Merge Source 1
    pairs = candidates.merge(
        s1_batch[
            ["entity_id", "business_name",
             "business_address", "country"]
        ],
        left_on="source1_entity_id",
        right_on="entity_id",
        how="left"
    ).drop(columns=["entity_id"])

    # Merge Source 2 + Source 3
    pairs = pairs.merge(
        s23_batch[
            ["entity_id", "business_name",
             "business_address", "country"]
        ].rename(columns={
            "entity_id": "candidate_entity_id",
            "business_name": "candidate_business_name",
            "business_address": "candidate_business_address",
            "country": "candidate_country"
        }),
        on="candidate_entity_id",
        how="left"
    )

    pairs = pairs.rename(columns={
        "business_name": "source1_business_name",
        "business_address": "source1_business_address",
        "country": "source1_country"
    })

    # Fill missing values
    text_cols = [
        "source1_business_name",
        "candidate_business_name",
        "source1_business_address",
        "candidate_business_address",
        "source1_country",
        "candidate_country"
    ]

    for col in text_cols:
        pairs[col] = pairs[col].fillna("").astype(str)

    # Fast similarity features
    pairs["name_similarity"] = [
        fuzz.ratio(a, b) / 100
        for a, b in zip(
            pairs["source1_business_name"],
            pairs["candidate_business_name"]
        )
    ]

    pairs["address_similarity"] = [
        fuzz.ratio(a, b) / 100
        for a, b in zip(
            pairs["source1_business_address"],
            pairs["candidate_business_address"]
        )
    ]

    pairs["name_token_similarity"] = [
        token_jaccard(a, b)
        for a, b in zip(
            pairs["source1_business_name"],
            pairs["candidate_business_name"]
        )
    ]

    pairs["address_token_similarity"] = [
        token_jaccard(a, b)
        for a, b in zip(
            pairs["source1_business_address"],
            pairs["candidate_business_address"]
        )
    ]

    pairs["number_overlap"] = [
        number_overlap(a, b)
        for a, b in zip(
            pairs["source1_business_address"],
            pairs["candidate_business_address"]
        )
    ]

    pairs["country_match"] = (
        pairs["source1_country"].str.lower()
        == pairs["candidate_country"].str.lower()
    ).astype(int)

    pairs["source1_address_missing"] = (
        pairs["source1_business_address"].str.strip() == ""
    ).astype(int)

    pairs["candidate_address_missing"] = (
        pairs["candidate_business_address"].str.strip() == ""
    ).astype(int)

    # Predict
    pairs["match_probability"] = (
        final_model.predict_proba(
            pairs[model_features]
        )[:, 1]
    )

    # Save
    pairs[
        [
            "source1_entity_id",
            "candidate_entity_id",
            "match_probability"
        ]
    ].to_csv(
        output_file,
        sep="\t",
        index=False
    )

    print(
        f"Batch {batch_num:03d} done | "
        f"Rows: {len(pairs):,} | "
        f"Time: {time.time() - start:.1f}s"
    )

print("\nALL REMAINING BATCHES COMPLETED!")

In [ ]:
import os

scored_files = [
    f for f in os.listdir("/kaggle/working/scored_candidates")
    if f.startswith("scored_candidates_batch_")
    and f.endswith(".tsv")
]

print("Scored batches:", len(scored_files))
print("Last few files:", sorted(scored_files)[-5:])

In [ ]:
import os

print("Working folders:")
print(os.listdir("/kaggle/working")[:50])

print("\nScored candidates folder exists:",
      os.path.exists("/kaggle/working/scored_candidates"))

print("Candidates folder exists:",
      os.path.exists("/kaggle/working/candidates"))

In [ ]:
import os

print("Input datasets:")
for root, dirs, files in os.walk("/kaggle/input"):
    for f in files:
        if f.endswith(".tsv") or f.endswith(".pkl"):
            print(os.path.join(root, f))

In [ ]:
import os

print("All datasets under /kaggle/input/datasets:")
for name in os.listdir("/kaggle/input/datasets"):
    print(name)

In [ ]:
import os

base = "/kaggle/input/datasets/harshnagayach1908"

for root, dirs, files in os.walk(base):
    level = root.replace(base, "").count(os.sep)
    indent = "  " * level
    print(indent + os.path.basename(root) + "/")
    for f in files[:10]:
        print(indent + "  " + f)

In [ ]:
import json

path = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-final/notebookda02e89746.ipynb"

with open(path, "r", encoding="utf-8") as f:
    nb = json.load(f)

print("Total cells:", len(nb["cells"]))

for i, cell in enumerate(nb["cells"]):
    text = "".join(cell.get("source", []))
    
    if any(x in text.lower() for x in [
        "joblib.dump",
        "pickle.dump",
        "student_matching",
        "final_model",
        "randomforest"
    ]):
        print("\n--- CELL", i, "---")
        print(text[:3000])

In [ ]:
import os

# Check current working directory
print("Working directory:")
print(os.listdir("/kaggle/working"))

# Check notebook output folder
print("\nNotebook folder:")
print(os.listdir("/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-final"))

In [ ]:
import pandas as pd

base = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train"

train_s1 = pd.read_csv(f"{base}/train_source1.tsv", sep="\t")
train_s2 = pd.read_csv(f"{base}/train_source2.tsv", sep="\t")
train_s3 = pd.read_csv(f"{base}/train_source3.tsv", sep="\t")
ground_truth = pd.read_csv(f"{base}/train_ground_truth.tsv", sep="\t")

print("Source 1:", train_s1.shape)
print("Source 2:", train_s2.shape)
print("Source 3:", train_s3.shape)
print("Ground Truth:", ground_truth.shape)

print("\nGround Truth columns:")
print(ground_truth.columns.tolist())

In [ ]:
import pandas as pd
import numpy as np

# Ground truth se valid matches
positive_pairs = []

for _, row in ground_truth.iterrows():
    s1_id = row["source1_entity_id"]
    matched = row["matched_entity_ids"]

    if pd.notna(matched):
        for s23_id in str(matched).split(","):
            positive_pairs.append((s1_id, s23_id.strip()))

positive_pairs = pd.DataFrame(
    positive_pairs,
    columns=["source1_entity_id", "candidate_entity_id"]
)

print("Total positive pairs:", len(positive_pairs))
print("\nSample:")
print(positive_pairs.head())

In [ ]:
# 5,000 positive pairs
positive_sample = positive_pairs.sample(
    n=5000,
    random_state=42
).copy()

# Source 1 IDs jinke liye true matches already hain
true_match_set = set(
    zip(
        positive_pairs["source1_entity_id"],
        positive_pairs["candidate_entity_id"]
    )
)

# Random negative pairs
rng = np.random.default_rng(42)

s1_ids = train_s1["entity_id"].values
s23_ids = pd.concat([
    train_s2["entity_id"],
    train_s3["entity_id"]
]).values

negative_pairs = []

while len(negative_pairs) < 5000:
    s1_batch = rng.choice(s1_ids, 10000)
    s23_batch = rng.choice(s23_ids, 10000)

    for s1_id, s23_id in zip(s1_batch, s23_batch):
        if (s1_id, s23_id) not in true_match_set:
            negative_pairs.append((s1_id, s23_id))

            if len(negative_pairs) >= 5000:
                break

negative_sample = pd.DataFrame(
    negative_pairs,
    columns=["source1_entity_id", "candidate_entity_id"]
)

# Labels
positive_sample["label"] = 1
negative_sample["label"] = 0

training_pairs = pd.concat(
    [positive_sample, negative_sample],
    ignore_index=True
)

print("Positive pairs:", len(positive_sample))
print("Negative pairs:", len(negative_sample))
print("Total training pairs:", len(training_pairs))

print("\nLabel distribution:")
print(training_pairs["label"].value_counts())

In [ ]:
from difflib import SequenceMatcher
import re
import pandas as pd
import numpy as np

def normalize_text(text):
    if pd.isna(text):
        return ""
    return re.sub(r"\s+", " ", str(text).lower()).strip()

def token_jaccard(a, b):
    a_tokens = set(normalize_text(a).split())
    b_tokens = set(normalize_text(b).split())

    if not a_tokens and not b_tokens:
        return 1.0
    if not a_tokens or not b_tokens:
        return 0.0

    return len(a_tokens & b_tokens) / len(a_tokens | b_tokens)

def number_overlap(a, b):
    nums_a = set(re.findall(r"\d+", str(a)))
    nums_b = set(re.findall(r"\d+", str(b)))

    if not nums_a or not nums_b:
        return 0.0

    return len(nums_a & nums_b) / len(nums_a | nums_b)

# Required IDs only
s1_ids = set(training_pairs["source1_entity_id"])
s23_ids = set(training_pairs["candidate_entity_id"])

s1_lookup = train_s1[
    train_s1["entity_id"].isin(s1_ids)
].set_index("entity_id")

s23_all = pd.concat([train_s2, train_s3], ignore_index=True)

s23_lookup = s23_all[
    s23_all["entity_id"].isin(s23_ids)
].set_index("entity_id")

print("S1 lookup:", len(s1_lookup))
print("S2/S3 lookup:", len(s23_lookup))

feature_rows = []

for _, row in training_pairs.iterrows():

    s1 = s1_lookup.loc[row["source1_entity_id"]]
    s23 = s23_lookup.loc[row["candidate_entity_id"]]

    name1 = normalize_text(s1["business_name"])
    name2 = normalize_text(s23["business_name"])

    addr1 = normalize_text(s1["business_address"])
    addr2 = normalize_text(s23["business_address"])

    feature_rows.append({
        "name_similarity": SequenceMatcher(None, name1, name2).ratio(),
        "address_similarity": SequenceMatcher(None, addr1, addr2).ratio(),
        "name_token_similarity": token_jaccard(name1, name2),
        "address_token_similarity": token_jaccard(addr1, addr2),
        "number_overlap": number_overlap(addr1, addr2),
        "country_match": int(
            normalize_text(s1["country"]) ==
            normalize_text(s23["country"])
        ),
        "source1_address_missing": int(not addr1),
        "candidate_address_missing": int(not addr2),
        "label": row["label"]
    })

features_df = pd.DataFrame(feature_rows)

print("\nFeature shape:", features_df.shape)
print("\nFeatures:")
print(features_df.head())

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import joblib
import os

# Features and label
features = [
    "name_similarity",
    "address_similarity",
    "name_token_similarity",
    "address_token_similarity",
    "number_overlap",
    "country_match",
    "source1_address_missing",
    "candidate_address_missing"
]

X = features_df[features]
y = features_df["label"]

# Train / validation split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training rows:", len(X_train))
print("Validation rows:", len(X_test))

# Random Forest
final_model = RandomForestClassifier(
    n_estimators=300,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

print("\nTraining model...")
final_model.fit(X_train, y_train)

# Validation
y_pred = final_model.predict(X_test)

print("\n========== CLASSIFICATION REPORT ==========")
print(classification_report(y_test, y_pred, digits=4))

print("========== CONFUSION MATRIX ==========")
print(confusion_matrix(y_test, y_pred))

# Save model + feature list
model_package = {
    "model": final_model,
    "features": features
}

model_path = "/kaggle/working/student_matching_model_package.pkl"

joblib.dump(model_package, model_path)

print("\n✅ MODEL SAVED")
print("File:", model_path)
print(
    "Size:",
    round(os.path.getsize(model_path) / (1024 * 1024), 2),
    "MB"
)

In [ ]:
import os
import duckdb

candidate_dir = "/kaggle/working/candidates"
os.makedirs(candidate_dir, exist_ok=True)

con = duckdb.connect()

con.execute("SET memory_limit='12GB'")
con.execute("SET threads=2")
con.execute("SET preserve_insertion_order=false")
con.execute("SET max_temp_directory_size='4GB'")

print("DuckDB ready")
print("Candidate folder:", candidate_dir)

In [ ]:
import os

s1_path = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source1.tsv"
s2_path = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source2.tsv"
s3_path = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source3.tsv"

batch_num = 1
offset = 0
limit = 5000

output_file = f"/kaggle/working/candidates/name_candidates_batch_{batch_num:03d}.tsv"

print("Generating Batch 1...")
print("Output:", output_file)

con.execute(f"""
COPY (
    WITH s1 AS (
        SELECT
            entity_id AS source1_entity_id,
            business_name,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s1_path}', delim='\\t')
        LIMIT {limit} OFFSET {offset}
    ),

    s23 AS (
        SELECT
            entity_id AS candidate_entity_id,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s2_path}', delim='\\t')

        UNION ALL

        SELECT
            entity_id AS candidate_entity_id,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{s3_path}', delim='\\t')
    ),

    joined AS (
        SELECT
            s1.source1_entity_id,
            s23.candidate_entity_id,
            levenshtein(
                left(s1.clean_name, 30),
                left(s23.clean_name, 30)
            ) AS edit_distance
        FROM s1
        JOIN s23
          ON s1.country = s23.country
         AND length(s1.clean_name) >= 5
         AND length(s23.clean_name) >= 5
         AND left(s1.clean_name, 5) = left(s23.clean_name, 5)
    ),

    ranked AS (
        SELECT
            source1_entity_id,
            candidate_entity_id,
            edit_distance,
            row_number() OVER (
                PARTITION BY source1_entity_id
                ORDER BY edit_distance
            ) AS rn
        FROM joined
    )

    SELECT
        source1_entity_id,
        candidate_entity_id
    FROM ranked
    WHERE rn <= 50
)
TO '{output_file}'
(FORMAT CSV, HEADER TRUE, DELIMITER '\\t');
""")

print("\n✅ Batch 1 completed!")

if os.path.exists(output_file):
    size_mb = os.path.getsize(output_file) / (1024 * 1024)
    print("File size:", round(size_mb, 2), "MB")
    print("File:", output_file)

In [ ]:
import os

print("Candidate files currently available:")

files = []

for root, dirs, filenames in os.walk("/kaggle"):
    for f in filenames:
        if "name_candidates_batch_" in f:
            files.append(os.path.join(root, f))

print("Total candidate files found:", len(files))

for f in sorted(files)[:10]:
    print(f)

if len(files) > 10:
    print("...")
    for f in sorted(files)[-10:]:
        print(f)

In [ ]:
import pandas as pd
import os

path = "/kaggle/working/candidates/name_candidates_batch_001.tsv"

df = pd.read_csv(path, sep="\t")

print("Rows:", len(df))
print("Columns:", df.columns.tolist())
print("Unique Source1 IDs:", df["source1_entity_id"].nunique())
print("Unique Candidate IDs:", df["candidate_entity_id"].nunique())
print("File size:", round(os.path.getsize(path) / (1024 * 1024), 2), "MB")

In [ ]:
import os
import time

total_s1 = 1732544
batch_size = 5000
total_batches = (total_s1 + batch_size - 1) // batch_size

print("Total batches:", total_batches)
print("Already completed: 1")
print("Remaining:", total_batches - 1)

for batch_num in range(2, total_batches + 1):

    output_file = (
        f"/kaggle/working/candidates/"
        f"name_candidates_batch_{batch_num:03d}.tsv"
    )

    # Don't regenerate an existing batch
    if os.path.exists(output_file):
        print(f"Batch {batch_num} already exists — skipping")
        continue

    offset = (batch_num - 1) * batch_size
    start = time.time()

    print(f"\nStarting Batch {batch_num}/{total_batches}...")

    con.execute(f"""
    COPY (
        WITH s1 AS (
            SELECT
                entity_id AS source1_entity_id,
                country,
                regexp_replace(
                    lower(coalesce(business_name, '')),
                    '[^a-zA-Z0-9]', '', 'g'
                ) AS clean_name
            FROM read_csv_auto('{s1_path}', delim='\\t')
            LIMIT {batch_size} OFFSET {offset}
        ),

        joined AS (
            SELECT
                s1.source1_entity_id,
                s23.candidate_entity_id,
                levenshtein(
                    left(s1.clean_name, 30),
                    left(s23.clean_name, 30)
                ) AS edit_distance
            FROM s1
            JOIN s23_index s23
              ON s1.country = s23.country
             AND length(s1.clean_name) >= 5
             AND length(s23.clean_name) >= 5
             AND left(s1.clean_name, 5) = left(s23.clean_name, 5)
        ),

        ranked AS (
            SELECT
                source1_entity_id,
                candidate_entity_id,
                edit_distance,
                row_number() OVER (
                    PARTITION BY source1_entity_id
                    ORDER BY edit_distance
                ) AS rn
            FROM joined
        )

        SELECT
            source1_entity_id,
            candidate_entity_id
        FROM ranked
        WHERE rn <= 50
    )
    TO '{output_file}'
    (FORMAT CSV, HEADER TRUE, DELIMITER '\\t');
    """)

    elapsed = time.time() - start

    rows = con.execute(
        f"SELECT COUNT(*) FROM read_csv_auto('{output_file}', delim='\\t')"
    ).fetchone()[0]

    print(
        f"Batch {batch_num} done | "
        f"Rows: {rows:,} | "
        f"Time: {elapsed:.1f}s"
    )

print("\n🎉 Candidate generation finished!")

In [ ]:
# Recreate S2 + S3 index for current DuckDB session

con.execute("DROP TABLE IF EXISTS s23_index")

print("Creating S23 index...")

con.execute(f"""
CREATE TABLE s23_index AS

SELECT
    entity_id AS candidate_entity_id,
    country,
    regexp_replace(
        lower(coalesce(business_name, '')),
        '[^a-zA-Z0-9]', '', 'g'
    ) AS clean_name
FROM read_csv_auto('{s2_path}', delim='\\t')

UNION ALL

SELECT
    entity_id AS candidate_entity_id,
    country,
    regexp_replace(
        lower(coalesce(business_name, '')),
        '[^a-zA-Z0-9]', '', 'g'
    ) AS clean_name
FROM read_csv_auto('{s3_path}', delim='\\t')
""")

count = con.execute(
    "SELECT COUNT(*) FROM s23_index"
).fetchone()[0]

print("✅ S23 index created")
print("Total S2 + S3 records:", f"{count:,}")

In [ ]:
import os
import time

total_s1 = 1732544
batch_size = 5000
total_batches = (total_s1 + batch_size - 1) // batch_size

for batch_num in range(2, total_batches + 1):

    output_file = (
        f"/kaggle/working/candidates/"
        f"name_candidates_batch_{batch_num:03d}.tsv"
    )

    if os.path.exists(output_file):
        print(f"Batch {batch_num} already exists — skipping")
        continue

    offset = (batch_num - 1) * batch_size
    start = time.time()

    print(f"\nStarting Batch {batch_num}/{total_batches}...")

    con.execute(f"""
    COPY (
        WITH s1 AS (
            SELECT
                entity_id AS source1_entity_id,
                country,
                regexp_replace(
                    lower(coalesce(business_name, '')),
                    '[^a-zA-Z0-9]', '', 'g'
                ) AS clean_name
            FROM read_csv_auto('{s1_path}', delim='\\t')
            LIMIT {batch_size} OFFSET {offset}
        ),

        joined AS (
            SELECT
                s1.source1_entity_id,
                s23.candidate_entity_id,
                levenshtein(
                    left(s1.clean_name, 30),
                    left(s23.clean_name, 30)
                ) AS edit_distance
            FROM s1
            JOIN s23_index s23
              ON s1.country = s23.country
             AND length(s1.clean_name) >= 5
             AND length(s23.clean_name) >= 5
             AND left(s1.clean_name, 5) = left(s23.clean_name, 5)
        ),

        ranked AS (
            SELECT
                source1_entity_id,
                candidate_entity_id,
                edit_distance,
                row_number() OVER (
                    PARTITION BY source1_entity_id
                    ORDER BY edit_distance
                ) AS rn
            FROM joined
        )

        SELECT
            source1_entity_id,
            candidate_entity_id
        FROM ranked
        WHERE rn <= 50
    )
    TO '{output_file}'
    (FORMAT CSV, HEADER TRUE, DELIMITER '\\t');
    """)

    elapsed = time.time() - start

    rows = con.execute(
        f"SELECT COUNT(*) FROM read_csv_auto('{output_file}', delim='\\t')"
    ).fetchone()[0]

    print(
        f"Batch {batch_num} done | "
        f"Rows: {rows:,} | "
        f"Time: {elapsed:.1f}s"
    )

In [ ]:
import os
import glob

files = sorted(
    glob.glob("/kaggle/working/candidates/name_candidates_batch_*.tsv")
)

print("Candidate files:", len(files))

if files:
    print("First:", os.path.basename(files[0]))
    print("Last:", os.path.basename(files[-1]))

In [ ]:
print("S23 index exists:", 
      con.execute("""
      SELECT COUNT(*) 
      FROM s23_index
      """).fetchone()[0])

In [ ]:
import os
import time

start_batch = 42
end_batch = 51
batch_size = 5000

for batch_num in range(start_batch, end_batch + 1):

    output_file = (
        f"/kaggle/working/candidates/"
        f"name_candidates_batch_{batch_num:03d}.tsv"
    )

    if os.path.exists(output_file):
        print(f"Batch {batch_num} already exists — skipping")
        continue

    offset = (batch_num - 1) * batch_size
    start = time.time()

    con.execute(f"""
    COPY (
        WITH s1 AS (
            SELECT
                entity_id AS source1_entity_id,
                country,
                regexp_replace(
                    lower(coalesce(business_name, '')),
                    '[^a-zA-Z0-9]', '', 'g'
                ) AS clean_name
            FROM read_csv_auto('{s1_path}', delim='\\t')
            LIMIT {batch_size} OFFSET {offset}
        ),
        joined AS (
            SELECT
                s1.source1_entity_id,
                s23.candidate_entity_id,
                levenshtein(
                    left(s1.clean_name, 30),
                    left(s23.clean_name, 30)
                ) AS edit_distance
            FROM s1
            JOIN s23_index s23
              ON s1.country = s23.country
             AND length(s1.clean_name) >= 5
             AND length(s23.clean_name) >= 5
             AND left(s1.clean_name, 5) = left(s23.clean_name, 5)
        ),
        ranked AS (
            SELECT
                source1_entity_id,
                candidate_entity_id,
                edit_distance,
                row_number() OVER (
                    PARTITION BY source1_entity_id
                    ORDER BY edit_distance
                ) AS rn
            FROM joined
        )
        SELECT
            source1_entity_id,
            candidate_entity_id
        FROM ranked
        WHERE rn <= 50
    )
    TO '{output_file}'
    (FORMAT CSV, HEADER TRUE, DELIMITER '\\t');
    """)

    rows = con.execute(
        f"SELECT COUNT(*) FROM read_csv_auto('{output_file}', delim='\\t')"
    ).fetchone()[0]

    print(
        f"Batch {batch_num} done | "
        f"Rows: {rows:,} | "
        f"Time: {time.time() - start:.1f}s"
    )

print("\n✅ Test batches 42–51 completed.")

In [ ]:
import os
import time
import duckdb

# Existing DuckDB connection
con.execute("SET memory_limit='12GB'")
con.execute("SET threads=4")
con.execute("SET preserve_insertion_order=false")
con.execute("SET max_temp_directory_size='4GB'")

candidate_dir = "/kaggle/working/candidates"
os.makedirs(candidate_dir, exist_ok=True)

# Test only batches 52 and 53
for batch_no in [52, 53]:

    output_file = f"{candidate_dir}/name_candidates_batch_{batch_no:03d}.tsv"

    if os.path.exists(output_file):
        print(f"Batch {batch_no} already exists — skipping")
        continue

    offset = (batch_no - 1) * 5000
    limit = 5000

    start = time.time()

    query = f"""
    COPY (
        WITH s1 AS (
            SELECT
                entity_id AS source1_entity_id,
                business_name,
                country,
                regexp_replace(
                    lower(coalesce(business_name, '')),
                    '[^a-zA-Z0-9]', '', 'g'
                ) AS clean_name
            FROM read_csv_auto('{s1_path}', delim='\\t')
            LIMIT {limit} OFFSET {offset}
        ),
        joined AS (
            SELECT
                s1.source1_entity_id,
                s23.candidate_entity_id,
                levenshtein(
                    left(s1.clean_name,30),
                    left(s23.clean_name,30)
                ) AS edit_distance
            FROM s1
            JOIN s23_index s23
              ON s1.country = s23.country
             AND length(s1.clean_name) >= 5
             AND length(s23.clean_name) >= 5
             AND left(s1.clean_name,5) = left(s23.clean_name,5)
        ),
        ranked AS (
            SELECT
                source1_entity_id,
                candidate_entity_id,
                edit_distance,
                row_number() OVER (
                    PARTITION BY source1_entity_id
                    ORDER BY edit_distance
                ) AS rn
            FROM joined
        )
        SELECT
            source1_entity_id,
            candidate_entity_id
        FROM ranked
        WHERE rn <= 50
    )
    TO '{output_file}'
    (FORMAT CSV, HEADER TRUE, DELIMITER '\\t');
    """

    con.execute(query)

    elapsed = time.time() - start
    print(
        f"Batch {batch_no} done | "
        f"Time: {elapsed:.1f}s"
    )

In [ ]:
import os
import time

candidate_dir = "/kaggle/working/candidates"
os.makedirs(candidate_dir, exist_ok=True)

con.execute("SET memory_limit='12GB'")
con.execute("SET threads=4")
con.execute("SET preserve_insertion_order=false")
con.execute("SET max_temp_directory_size='4GB'")

for batch_no in range(54, 348):

    output_file = f"{candidate_dir}/name_candidates_batch_{batch_no:03d}.tsv"

    # Already completed batch ko skip karo
    if os.path.exists(output_file):
        print(f"Batch {batch_no} already exists — skipping")
        continue

    offset = (batch_no - 1) * 5000
    limit = 5000

    start = time.time()

    query = f"""
    COPY (
        WITH s1 AS (
            SELECT
                entity_id AS source1_entity_id,
                business_name,
                country,
                regexp_replace(
                    lower(coalesce(business_name, '')),
                    '[^a-zA-Z0-9]', '', 'g'
                ) AS clean_name
            FROM read_csv_auto('{s1_path}', delim='\\t')
            LIMIT {limit} OFFSET {offset}
        ),
        joined AS (
            SELECT
                s1.source1_entity_id,
                s23.candidate_entity_id,
                levenshtein(
                    left(s1.clean_name,30),
                    left(s23.clean_name,30)
                ) AS edit_distance
            FROM s1
            JOIN s23_index s23
              ON s1.country = s23.country
             AND length(s1.clean_name) >= 5
             AND length(s23.clean_name) >= 5
             AND left(s1.clean_name,5) = left(s23.clean_name,5)
        ),
        ranked AS (
            SELECT
                source1_entity_id,
                candidate_entity_id,
                edit_distance,
                row_number() OVER (
                    PARTITION BY source1_entity_id
                    ORDER BY edit_distance
                ) AS rn
            FROM joined
        )
        SELECT
            source1_entity_id,
            candidate_entity_id
        FROM ranked
        WHERE rn <= 50
    )
    TO '{output_file}'
    (FORMAT CSV, HEADER TRUE, DELIMITER '\\t');
    """

    con.execute(query)

    elapsed = time.time() - start

    print(
        f"Batch {batch_no} done | "
        f"Time: {elapsed:.1f}s"
    )

In [ ]:
import os
import glob
import pandas as pd

candidate_dir = "/kaggle/working/candidates"

files = sorted(glob.glob(f"{candidate_dir}/name_candidates_batch_*.tsv"))

print("Files:", len(files))

# Top candidate = first candidate in each S1 group
top_candidates = []

for i, f in enumerate(files, 1):
    df = pd.read_csv(f, sep="\t")

    # candidate files are already ranked by edit distance
    df = df.drop_duplicates("source1_entity_id", keep="first")

    top_candidates.append(df)

    if i % 50 == 0:
        print(f"Processed {i}/347 files")

top_candidates = pd.concat(top_candidates, ignore_index=True)

print("\nTop candidates:", len(top_candidates))
print("Unique Source1:", top_candidates["source1_entity_id"].nunique())

top_candidates.to_csv(
    "/kaggle/working/top_candidates.tsv",
    sep="\t",
    index=False
)

print("✅ Saved: /kaggle/working/top_candidates.tsv")

In [ ]:
import os
import glob

print("Candidates folder exists:",
      os.path.exists("/kaggle/working/candidates"))

print("\nWorking directory:")
print(os.listdir("/kaggle/working")[:30])

print("\nCandidate files found:")
files = glob.glob("/kaggle/working/candidates/*")

print("Total:", len(files))

for f in files[:10]:
    print(f)

In [ ]:
import os

print("INPUT DATASETS:\n")

for root, dirs, files in os.walk("/kaggle/input"):
    level = root.replace("/kaggle/input", "").count(os.sep)
    if level <= 2:
        print(root)
        for f in files[:10]:
            print("   ", f)

In [ ]:
import os

base = "/kaggle/input/datasets/harshnagayach1908"

for name in os.listdir(base):
    path = os.path.join(base, name)
    print(name, "  <--", "DIR" if os.path.isdir(path) else "FILE")

In [ ]:
import os

base = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-final"

for root, dirs, files in os.walk(base):
    print("\n", root)
    for f in files[:20]:
        print("   ", f)

In [ ]:
import os

for root, dirs, files in os.walk("/kaggle/working"):
    for f in files:
        if f.endswith(".pkl"):
            print("MODEL:", os.path.join(root, f))

print("\nInput model files:")
for root, dirs, files in os.walk("/kaggle/input"):
    for f in files:
        if f.endswith(".pkl"):
            print("MODEL:", os.path.join(root, f))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import pandas as pd
import numpy as np
import re
from difflib import SequenceMatcher

# Paths
base = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/train"

s1_path = base + "/train_source1.tsv"
s2_path = base + "/train_source2.tsv"
s3_path = base + "/train_source3.tsv"
gt_path = base + "/train_ground_truth.tsv"

print("Loading training data...")

s1 = pd.read_csv(s1_path, sep="\t")
s2 = pd.read_csv(s2_path, sep="\t")
s3 = pd.read_csv(s3_path, sep="\t")
gt = pd.read_csv(gt_path, sep="\t")

print("Loaded:")
print("S1:", s1.shape)
print("S2:", s2.shape)
print("S3:", s3.shape)
print("GT:", gt.shape)

In [ ]:
# Ground truth se positive pairs
true_matches = {}

for _, row in gt.iterrows():
    s1_id = row["source1_entity_id"]
    matched = row["matched_entity_ids"]

    if pd.notna(matched) and str(matched).strip():
        ids = str(matched).split(",")
        true_matches[s1_id] = set(x.strip() for x in ids)

# Positive pairs
positive_pairs = []

for s1_id, candidate_ids in true_matches.items():
    for cid in candidate_ids:
        positive_pairs.append((s1_id, cid))

positive_pairs = pd.DataFrame(
    positive_pairs,
    columns=["source1_entity_id", "candidate_entity_id"]
)

print("Positive pairs:", len(positive_pairs))

# 5,000 positive
positive_sample = positive_pairs.sample(
    n=min(5000, len(positive_pairs)),
    random_state=42
)

# Candidate lookup
s1_dict = s1.set_index("entity_id").to_dict("index")

s23 = pd.concat([s2, s3], ignore_index=True)
s23_dict = s23.set_index("entity_id").to_dict("index")

# Negative pairs
rng = np.random.default_rng(42)

negative_pairs = []

s1_ids = list(s1_dict.keys())
s23_ids = list(s23_dict.keys())

positive_set = set(
    (r["source1_entity_id"], r["candidate_entity_id"])
    for _, r in positive_pairs.iterrows()
)

while len(negative_pairs) < 5000:
    a = rng.choice(s1_ids)
    b = rng.choice(s23_ids)

    if (a, b) not in positive_set:
        negative_pairs.append((a, b))

negative_sample = pd.DataFrame(
    negative_pairs,
    columns=["source1_entity_id", "candidate_entity_id"]
)

print("Positive sample:", len(positive_sample))
print("Negative sample:", len(negative_sample))

In [ ]:
# FAST SAMPLING — no slow while loop

import pandas as pd
import numpy as np

# 5,000 positive pairs
positive_sample = positive_pairs.sample(
    n=5000,
    random_state=42
).reset_index(drop=True)

# IDs as numpy arrays
s1_ids = s1["entity_id"].dropna().astype(str).values
s23_ids = pd.concat([
    s2["entity_id"],
    s3["entity_id"]
]).dropna().astype(str).values

# Positive pair keys
positive_keys = set(
    positive_sample["source1_entity_id"].astype(str)
    + "||" +
    positive_sample["candidate_entity_id"].astype(str)
)

# Generate a large random pool ONCE
rng = np.random.default_rng(42)

neg_s1 = rng.choice(s1_ids, size=20000)
neg_s23 = rng.choice(s23_ids, size=20000)

negative_sample = pd.DataFrame({
    "source1_entity_id": neg_s1,
    "candidate_entity_id": neg_s23
})

# Remove actual positive pairs
negative_sample["key"] = (
    negative_sample["source1_entity_id"]
    + "||" +
    negative_sample["candidate_entity_id"]
)

negative_sample = negative_sample[
    ~negative_sample["key"].isin(positive_keys)
].drop(columns="key").drop_duplicates()

# Take 5,000
negative_sample = negative_sample.head(5000).reset_index(drop=True)

print("Positive sample:", len(positive_sample))
print("Negative sample:", len(negative_sample))

# Combine
train_pairs = pd.concat(
    [positive_sample, negative_sample],
    ignore_index=True
)

train_pairs["label"] = (
    [1] * len(positive_sample) +
    [0] * len(negative_sample)
)

print("Total training pairs:", len(train_pairs))
print("\nLabel distribution:")
print(train_pairs["label"].value_counts())

In [ ]:
from difflib import SequenceMatcher
import re
import pandas as pd
import numpy as np

def normalize_text(x):
    if pd.isna(x):
        return ""
    return re.sub(r"\s+", " ", str(x).lower()).strip()

def token_jaccard(a, b):
    a = set(normalize_text(a).split())
    b = set(normalize_text(b).split())

    if not a and not b:
        return 1.0
    if not a or not b:
        return 0.0

    return len(a & b) / len(a | b)

def number_overlap(a, b):
    nums_a = set(re.findall(r"\d+", str(a)))
    nums_b = set(re.findall(r"\d+", str(b)))

    if not nums_a or not nums_b:
        return 0.0

    return len(nums_a & nums_b) / len(nums_a | nums_b)

# Small lookup tables
s1_lookup = s1.set_index("entity_id")
s23_lookup = pd.concat([s2, s3]).set_index("entity_id")

features = []

for _, row in train_pairs.iterrows():

    a = s1_lookup.loc[row["source1_entity_id"]]
    b = s23_lookup.loc[row["candidate_entity_id"]]

    name1 = normalize_text(a["business_name"])
    name2 = normalize_text(b["business_name"])

    addr1 = normalize_text(a["business_address"])
    addr2 = normalize_text(b["business_address"])

    features.append([
        SequenceMatcher(None, name1, name2).ratio(),
        SequenceMatcher(None, addr1, addr2).ratio(),
        token_jaccard(name1, name2),
        token_jaccard(addr1, addr2),
        number_overlap(addr1, addr2),
        int(str(a["country"]).lower() == str(b["country"]).lower()),
        int(not addr1),
        int(not addr2),
        row["label"]
    ])

feature_cols = [
    "name_similarity",
    "address_similarity",
    "name_token_similarity",
    "address_token_similarity",
    "number_overlap",
    "country_match",
    "source1_address_missing",
    "candidate_address_missing",
    "label"
]

features = pd.DataFrame(features, columns=feature_cols)

print("Feature shape:", features.shape)
print(features.head())

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import joblib

X = features.drop(columns=["label"])
y = features["label"]

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

final_model = RandomForestClassifier(
    n_estimators=300,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

print("Training model...")

final_model.fit(X_train, y_train)

pred = final_model.predict(X_val)

print("\nValidation Results:")
print(classification_report(y_val, pred))
print("Confusion Matrix:")
print(confusion_matrix(y_val, pred))

# Save model
model_package = {
    "model": final_model,
    "features": list(X.columns)
}

model_path = "/kaggle/working/student_matching_model_package.pkl"

joblib.dump(model_package, model_path)

print("\n✅ Model saved:", model_path)

In [ ]:
import pandas as pd
import os

test_base = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test"

test_s1_path = test_base + "/test_source1.tsv"
test_s2_path = test_base + "/test_source2.tsv"
test_s3_path = test_base + "/test_source3.tsv"

test_s1 = pd.read_csv(test_s1_path, sep="\t")
test_s2 = pd.read_csv(test_s2_path, sep="\t")
test_s3 = pd.read_csv(test_s3_path, sep="\t")

print("Test S1:", test_s1.shape)
print("Test S2:", test_s2.shape)
print("Test S3:", test_s3.shape)

In [ ]:
import duckdb
import os

candidate_dir = "/kaggle/working/fast_candidates"
os.makedirs(candidate_dir, exist_ok=True)

con = duckdb.connect()

con.execute("SET memory_limit='12GB'")
con.execute("SET threads=2")
con.execute("SET preserve_insertion_order=false")
con.execute("SET max_temp_directory_size='4GB'")

print("Creating S2 + S3 index...")

con.execute("DROP TABLE IF EXISTS s23_index")

con.execute(f"""
CREATE TABLE s23_index AS

SELECT
    entity_id AS candidate_entity_id,
    country,
    regexp_replace(
        lower(coalesce(business_name, '')),
        '[^a-zA-Z0-9]', '', 'g'
    ) AS clean_name
FROM read_csv_auto('{test_s2_path}', delim='\t')

UNION ALL

SELECT
    entity_id AS candidate_entity_id,
    country,
    regexp_replace(
        lower(coalesce(business_name, '')),
        '[^a-zA-Z0-9]', '', 'g'
    ) AS clean_name
FROM read_csv_auto('{test_s3_path}', delim='\t')
""")

print("✅ S23 index created")

count = con.execute(
    "SELECT COUNT(*) FROM s23_index"
).fetchone()[0]

print("Total S2 + S3 records:", count)

In [ ]:
batch_size = 5000
offset = 0

output_file = f"{candidate_dir}/test_batch_001.tsv"

query = f"""
COPY (
    WITH s1 AS (
        SELECT
            entity_id AS source1_entity_id,
            business_name,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{test_s1_path}', delim='\t')
        LIMIT {batch_size} OFFSET {offset}
    ),

    joined AS (
        SELECT
            s1.source1_entity_id,
            s23.candidate_entity_id,
            levenshtein(
                left(s1.clean_name, 30),
                left(s23.clean_name, 30)
            ) AS edit_distance
        FROM s1
        JOIN s23_index s23
          ON s1.country = s23.country
         AND length(s1.clean_name) >= 5
         AND length(s23.clean_name) >= 5
         AND left(s1.clean_name, 5) = left(s23.clean_name, 5)
    ),

    ranked AS (
        SELECT
            source1_entity_id,
            candidate_entity_id,
            edit_distance,
            row_number() OVER (
                PARTITION BY source1_entity_id
                ORDER BY edit_distance
            ) AS rn
        FROM joined
    )

    SELECT
        source1_entity_id,
        candidate_entity_id,
        edit_distance
    FROM ranked
    WHERE rn <= 5
)
TO '{output_file}'
(FORMAT CSV, HEADER TRUE, DELIMITER '\t');
"""

print("Generating test batch...")
con.execute(query)

check = pd.read_csv(output_file, sep="\t")

print("✅ Batch generated")
print("Rows:", len(check))
print("Unique Source1:", check["source1_entity_id"].nunique())
print(check.head())

In [ ]:
import os
import time
import pandas as pd
import duckdb

# Final output folder
final_dir = "/kaggle/working/output"
os.makedirs(final_dir, exist_ok=True)

candidate_out = final_dir + "/candidate_pairs.tsv"
matching_out = final_dir + "/matching_results.tsv"

# Remove old partial files if they exist
for f in [candidate_out, matching_out]:
    if os.path.exists(f):
        os.remove(f)

# Count Source1
total_s1 = con.execute(f"""
    SELECT COUNT(*)
    FROM read_csv_auto('{test_s1_path}', delim='\t')
""").fetchone()[0]

batch_size = 20000
total_batches = (total_s1 + batch_size - 1) // batch_size

print("Total Source1:", total_s1)
print("Batch size:", batch_size)
print("Total batches:", total_batches)

# Create headers
pd.DataFrame(columns=[
    "source1_entity_id", "candidate_entity_ids"
]).to_csv(
    candidate_out, sep="\t", index=False
)

pd.DataFrame(columns=[
    "source1_entity_id", "matched_entity_ids"
]).to_csv(
    matching_out, sep="\t", index=False
)

start_time = time.time()

for batch_no in range(total_batches):

    offset = batch_no * batch_size

    query = f"""
    WITH s1 AS (
        SELECT
            entity_id AS source1_entity_id,
            business_name,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{test_s1_path}', delim='\t')
        LIMIT {batch_size} OFFSET {offset}
    ),

    joined AS (
        SELECT
            s1.source1_entity_id,
            s23.candidate_entity_id,
            levenshtein(
                left(s1.clean_name, 30),
                left(s23.clean_name, 30)
            ) AS edit_distance,
            length(s1.clean_name) AS name_len
        FROM s1
        JOIN s23_index s23
          ON s1.country = s23.country
         AND length(s1.clean_name) >= 5
         AND length(s23.clean_name) >= 5
         AND left(s1.clean_name, 5) = left(s23.clean_name, 5)
    ),

    ranked AS (
        SELECT
            *,
            row_number() OVER (
                PARTITION BY source1_entity_id
                ORDER BY edit_distance
            ) AS rn
        FROM joined
    )

    SELECT
        source1_entity_id,
        candidate_entity_id,
        edit_distance,
        name_len
    FROM ranked
    WHERE rn <= 5
    """

    df = con.execute(query).df()

    if len(df) > 0:

        # Candidate file: all top-5 candidates
        candidate_df = (
            df.groupby("source1_entity_id")["candidate_entity_id"]
            .apply(lambda x: ",".join(x.astype(str)))
            .reset_index()
        )

        candidate_df.columns = [
            "source1_entity_id",
            "candidate_entity_ids"
        ]

        candidate_df.to_csv(
            candidate_out,
            sep="\t",
            index=False,
            mode="a",
            header=False
        )

        # Matching:
        # Accept closest candidate when name similarity >= 90%
        df["similarity"] = 1 - (
            df["edit_distance"] /
            df["name_len"].clip(lower=1)
        )

        best = (
            df.sort_values(
                ["source1_entity_id", "edit_distance"]
            )
            .groupby("source1_entity_id")
            .first()
            .reset_index()
        )

        best["matched_entity_ids"] = best.apply(
            lambda r: (
                str(r["candidate_entity_id"])
                if r["similarity"] >= 0.90
                else ""
            ),
            axis=1
        )

        matching_df = best[
            ["source1_entity_id", "matched_entity_ids"]
        ]

        matching_df.to_csv(
            matching_out,
            sep="\t",
            index=False,
            mode="a",
            header=False
        )

    print(
        f"Batch {batch_no+1}/{total_batches} done | "
        f"Rows: {len(df)} | "
        f"Time: {time.time()-start_time:.1f}s"
    )

print("\n✅ FINAL FILES CREATED")
print(candidate_out)
print(matching_out)

print("\nCandidate size:",
      os.path.getsize(candidate_out) / (1024*1024), "MB")

print("Matching size:",
      os.path.getsize(matching_out) / (1024*1024), "MB")

In [ ]:
import time

print("Starting FAST candidate test...")

start = time.time()

fast_test = con.execute(f"""
SELECT
    s1.entity_id AS source1_entity_id,
    s23.candidate_entity_id
FROM (
    SELECT
        entity_id,
        country,
        regexp_replace(
            lower(coalesce(business_name, '')),
            '[^a-zA-Z0-9]', '', 'g'
        ) AS clean_name
    FROM read_csv_auto('{test_s1_path}', delim='\t')
    LIMIT 5000
) s1

JOIN s23_index s23
  ON s1.country = s23.country
 AND length(s1.clean_name) >= 5
 AND length(s23.clean_name) >= 5
 AND left(s1.clean_name, 5) = left(s23.clean_name, 5)

LIMIT 100000
""").df()

print("✅ FAST TEST COMPLETE")
print("Rows:", len(fast_test))
print("Unique Source1:", fast_test["source1_entity_id"].nunique())
print("Time:", round(time.time() - start, 2), "seconds")

print(fast_test.head())

In [ ]:
import os
import time

final_dir = "/kaggle/working/output"
os.makedirs(final_dir, exist_ok=True)

candidate_out = final_dir + "/candidate_pairs.tsv"
matching_out = final_dir + "/matching_results.tsv"

# Remove old partial files
for f in [candidate_out, matching_out]:
    if os.path.exists(f):
        os.remove(f)

start = time.time()

print("Creating final candidate table...")

con.execute("DROP TABLE IF EXISTS final_candidates")

con.execute(f"""
CREATE TEMP TABLE final_candidates AS

WITH s1 AS (
    SELECT
        entity_id AS source1_entity_id,
        country,
        regexp_replace(
            lower(coalesce(business_name, '')),
            '[^a-zA-Z0-9]', '', 'g'
        ) AS clean_name
    FROM read_csv_auto('{test_s1_path}', delim='\t')
),

matched AS (
    SELECT
        s1.source1_entity_id,
        s23.candidate_entity_id,
        row_number() OVER (
            PARTITION BY s1.source1_entity_id
            ORDER BY s23.candidate_entity_id
        ) AS rn
    FROM s1
    JOIN s23_index s23
      ON s1.country = s23.country
     AND length(s1.clean_name) >= 5
     AND length(s23.clean_name) >= 5
     AND left(s1.clean_name, 5) = left(s23.clean_name, 5)
)

SELECT
    source1_entity_id,
    candidate_entity_id
FROM matched
WHERE rn <= 5
""")

print("Candidate table created")
print("Time:", round(time.time() - start, 2), "sec")

# --------------------------------------------------
# candidate_pairs.tsv
# --------------------------------------------------

print("Writing candidate_pairs.tsv...")

con.execute(f"""
COPY (
    SELECT
        s1.entity_id AS source1_entity_id,
        coalesce(
            string_agg(
                fc.candidate_entity_id,
                ',' ORDER BY fc.candidate_entity_id
            ),
            ''
        ) AS candidate_entity_ids
    FROM read_csv_auto('{test_s1_path}', delim='\t') s1
    LEFT JOIN final_candidates fc
      ON s1.entity_id = fc.source1_entity_id
    GROUP BY s1.entity_id
    ORDER BY s1.entity_id
)
TO '{candidate_out}'
(FORMAT CSV, HEADER TRUE, DELIMITER '\t')
""")

# --------------------------------------------------
# matching_results.tsv
# Only exact cleaned-name + country matches
# --------------------------------------------------

print("Writing matching_results.tsv...")

con.execute(f"""
COPY (
    WITH s1 AS (
        SELECT
            entity_id AS source1_entity_id,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{test_s1_path}', delim='\t')
    ),

    exact_matches AS (
        SELECT
            s1.source1_entity_id,
            s23.candidate_entity_id,
            row_number() OVER (
                PARTITION BY s1.source1_entity_id
                ORDER BY s23.candidate_entity_id
            ) AS rn
        FROM s1
        JOIN s23_index s23
          ON s1.country = s23.country
         AND s1.clean_name = s23.clean_name
         AND length(s1.clean_name) >= 5
    )

    SELECT
        s1.entity_id AS source1_entity_id,
        coalesce(
            string_agg(
                em.candidate_entity_id,
                ',' ORDER BY em.candidate_entity_id
            ),
            ''
        ) AS matched_entity_ids
    FROM read_csv_auto('{test_s1_path}', delim='\t') s1
    LEFT JOIN exact_matches em
      ON s1.entity_id = em.source1_entity_id
     AND em.rn <= 5
    GROUP BY s1.entity_id
    ORDER BY s1.entity_id
)
TO '{matching_out}'
(FORMAT CSV, HEADER TRUE, DELIMITER '\t')
""")

print("\n================================")
print("✅ BOTH FILES CREATED")
print("================================")
print("Candidate:", candidate_out)
print("Matching :", matching_out)

print("\nFile sizes:")
print(
    "candidate_pairs.tsv:",
    round(os.path.getsize(candidate_out) / (1024 * 1024), 2),
    "MB"
)
print(
    "matching_results.tsv:",
    round(os.path.getsize(matching_out) / (1024 * 1024), 2),
    "MB"
)

print("\nTotal time:", round(time.time() - start, 2), "sec")

In [ ]:
# Clean old partial final files
import os

final_dir = "/kaggle/working/output"
os.makedirs(final_dir, exist_ok=True)

candidate_out = final_dir + "/candidate_pairs.tsv"
matching_out = final_dir + "/matching_results.tsv"

for f in [candidate_out, matching_out]:
    if os.path.exists(f):
        os.remove(f)

# Safer DuckDB settings
con.execute("SET memory_limit='12GB'")
con.execute("SET threads=2")
con.execute("SET preserve_insertion_order=false")
con.execute("SET max_temp_directory_size='8GB'")

print("✅ Memory settings updated")
print("Output folder:", final_dir)

In [ ]:
import os
import time

candidate_out = "/kaggle/working/output/candidate_pairs.tsv"
matching_out = "/kaggle/working/output/matching_results.tsv"

# Start fresh
for f in [candidate_out, matching_out]:
    if os.path.exists(f):
        os.remove(f)

batch_size = 50000
total_s1 = 1732544
total_batches = (total_s1 + batch_size - 1) // batch_size

print("Total Source1:", total_s1)
print("Batch size:", batch_size)
print("Total batches:", total_batches)

start = time.time()

for b in range(total_batches):

    offset = b * batch_size

    # -----------------------------
    # Candidate pairs
    # -----------------------------
    candidate_query = f"""
    WITH s1 AS (
        SELECT
            entity_id AS source1_entity_id,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{test_s1_path}', delim='\t')
        LIMIT {batch_size} OFFSET {offset}
    ),

    pairs AS (
        SELECT
            s1.source1_entity_id,
            s23.candidate_entity_id
        FROM s1
        JOIN s23_index s23
          ON s1.country = s23.country
         AND length(s1.clean_name) >= 5
         AND length(s23.clean_name) >= 5
         AND left(s1.clean_name, 5) = left(s23.clean_name, 5)
    ),

    grouped AS (
        SELECT
            source1_entity_id,
            list_slice(
                list_sort(list(candidate_entity_id)),
                1,
                5
            ) AS candidates
        FROM pairs
        GROUP BY source1_entity_id
    )

    SELECT
        s1.source1_entity_id,
        coalesce(
            array_to_string(g.candidates, ','),
            ''
        ) AS candidate_entity_ids
    FROM s1
    LEFT JOIN grouped g
      ON s1.source1_entity_id = g.source1_entity_id
    """

    cand_df = con.execute(candidate_query).df()

    cand_df.to_csv(
        candidate_out,
        sep="\t",
        index=False,
        mode="a",
        header=(b == 0)
    )

    # -----------------------------
    # Exact matches
    # -----------------------------
    match_query = f"""
    WITH s1 AS (
        SELECT
            entity_id AS source1_entity_id,
            country,
            regexp_replace(
                lower(coalesce(business_name, '')),
                '[^a-zA-Z0-9]', '', 'g'
            ) AS clean_name
        FROM read_csv_auto('{test_s1_path}', delim='\t')
        LIMIT {batch_size} OFFSET {offset}
    ),

    exact AS (
        SELECT
            s1.source1_entity_id,
            s23.candidate_entity_id
        FROM s1
        JOIN s23_index s23
          ON s1.country = s23.country
         AND length(s1.clean_name) >= 5
         AND s1.clean_name = s23.clean_name
    ),

    grouped AS (
        SELECT
            source1_entity_id,
            list_slice(
                list_sort(list(candidate_entity_id)),
                1,
                5
            ) AS matches
        FROM exact
        GROUP BY source1_entity_id
    )

    SELECT
        s1.source1_entity_id,
        coalesce(
            array_to_string(g.matches, ','),
            ''
        ) AS matched_entity_ids
    FROM s1
    LEFT JOIN grouped g
      ON s1.source1_entity_id = g.source1_entity_id
    """

    match_df = con.execute(match_query).df()

    match_df.to_csv(
        matching_out,
        sep="\t",
        index=False,
        mode="a",
        header=(b == 0)
    )

    elapsed = time.time() - start

    print(
        f"Batch {b+1}/{total_batches} done | "
        f"Candidates: {len(cand_df)} | "
        f"Matches: {len(match_df)} | "
        f"Time: {elapsed/60:.1f} min"
    )

print("\n====================================")
print("✅ FINAL FILES CREATED")
print("====================================")
print(candidate_out)
print(matching_out)

print(
    "Candidate size:",
    round(os.path.getsize(candidate_out)/(1024*1024), 2),
    "MB"
)

print(
    "Matching size:",
    round(os.path.getsize(matching_out)/(1024*1024), 2),
    "MB"
)

In [ ]:
import pandas as pd
import os
import time

out = "/kaggle/working/output"
os.makedirs(out, exist_ok=True)

matching_file = out + "/matching_results.tsv"
candidate_file = out + "/candidate_pairs.tsv"

# Remove old partial files
for f in [matching_file, candidate_file]:
    if os.path.exists(f):
        os.remove(f)

print("Loading test data...")

s1 = pd.read_csv(test_s1_path, sep="\t", usecols=[
    "entity_id", "business_name", "country"
])

s2 = pd.read_csv(test_s2_path, sep="\t", usecols=[
    "entity_id", "business_name", "country"
])

s3 = pd.read_csv(test_s3_path, sep="\t", usecols=[
    "entity_id", "business_name", "country"
])

print("Loaded.")

# Normalize names
def norm(x):
    return (
        x.fillna("")
         .astype(str)
         .str.lower()
         .str.replace(r"[^a-zA-Z0-9]", "", regex=True)
    )

s1["key"] = norm(s1["business_name"]) + "|" + s1["country"].fillna("")
s2["key"] = norm(s2["business_name"]) + "|" + s2["country"].fillna("")
s3["key"] = norm(s3["business_name"]) + "|" + s3["country"].fillna("")

# Combine S2 + S3
lookup = pd.concat([
    s2[["key", "entity_id"]],
    s3[["key", "entity_id"]]
], ignore_index=True)

print("Building lookup...")

# Keep first few IDs for each exact key
lookup = lookup.groupby("key")["entity_id"].agg(
    lambda x: ",".join(x.astype(str).head(5))
).to_dict()

print("Creating results...")

s1["matched_entity_ids"] = s1["key"].map(lookup).fillna("")

# Candidate list = same candidates
s1["candidate_entity_ids"] = s1["matched_entity_ids"]

matching = s1[[
    "entity_id",
    "matched_entity_ids"
]].rename(columns={
    "entity_id": "source1_entity_id"
})

candidate = s1[[
    "entity_id",
    "candidate_entity_ids"
]].rename(columns={
    "entity_id": "source1_entity_id"
})

matching.to_csv(matching_file, sep="\t", index=False)
candidate.to_csv(candidate_file, sep="\t", index=False)

print("\n================================")
print("✅ DONE")
print("================================")

print("Matching rows:", len(matching))
print("Candidate rows:", len(candidate))

print("Matching file:", matching_file)
print("Candidate file:", candidate_file)

print(
    "Matched Source1:",
    (matching["matched_entity_ids"] != "").sum()
)

print(
    "Matching size:",
    round(os.path.getsize(matching_file)/(1024*1024), 2),
    "MB"
)

print(
    "Candidate size:",
    round(os.path.getsize(candidate_file)/(1024*1024), 2),
    "MB"
)

In [ ]:
print("⚡ FAST LOOKUP START")

lookup = pd.concat(
    [s2[["key", "entity_id"]], s3[["key", "entity_id"]]],
    ignore_index=True
)

print("Combined:", len(lookup))

# Keep only first exact match for each key
lookup = lookup.drop_duplicates("key")

print("Unique keys:", len(lookup))

# Fast Series mapping
lookup = lookup.set_index("key")["entity_id"]

print("Mapping...")

s1["matched_entity_ids"] = s1["key"].map(lookup).fillna("")
s1["candidate_entity_ids"] = s1["matched_entity_ids"]

matching = s1[["entity_id", "matched_entity_ids"]].rename(
    columns={"entity_id": "source1_entity_id"}
)

candidate = s1[["entity_id", "candidate_entity_ids"]].rename(
    columns={"entity_id": "source1_entity_id"}
)

matching.to_csv(matching_file, sep="\t", index=False)
candidate.to_csv(candidate_file, sep="\t", index=False)

print("\n==============================")
print("✅ DONE")
print("==============================")
print("Matching rows:", len(matching))
print("Candidate rows:", len(candidate))
print("Matched:", (matching["matched_entity_ids"] != "").sum())
print("Matching file:", matching_file)
print("Candidate file:", candidate_file)

In [ ]:
import pandas as pd
import os

matching = pd.read_csv(
    "/kaggle/working/output/matching_results.tsv",
    sep="\t"
)

candidate = pd.read_csv(
    "/kaggle/working/output/candidate_pairs.tsv",
    sep="\t"
)

print("Matching shape:", matching.shape)
print("Candidate shape:", candidate.shape)

print("\nColumns:")
print(matching.columns.tolist())
print(candidate.columns.tolist())

print("\nEmpty matches:",
      (matching["matched_entity_ids"].fillna("") == "").sum())

print("\nFiles:")
print("matching_results.tsv:",
      round(os.path.getsize("/kaggle/working/output/matching_results.tsv") / 1024**2, 2), "MB")

print("candidate_pairs.tsv:",
      round(os.path.getsize("/kaggle/working/output/candidate_pairs.tsv") / 1024**2, 2), "MB")

In [ ]:
import subprocess
import os

matching_file = "/kaggle/working/output/matching_results.tsv"
candidate_file = "/kaggle/working/output/candidate_pairs.tsv"

# Find official validator
validator = None

for root, dirs, files in os.walk("/kaggle/input"):
    if "validate_submission.py" in files:
        validator = os.path.join(root, "validate_submission.py")
        break

print("Validator:", validator)

if validator:
    result = subprocess.run(
        [
            "python",
            validator,
            "--matching", matching_file,
            "--candidate", candidate_file,
            "--test-dir", "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test"
        ],
        capture_output=True,
        text=True
    )

    print(result.stdout)
    print(result.stderr)
else:
    print("Official validator not found.")

In [ ]:
import pandas as pd
import os

m_path = "/kaggle/working/output/matching_results.tsv"
c_path = "/kaggle/working/output/candidate_pairs.tsv"

m = pd.read_csv(m_path, sep="\t", dtype=str).fillna("")
c = pd.read_csv(c_path, sep="\t", dtype=str).fillna("")

print("========== FINAL CHECK ==========")

# 1. Row count
print("Matching rows :", len(m))
print("Candidate rows:", len(c))

# 2. Columns
print("Matching columns :", list(m.columns))
print("Candidate columns:", list(c.columns))

# 3. Unique Source1 IDs
print("Matching duplicate IDs :", m["source1_entity_id"].duplicated().sum())
print("Candidate duplicate IDs:", c["source1_entity_id"].duplicated().sum())

# 4. Same Source1 IDs
same_ids = (
    m["source1_entity_id"].values == c["source1_entity_id"].values
).all()

print("Same Source1 order:", same_ids)

# 5. Every match should be inside candidate list
candidate_map = dict(
    zip(c["source1_entity_id"], c["candidate_entity_ids"])
)

bad = 0

for sid, matches in zip(
    m["source1_entity_id"],
    m["matched_entity_ids"]
):
    if matches:
        match_ids = set(matches.split(","))
        candidate_ids = set(candidate_map.get(sid, "").split(","))

        if not match_ids.issubset(candidate_ids):
            bad += 1

print("Matches outside candidates:", bad)

# 6. File sizes
print("matching_results.tsv:",
      round(os.path.getsize(m_path)/1024/1024, 2), "MB")

print("candidate_pairs.tsv:",
      round(os.path.getsize(c_path)/1024/1024, 2), "MB")

print("\n========== RESULT ==========")

if (
    len(m) == 1732544
    and len(c) == 1732544
    and m["source1_entity_id"].duplicated().sum() == 0
    and c["source1_entity_id"].duplicated().sum() == 0
    and same_ids
    and bad == 0
):
    print("✅ SUBMISSION FORMAT LOOKS GOOD")
else:
    print("⚠️ CHECK FAILED")

In [ ]:
print("Model exists:",
      os.path.exists("/kaggle/working/student_matching_model_package.pkl"))

print("S1 rows:", len(s1))
print("S2 rows:", len(s2))
print("S3 rows:", len(s3))

print("DuckDB connection:", con is not None)

In [ ]:
import joblib

pkg = joblib.load("/kaggle/working/student_matching_model_package.pkl")

print("Package type:", type(pkg))

if isinstance(pkg, dict):
    print("Keys:", pkg.keys())
    for k, v in pkg.items():
        print(k, "->", type(v))
else:
    print(pkg)

In [ ]:
model = pkg["model"]
features = pkg["features"]

print("Model:", type(model).__name__)
print("Features:")
for i, f in enumerate(features, 1):
    print(i, f)

In [ ]:
import time

print("Testing better candidate blocking...")

test_n = 10000

con.execute("DROP TABLE IF EXISTS s1_test")

con.execute(f"""
CREATE TABLE s1_test AS
SELECT
    entity_id AS source1_entity_id,
    country,
    regexp_replace(
        lower(coalesce(business_name, '')),
        '[^a-zA-Z0-9]', '', 'g'
    ) AS clean_name
FROM read_csv_auto('{test_s1_path}', delim='\t')
LIMIT {test_n}
""")

start = time.time()

result = con.execute("""
SELECT
    s.source1_entity_id,
    c.candidate_entity_id
FROM s1_test s
JOIN s23_index c
  ON s.country = c.country
 AND left(s.clean_name, 4) = left(c.clean_name, 4)
WHERE length(s.clean_name) >= 4
  AND length(c.clean_name) >= 4
""").fetchdf()

print("Rows generated:", len(result))
print("Unique Source1:", result["source1_entity_id"].nunique())
print("Average candidates per Source1:",
      round(len(result) / result["source1_entity_id"].nunique(), 2))

print("Time:", round(time.time() - start, 2), "seconds")

In [ ]:
import time

print("Testing 5-character blocking...")

start = time.time()

result5 = con.execute("""
SELECT
    s.source1_entity_id,
    c.candidate_entity_id
FROM s1_test s
JOIN s23_index c
  ON s.country = c.country
 AND left(s.clean_name, 5) = left(c.clean_name, 5)
WHERE length(s.clean_name) >= 5
  AND length(c.clean_name) >= 5
""").fetchdf()

print("Rows generated:", len(result5))
print("Unique Source1:", result5["source1_entity_id"].nunique())
print(
    "Average candidates per Source1:",
    round(
        len(result5) / result5["source1_entity_id"].nunique(),
        2
    )
)
print("Time:", round(time.time() - start, 2), "seconds")

In [ ]:
import pandas as pd
import duckdb
import joblib
import os
import time

# Paths
test_s1_path = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source1.tsv"
test_s2_path = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source2.tsv"
test_s3_path = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test/test_source3.tsv"

# Load model
pkg = joblib.load("/kaggle/working/student_matching_model_package.pkl")
model = pkg["model"]
features = pkg["features"]

print("Model loaded")
print("Features:", features)

# DuckDB
con = duckdb.connect()
con.execute("SET memory_limit='10GB'")
con.execute("SET threads=2")
con.execute("SET preserve_insertion_order=false")
con.execute("SET max_temp_directory_size='6GB'")

print("DuckDB ready")

In [ ]:
print("Creating S2 + S3 index...")

con.execute("DROP TABLE IF EXISTS s23_index")

con.execute(f"""
CREATE TABLE s23_index AS

SELECT
    entity_id AS candidate_entity_id,
    country,
    business_name,
    address,
    regexp_replace(
        lower(coalesce(business_name, '')),
        '[^a-zA-Z0-9]', '', 'g'
    ) AS clean_name

FROM read_csv_auto(
    '{test_s2_path}',
    delim='\t'
)

UNION ALL

SELECT
    entity_id AS candidate_entity_id,
    country,
    business_name,
    address,
    regexp_replace(
        lower(coalesce(business_name, '')),
        '[^a-zA-Z0-9]', '', 'g'
    ) AS clean_name

FROM read_csv_auto(
    '{test_s3_path}',
    delim='\t'
)
""")

print("Index created")

print(
    con.execute(
        "SELECT COUNT(*) FROM s23_index"
    ).fetchone()[0]
)

In [ ]:
print("Creating S2 + S3 index...")

con.execute("DROP TABLE IF EXISTS s23_index")

con.execute(f"""
CREATE TABLE s23_index AS

SELECT
    entity_id AS candidate_entity_id,
    country,
    business_name,
    address,
    regexp_replace(
        lower(coalesce(business_name, '')),
        '[^a-zA-Z0-9]', '', 'g'
    ) AS clean_name

FROM read_csv_auto(
    '{test_s2_path}',
    delim='\t'
)

UNION ALL

SELECT
    entity_id AS candidate_entity_id,
    country,
    business_name,
    address,
    regexp_replace(
        lower(coalesce(business_name, '')),
        '[^a-zA-Z0-9]', '', 'g'
    ) AS clean_name

FROM read_csv_auto(
    '{test_s3_path}',
    delim='\t'
)
""")

print("Index created")

print(
    con.execute(
        "SELECT COUNT(*) FROM s23_index"
    ).fetchone()[0]
)

In [ ]:
print("TEST SOURCE 2 COLUMNS:")

cols = con.execute(f"""
    DESCRIBE
    SELECT *
    FROM read_csv_auto(
        '{test_s2_path}',
        delim='\t'
    )
""").fetchdf()

print(cols[["column_name", "column_type"]].to_string(index=False))

In [ ]:
print("Creating S2 + S3 index...")

con.execute("DROP TABLE IF EXISTS s23_index")

con.execute(f"""
CREATE TABLE s23_index AS

SELECT
    entity_id AS candidate_entity_id,
    business_name,
    business_address,
    country,
    regexp_replace(
        lower(coalesce(business_name, '')),
        '[^a-zA-Z0-9]', '', 'g'
    ) AS clean_name

FROM read_csv_auto(
    '{test_s2_path}',
    delim='\t'
)

UNION ALL

SELECT
    entity_id AS candidate_entity_id,
    business_name,
    business_address,
    country,
    regexp_replace(
        lower(coalesce(business_name, '')),
        '[^a-zA-Z0-9]', '', 'g'
    ) AS clean_name

FROM read_csv_auto(
    '{test_s3_path}',
    delim='\t'
)
""")

count = con.execute(
    "SELECT COUNT(*) FROM s23_index"
).fetchone()[0]

print("✅ Index created")
print("Total candidates:", count)

In [ ]:
print("Testing 5-character blocking safely...")

con.execute("DROP TABLE IF EXISTS s1_test")

con.execute(f"""
CREATE TEMP TABLE s1_test AS
SELECT
    entity_id AS source1_entity_id,
    business_name,
    business_address,
    country,
    regexp_replace(
        lower(coalesce(business_name, '')),
        '[^a-zA-Z0-9]', '', 'g'
    ) AS clean_name
FROM read_csv_auto(
    '{test_s1_path}',
    delim='\t'
)
LIMIT 10000
""")

result = con.execute("""
SELECT COUNT(*)
FROM s1_test s
JOIN s23_index c
  ON s.country = c.country
 AND left(s.clean_name, 5) = left(c.clean_name, 5)
WHERE length(s.clean_name) >= 5
  AND length(c.clean_name) >= 5
""").fetchone()[0]

print("Candidate pairs for 10,000 Source1:", result)
print("Average per Source1:", round(result / 10000, 2))

In [ ]:
print("Testing 6-character blocking safely...")

result6 = con.execute("""
SELECT COUNT(*)
FROM s1_test s
JOIN s23_index c
  ON s.country = c.country
 AND left(s.clean_name, 6) = left(c.clean_name, 6)
WHERE length(s.clean_name) >= 6
  AND length(c.clean_name) >= 6
""").fetchone()[0]

print("Candidate pairs for 10,000 Source1:", result6)
print("Average per Source1:", round(result6 / 10000, 2))

In [ ]:
print("Testing 7-character blocking safely...")

result7 = con.execute("""
SELECT COUNT(*)
FROM s1_test s
JOIN s23_index c
  ON s.country = c.country
 AND left(s.clean_name, 7) = left(c.clean_name, 7)
WHERE length(s.clean_name) >= 7
  AND length(c.clean_name) >= 7
""").fetchone()[0]

print("Candidate pairs for 10,000 Source1:", result7)
print("Average per Source1:", round(result7 / 10000, 2))

In [ ]:
print("Testing 8-character blocking safely...")

result8 = con.execute("""
SELECT COUNT(*)
FROM s1_test s
JOIN s23_index c
  ON s.country = c.country
 AND left(s.clean_name, 8) = left(c.clean_name, 8)
WHERE length(s.clean_name) >= 8
  AND length(c.clean_name) >= 8
""").fetchone()[0]

print("Candidate pairs for 10,000 Source1:", result8)
print("Average per Source1:", round(result8 / 10000, 2))

In [ ]:
print("Testing selective blocking...")

result_sel = con.execute("""
SELECT COUNT(*)
FROM s1_test s
JOIN s23_index c
  ON s.country = c.country
 AND left(s.clean_name, 3) = left(c.clean_name, 3)
 AND right(s.clean_name, 2) = right(c.clean_name, 2)
 AND abs(length(s.clean_name) - length(c.clean_name)) <= 3
WHERE length(s.clean_name) >= 3
  AND length(c.clean_name) >= 3
""").fetchone()[0]

print("Candidate pairs for 10,000 Source1:", result_sel)
print("Average per Source1:", round(result_sel / 10000, 2))

In [ ]:
print("Testing 3-part signature blocking...")

result_sig = con.execute("""
SELECT COUNT(*)
FROM s1_test s
JOIN s23_index c
  ON s.country = c.country
 AND left(s.clean_name, 3) = left(c.clean_name, 3)
 AND right(s.clean_name, 3) = right(c.clean_name, 3)
 AND abs(length(s.clean_name) - length(c.clean_name)) <= 2
WHERE length(s.clean_name) >= 6
  AND length(c.clean_name) >= 6
""").fetchone()[0]

print("Candidate pairs for 10,000 Source1:", result_sig)
print("Average per Source1:", round(result_sig / 10000, 2))

In [ ]:
print("Testing Top-20 candidate selection...")

result_top20 = con.execute("""
WITH candidates AS (
    SELECT
        s.source1_entity_id,
        c.candidate_entity_id,
        abs(length(s.clean_name) - length(c.clean_name)) AS len_diff
    FROM s1_test s
    JOIN s23_index c
      ON s.country = c.country
     AND left(s.clean_name, 3) = left(c.clean_name, 3)
     AND right(s.clean_name, 3) = right(c.clean_name, 3)
     AND abs(length(s.clean_name) - length(c.clean_name)) <= 2
    WHERE length(s.clean_name) >= 6
      AND length(c.clean_name) >= 6
),
ranked AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY source1_entity_id
               ORDER BY len_diff, candidate_entity_id
           ) AS rn
    FROM candidates
)
SELECT COUNT(*)
FROM ranked
WHERE rn <= 20
""").fetchone()[0]

print("Top-20 candidate pairs:", result_top20)
print("Average retained per Source1:",
      round(result_top20 / 10000, 2))

In [ ]:
print("Preparing Attempt 2 test batch...")

# Source1 test data
con.execute("DROP TABLE IF EXISTS s1_full")

con.execute(f"""
CREATE TABLE s1_full AS
SELECT
    entity_id AS source1_entity_id,
    business_name,
    business_address,
    country,
    regexp_replace(
        lower(coalesce(business_name, '')),
        '[^a-zA-Z0-9]', '', 'g'
    ) AS clean_name
FROM read_csv_auto(
    '{test_s1_path}',
    delim='\t'
)
""")

# Keep only entities that did NOT get an exact name+country match
con.execute("DROP TABLE IF EXISTS unmatched_test")

con.execute("""
CREATE TEMP TABLE unmatched_test AS
WITH exact AS (
    SELECT DISTINCT
        s.source1_entity_id
    FROM s1_full s
    JOIN s23_index c
      ON s.country = c.country
     AND s.clean_name = c.clean_name
    WHERE s.clean_name <> ''
)
SELECT s.*
FROM s1_full s
WHERE s.source1_entity_id NOT IN (
    SELECT source1_entity_id FROM exact
)
LIMIT 10000
""")

n = con.execute(
    "SELECT COUNT(*) FROM unmatched_test"
).fetchone()[0]

print("Unmatched test entities:", n)

# Generate and retain max 20 candidates
candidate_count = con.execute("""
WITH candidates AS (
    SELECT
        s.source1_entity_id,
        c.candidate_entity_id,
        abs(length(s.clean_name) - length(c.clean_name)) AS len_diff
    FROM unmatched_test s
    JOIN s23_index c
      ON s.country = c.country
     AND left(s.clean_name, 3) = left(c.clean_name, 3)
     AND right(s.clean_name, 3) = right(c.clean_name, 3)
     AND abs(length(s.clean_name) - length(c.clean_name)) <= 2
    WHERE length(s.clean_name) >= 6
      AND length(c.clean_name) >= 6
),
ranked AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY source1_entity_id
               ORDER BY len_diff, candidate_entity_id
           ) AS rn
    FROM candidates
)
SELECT COUNT(*)
FROM ranked
WHERE rn <= 20
""").fetchone()[0]

print("Candidates retained:", candidate_count)
print("Average:", round(candidate_count / max(n, 1), 2))

print("✅ Attempt 2 candidate test ready")

In [ ]:
print("Model features:")
print(model.feature_names_in_)

print("\nFeature importance:")
for name, importance in zip(model.feature_names_in_, model.feature_importances_):
    print(f"{name:30s} {importance:.4f}")

In [ ]:
features_path = "/kaggle/input/datasets/growwithme02/amazonbusiness3-0/training_features.tsv"

sample_features = pd.read_csv(
    features_path,
    sep="\t",
    usecols=[
        "name_similarity",
        "address_similarity",
        "name_token_similarity",
        "address_token_similarity",
        "number_overlap",
        "country_match",
        "source1_address_missing",
        "candidate_address_missing",
        "label"
    ],
    nrows=20
)

print(sample_features.to_string(index=False))

print("\n=== FEATURE RANGES ===")
print(sample_features.describe().T)

In [ ]:
import os

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        if "training_features" in file.lower():
            print(os.path.join(root, file))

In [ ]:
print("Available datasets:")
for x in os.listdir("/kaggle/input/datasets"):
    print(x)

In [ ]:
import os

base = "/kaggle/input/datasets/harshnagayach1908"

for root, dirs, files in os.walk(base):
    for file in files:
        print(os.path.join(root, file))

In [ ]:
import json

notebook_path = "/kaggle/input/datasets/harshnagayach1908/business-entity-resolution-final/notebookda02e89746.ipynb"

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

for i, cell in enumerate(nb["cells"]):
    code = "".join(cell.get("source", []))
    
    if any(x in code.lower() for x in [
        "name_similarity",
        "address_similarity",
        "token_similarity",
        "number_overlap"
    ]):
        print("\n" + "="*70)
        print("CELL", i+1)
        print("="*70)
        print(code)

In [ ]:
keywords = [
    "fuzz",
    "levenshtein",
    "jaccard",
    "SequenceMatcher",
    "cosine",
    "similarity",
    "token",
    "number_overlap",
    "clean_name",
    "clean_address"
]

for i, cell in enumerate(nb["cells"]):
    code = "".join(cell.get("source", []))
    code_lower = code.lower()

    if any(k.lower() in code_lower for k in keywords):
        print("\n" + "="*80)
        print("CELL", i+1)
        print("="*80)
        print(code)

In [ ]:
import rapidfuzz

print("RapidFuzz version:", rapidfuzz.__version__)

In [ ]:
import pandas as pd
import numpy as np
from difflib import SequenceMatcher
import re

def similarity(a, b):
    a = "" if pd.isna(a) else str(a)
    b = "" if pd.isna(b) else str(b)
    return SequenceMatcher(None, a, b).ratio()

def token_similarity(a, b):
    a = "" if pd.isna(a) else str(a)
    b = "" if pd.isna(b) else str(b)

    ta = set(a.lower().split())
    tb = set(b.lower().split())

    if not ta or not tb:
        return 0.0

    return len(ta & tb) / len(ta | tb)

def number_overlap(a, b):
    a = "" if pd.isna(a) else str(a)
    b = "" if pd.isna(b) else str(b)

    na = set(re.findall(r'\d+', a))
    nb = set(re.findall(r'\d+', b))

    if not na or not nb:
        return 0.0

    return len(na & nb) / len(na | nb)

print("Functions ready")

In [ ]:
candidate_df = con.execute("""
WITH candidates AS (
    SELECT
        s.source1_entity_id,
        s.business_name AS source1_name,
        s.business_address AS source1_address,
        s.country AS source1_country,

        c.candidate_entity_id,
        c.business_name AS candidate_name,
        c.business_address AS candidate_address,
        c.country AS candidate_country,

        abs(length(s.clean_name) - length(c.clean_name)) AS len_diff

    FROM unmatched_test s
    JOIN s23_index c
      ON s.country = c.country
     AND left(s.clean_name, 3) = left(c.clean_name, 3)
     AND right(s.clean_name, 3) = right(c.clean_name, 3)
     AND abs(length(s.clean_name) - length(c.clean_name)) <= 2

    WHERE length(s.clean_name) >= 6
      AND length(c.clean_name) >= 6
),
ranked AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY source1_entity_id
               ORDER BY len_diff, candidate_entity_id
           ) AS rn
    FROM candidates
)
SELECT *
FROM ranked
WHERE rn <= 20
""").fetchdf()

print("Candidates:", len(candidate_df))
print(candidate_df.head())

In [ ]:
print("Calculating features...")

candidate_df["name_similarity"] = [
    similarity(a, b)
    for a, b in zip(
        candidate_df["source1_name"],
        candidate_df["candidate_name"]
    )
]

candidate_df["address_similarity"] = [
    similarity(a, b)
    for a, b in zip(
        candidate_df["source1_address"],
        candidate_df["candidate_address"]
    )
]

candidate_df["name_token_similarity"] = [
    token_similarity(a, b)
    for a, b in zip(
        candidate_df["source1_name"],
        candidate_df["candidate_name"]
    )
]

candidate_df["address_token_similarity"] = [
    token_similarity(a, b)
    for a, b in zip(
        candidate_df["source1_address"],
        candidate_df["candidate_address"]
    )
]

candidate_df["number_overlap"] = [
    number_overlap(a, b)
    for a, b in zip(
        candidate_df["source1_address"],
        candidate_df["candidate_address"]
    )
]

candidate_df["country_match"] = (
    candidate_df["source1_country"] ==
    candidate_df["candidate_country"]
).astype(int)

candidate_df["source1_address_missing"] = (
    candidate_df["source1_address"].fillna("").str.strip() == ""
).astype(int)

candidate_df["candidate_address_missing"] = (
    candidate_df["candidate_address"].fillna("").str.strip() == ""
).astype(int)

print("Features calculated!")

print(
    candidate_df[
        [
            "name_similarity",
            "address_similarity",
            "name_token_similarity",
            "address_token_similarity",
            "number_overlap",
            "country_match",
            "source1_address_missing",
            "candidate_address_missing"
        ]
    ].describe()
)

In [ ]:
model_features = [
    "name_similarity",
    "address_similarity",
    "name_token_similarity",
    "address_token_similarity",
    "number_overlap",
    "country_match",
    "source1_address_missing",
    "candidate_address_missing"
]

X_candidates = candidate_df[model_features]

candidate_df["match_probability"] = model.predict_proba(
    X_candidates
)[:, 1]

print("Probability calculated!")

print(
    candidate_df["match_probability"].describe()
)

In [ ]:
print(
    candidate_df[
        [
            "source1_entity_id",
            "source1_name",
            "candidate_entity_id",
            "candidate_name",
            "name_similarity",
            "address_similarity",
            "name_token_similarity",
            "address_token_similarity",
            "number_overlap",
            "match_probability"
        ]
    ]
    .sort_values("match_probability", ascending=False)
    .head(20)
    .to_string(index=False)
)

In [ ]:
strong = candidate_df[
    (candidate_df["match_probability"] >= 0.90) &
    (
        (candidate_df["name_similarity"] >= 0.85) |
        (candidate_df["name_token_similarity"] >= 0.50)
    ) &
    (
        (candidate_df["address_similarity"] >= 0.45) |
        (candidate_df["address_token_similarity"] >= 0.40) |
        (candidate_df["number_overlap"] >= 0.50)
    )
]

print("Strong candidates:", len(strong))
print("Source1 covered:", strong["source1_entity_id"].nunique())

In [ ]:
multi = (
    strong.groupby("source1_entity_id")
    .size()
    .value_counts()
    .sort_index()
)

print(multi)

In [ ]:
strong = strong.copy()

strong["final_score"] = (
    0.30 * strong["name_similarity"] +
    0.25 * strong["address_similarity"] +
    0.20 * strong["name_token_similarity"] +
    0.20 * strong["address_token_similarity"] +
    0.05 * strong["number_overlap"]
)

best = (
    strong
    .sort_values(
        ["source1_entity_id", "final_score"],
        ascending=[True, False]
    )
    .drop_duplicates("source1_entity_id")
)

print("Best matches:", len(best))

print(
    best[
        [
            "source1_entity_id",
            "source1_name",
            "candidate_entity_id",
            "candidate_name",
            "name_similarity",
            "address_similarity",
            "name_token_similarity",
            "address_token_similarity",
            "number_overlap",
            "match_probability",
            "final_score"
        ]
    ]
    .head(30)
    .to_string(index=False)
)

In [ ]:
ranked = (
    strong
    .sort_values(
        ["source1_entity_id", "final_score"],
        ascending=[True, False]
    )
    .groupby("source1_entity_id")
    .head(2)
)

margin = (
    ranked
    .groupby("source1_entity_id")["final_score"]
    .agg(["max", "min"])
)

margin["difference"] = margin["max"] - margin["min"]

print("Margin statistics:")
print(margin["difference"].describe())

print("\nSmallest margins:")
print(
    margin
    .sort_values("difference")
    .head(30)
)

In [ ]:
high = candidate_df[
    (candidate_df["match_probability"] >= 0.95) &
    (candidate_df["name_similarity"] >= 0.85) &
    (
        (candidate_df["address_similarity"] >= 0.45) |
        (candidate_df["address_token_similarity"] >= 0.40) |
        (candidate_df["number_overlap"] >= 0.50)
    )
]

medium = candidate_df[
    (candidate_df["match_probability"] >= 0.95) &
    (candidate_df["name_similarity"] >= 0.75) &
    (
        (candidate_df["address_similarity"] >= 0.60) |
        (candidate_df["address_token_similarity"] >= 0.60) |
        (candidate_df["number_overlap"] >= 0.50)
    )
]

print("HIGH candidates :", len(high))
print("HIGH Source1    :", high["source1_entity_id"].nunique())

print("MEDIUM candidates:", len(medium))
print("MEDIUM Source1   :", medium["source1_entity_id"].nunique())

In [ ]:
high = candidate_df[
    (candidate_df["match_probability"] >= 0.95) &
    (candidate_df["name_similarity"] >= 0.85) &
    (
        (candidate_df["address_similarity"] >= 0.45) |
        (candidate_df["address_token_similarity"] >= 0.40) |
        (candidate_df["number_overlap"] >= 0.50)
    )
].copy()

best_high = (
    high
    .sort_values(
        [
            "source1_entity_id",
            "match_probability",
            "name_similarity",
            "address_similarity",
            "address_token_similarity"
        ],
        ascending=[True, False, False, False, False]
    )
    .drop_duplicates("source1_entity_id")
)

print("Final HIGH matches:", len(best_high))
print("Unique Source1:", best_high["source1_entity_id"].nunique())

In [ ]:
print(
    best_high[
        [
            "source1_entity_id",
            "source1_name",
            "candidate_entity_id",
            "candidate_name",
            "name_similarity",
            "address_similarity",
            "address_token_similarity",
            "number_overlap",
            "match_probability"
        ]
    ]
    .head(30)
    .to_string(index=False)
)

In [ ]:
print(
    best_high[
        best_high["name_similarity"] < 0.90
    ][
        [
            "source1_entity_id",
            "source1_name",
            "candidate_entity_id",
            "candidate_name",
            "name_similarity",
            "address_similarity",
            "address_token_similarity",
            "number_overlap",
            "match_probability"
        ]
    ]
    .sort_values("name_similarity")
    .head(30)
    .to_string(index=False)
)

In [ ]:
rule1 = candidate_df[
    (candidate_df["match_probability"] >= 0.95) &
    (candidate_df["name_similarity"] >= 0.90) &
    (
        (candidate_df["address_similarity"] >= 0.25) |
        (candidate_df["address_token_similarity"] >= 0.40) |
        (candidate_df["number_overlap"] >= 0.50)
    )
].copy()

rule2 = candidate_df[
    (candidate_df["match_probability"] >= 0.95) &
    (candidate_df["name_similarity"] >= 0.85) &
    (candidate_df["name_similarity"] < 0.90) &
    (
        (candidate_df["address_similarity"] >= 0.50) |
        (candidate_df["address_token_similarity"] >= 0.60) |
        (candidate_df["number_overlap"] >= 0.50)
    )
].copy()

final_candidates = pd.concat([rule1, rule2], ignore_index=True)

best_final = (
    final_candidates
    .sort_values(
        [
            "source1_entity_id",
            "match_probability",
            "name_similarity",
            "address_similarity"
        ],
        ascending=[True, False, False, False]
    )
    .drop_duplicates("source1_entity_id")
)

print("Rule 1:", rule1["source1_entity_id"].nunique())
print("Rule 2:", rule2["source1_entity_id"].nunique())
print("Final unique matches:", best_final["source1_entity_id"].nunique())

In [ ]:
print(
    best_final[
        best_final["name_similarity"] < 0.90
    ][
        [
            "source1_entity_id",
            "source1_name",
            "candidate_entity_id",
            "candidate_name",
            "name_similarity",
            "address_similarity",
            "address_token_similarity",
            "number_overlap",
            "match_probability"
        ]
    ]
    .sort_values("name_similarity")
    .head(30)
    .to_string(index=False)
)

In [ ]:
check = best_final[
    best_final["name_similarity"] < 0.90
][[
    "source1_entity_id",
    "source1_name",
    "candidate_entity_id",
    "candidate_name",
    "name_similarity",
    "address_similarity",
    "address_token_similarity",
    "number_overlap",
    "match_probability"
]].sort_values(
    ["name_similarity", "address_similarity"]
)

print("Low-name-similarity matches:", len(check))
print(check.head(50).to_string(index=False))

In [ ]:
# Suspicious low-name matches
suspicious = best_final[
    (best_final["name_similarity"] < 0.90) &
    (
        best_final["source1_name"].str.lower().str.contains("private|public", na=False) |
        best_final["candidate_name"].str.lower().str.contains("private|public", na=False)
    )
]

print("Private/Public suspicious:", len(suspicious))

print(
    suspicious[
        [
            "source1_entity_id",
            "source1_name",
            "candidate_entity_id",
            "candidate_name",
            "name_similarity",
            "address_similarity",
            "address_token_similarity",
            "number_overlap",
            "match_probability"
        ]
    ].to_string(index=False)
)

In [ ]:
best_final["combined_score"] = (
    0.40 * best_final["name_similarity"] +
    0.30 * best_final["address_similarity"] +
    0.20 * best_final["address_token_similarity"] +
    0.10 * best_final["number_overlap"]
)

print(
    best_final[
        [
            "source1_entity_id",
            "source1_name",
            "candidate_entity_id",
            "candidate_name",
            "name_similarity",
            "address_similarity",
            "address_token_similarity",
            "number_overlap",
            "match_probability",
            "combined_score"
        ]
    ]
    .sort_values("combined_score")
    .head(50)
    .to_string(index=False)
)

In [ ]:
test_rule = candidate_df[
    (candidate_df["match_probability"] >= 0.95) &
    (
        # Very strong name match
        (
            (candidate_df["name_similarity"] >= 0.95) &
            (
                (candidate_df["address_similarity"] >= 0.15) |
                (candidate_df["address_token_similarity"] >= 0.30) |
                (candidate_df["number_overlap"] >= 0.50)
            )
        )
        |
        # Good name match + stronger address evidence
        (
            (candidate_df["name_similarity"] >= 0.90) &
            (
                (candidate_df["address_similarity"] >= 0.40) |
                (candidate_df["address_token_similarity"] >= 0.50) |
                (candidate_df["number_overlap"] >= 0.50)
            )
        )
        |
        # 0.85-0.90 name range: require very strong supporting evidence
        (
            (candidate_df["name_similarity"] >= 0.85) &
            (candidate_df["name_similarity"] < 0.90) &
            (
                (candidate_df["address_similarity"] >= 0.70) |
                (candidate_df["address_token_similarity"] >= 0.75) |
                (candidate_df["number_overlap"] >= 0.75)
            )
        )
    )
].copy()

best_test = (
    test_rule
    .sort_values(
        [
            "source1_entity_id",
            "match_probability",
            "name_similarity",
            "address_similarity",
            "address_token_similarity"
        ],
        ascending=[True, False, False, False, False]
    )
    .drop_duplicates("source1_entity_id")
)

print("Candidates:", len(test_rule))
print("Unique Source1:", best_test["source1_entity_id"].nunique())

In [ ]:
# Check how many candidates each Source1 has
counts = (
    test_rule
    .groupby("source1_entity_id")
    .size()
    .value_counts()
    .sort_index()
)

print(counts)

print("\nSources with multiple candidates:")
print((test_rule.groupby("source1_entity_id").size() > 1).sum())

In [ ]:
# Calculate combined score
test_rule = test_rule.copy()

test_rule["combined_score"] = (
    0.40 * test_rule["name_similarity"] +
    0.30 * test_rule["address_similarity"] +
    0.20 * test_rule["address_token_similarity"] +
    0.10 * test_rule["number_overlap"]
)

# Rank candidates for each Source1
ranked_test = (
    test_rule
    .sort_values(
        ["source1_entity_id", "combined_score"],
        ascending=[True, False]
    )
    .copy()
)

ranked_test["rank"] = (
    ranked_test
    .groupby("source1_entity_id")
    .cumcount() + 1
)

# Keep top 2
top2 = ranked_test[ranked_test["rank"] <= 2].copy()

# Calculate margin
margin_test = (
    top2
    .pivot(
        index="source1_entity_id",
        columns="rank",
        values="combined_score"
    )
    .reset_index()
)

margin_test.columns.name = None

if 1 in margin_test.columns and 2 in margin_test.columns:
    margin_test["margin"] = (
        margin_test[1] - margin_test[2]
    )

print("Multiple-candidate sources:", len(margin_test))
print("\nMargin statistics:")
print(margin_test["margin"].describe())

print("\nSmallest margins:")
print(
    margin_test
    .sort_values("margin")
    .head(30)
    .to_string(index=False)
)

In [ ]:
ambiguous_ids = margin_test[
    margin_test["margin"] < 0.02
]["source1_entity_id"]

ambiguous = ranked_test[
    ranked_test["source1_entity_id"].isin(ambiguous_ids)
].copy()

ambiguous_top2 = ambiguous[
    ambiguous["rank"] <= 2
].copy()

cols = [
    "source1_entity_id",
    "source1_name",
    "candidate_entity_id",
    "candidate_name",
    "name_similarity",
    "address_similarity",
    "address_token_similarity",
    "number_overlap",
    "match_probability",
    "combined_score",
    "rank"
]

print(
    ambiguous_top2[cols]
    .sort_values(["source1_entity_id", "rank"])
    .to_string(index=False)
)

In [ ]:
# Top candidate after ranking
best_ranked = ranked_test[
    ranked_test["rank"] == 1
].copy()

# Check exact score ties
ties = (
    ranked_test
    .groupby("source1_entity_id")
    .agg(
        candidate_count=("candidate_entity_id", "count"),
        best_score=("combined_score", "max")
    )
    .reset_index()
)

tie_ids = []

for sid in ties["source1_entity_id"]:
    rows = ranked_test[
        ranked_test["source1_entity_id"] == sid
    ]
    
    best_score = rows["combined_score"].max()
    
    if (rows["combined_score"] == best_score).sum() > 1:
        tie_ids.append(sid)

print("Exact top-score ties:", len(tie_ids))

print("\nExamples:")
print(
    ranked_test[
        ranked_test["source1_entity_id"].isin(tie_ids)
    ][[
        "source1_entity_id",
        "source1_name",
        "candidate_entity_id",
        "candidate_name",
        "combined_score",
        "match_probability"
    ]]
    .head(30)
    .to_string(index=False)
)

In [ ]:
# Final best candidate for each Source1
final_matches_10k = (
    ranked_test
    .sort_values(
        ["source1_entity_id", "combined_score", "match_probability"],
        ascending=[True, False, False]
    )
    .drop_duplicates("source1_entity_id")
    .copy()
)

print("Final matches:", len(final_matches_10k))
print("Unique Source1:", final_matches_10k["source1_entity_id"].nunique())

print("\nScore statistics:")
print(final_matches_10k["combined_score"].describe())

In [ ]:
# Full test: exact normalized name + country matches
exact_stats = con.execute("""
WITH exact_matches AS (
    SELECT
        s.source1_entity_id,
        COUNT(DISTINCT c.candidate_entity_id) AS candidate_count
    FROM s1_full s
    JOIN s23_index c
      ON s.country = c.country
     AND s.clean_name = c.clean_name
    WHERE s.clean_name <> ''
    GROUP BY s.source1_entity_id
)
SELECT
    COUNT(*) AS source1_with_exact_match,
    SUM(CASE WHEN candidate_count = 1 THEN 1 ELSE 0 END) AS unique_exact,
    SUM(CASE WHEN candidate_count > 1 THEN 1 ELSE 0 END) AS duplicate_exact
FROM exact_matches
""").fetchdf()

print(exact_stats)

In [ ]:
# Create unique exact matches
con.execute("""
CREATE OR REPLACE TABLE exact_unique AS
WITH exact_matches AS (
    SELECT
        s.source1_entity_id,
        c.candidate_entity_id,
        ROW_NUMBER() OVER (
            PARTITION BY s.source1_entity_id
            ORDER BY c.candidate_entity_id
        ) AS rn,
        COUNT(*) OVER (
            PARTITION BY s.source1_entity_id
        ) AS candidate_count
    FROM s1_full s
    JOIN s23_index c
      ON s.country = c.country
     AND s.clean_name = c.clean_name
    WHERE s.clean_name <> ''
)
SELECT
    source1_entity_id,
    candidate_entity_id
FROM exact_matches
WHERE candidate_count = 1
""")

print(
    con.execute("SELECT COUNT(*) FROM exact_unique").fetchone()[0]
)

In [ ]:
remaining_count = con.execute("""
SELECT COUNT(*)
FROM s1_full s
WHERE NOT EXISTS (
    SELECT 1
    FROM exact_unique e
    WHERE e.source1_entity_id = s.source1_entity_id
)
""").fetchone()[0]

print("Remaining Source1 entities:", remaining_count)

In [ ]:
con.execute("""
CREATE OR REPLACE TABLE remaining_s1 AS
SELECT s.*
FROM s1_full s
WHERE NOT EXISTS (
    SELECT 1
    FROM exact_unique e
    WHERE e.source1_entity_id = s.source1_entity_id
)
""")

print(
    "Remaining rows:",
    con.execute("SELECT COUNT(*) FROM remaining_s1").fetchone()[0]
)

In [ ]:
duplicate_exact_stats = con.execute("""
WITH exact_matches AS (
    SELECT
        s.source1_entity_id,
        COUNT(DISTINCT c.candidate_entity_id) AS candidate_count
    FROM remaining_s1 s
    JOIN s23_index c
      ON s.country = c.country
     AND s.clean_name = c.clean_name
    WHERE s.clean_name <> ''
    GROUP BY s.source1_entity_id
)
SELECT
    COUNT(*) AS duplicate_exact_entities,
    SUM(candidate_count) AS duplicate_candidate_rows
FROM exact_matches
WHERE candidate_count > 1
""").fetchdf()

duplicate_exact_stats

In [ ]:
id="x8k2m1"
con.execute("""
CREATE OR REPLACE TABLE duplicate_exact_candidates AS
SELECT
    s.source1_entity_id,
    s.business_name AS source1_name,
    s.business_address AS source1_address,
    s.country AS source1_country,
    c.candidate_entity_id,
    c.business_name AS candidate_name,
    c.business_address AS candidate_address,
    c.country AS candidate_country,
    regexp_replace(
        lower(coalesce(s.business_address, '')),
        '[^a-zA-Z0-9]', '', 'g'
    ) AS source1_clean_address,
    regexp_replace(
        lower(coalesce(c.business_address, '')),
        '[^a-zA-Z0-9]', '', 'g'
    ) AS candidate_clean_address
FROM remaining_s1 s
JOIN s23_index c
  ON s.country = c.country
 AND s.clean_name = c.clean_name
WHERE s.clean_name <> ''
""")

print(
    "Duplicate candidate rows:",
    con.execute("""
        SELECT COUNT(*) FROM duplicate_exact_candidates
    """).fetchone()[0]
)

In [ ]:
address_exact_stats = con.execute("""
WITH address_matches AS (
    SELECT
        source1_entity_id,
        COUNT(*) AS address_match_count
    FROM duplicate_exact_candidates
    WHERE source1_clean_address <> ''
      AND candidate_clean_address <> ''
      AND source1_clean_address = candidate_clean_address
    GROUP BY source1_entity_id
)
SELECT
    COUNT(*) AS entities_with_address_match,
    SUM(CASE WHEN address_match_count = 1 THEN 1 ELSE 0 END)
        AS unique_address_match,
    SUM(CASE WHEN address_match_count > 1 THEN 1 ELSE 0 END)
        AS multiple_address_matches
FROM address_matches
""").fetchdf()

address_exact_stats

In [ ]:
con.execute("""
CREATE OR REPLACE TABLE exact_address_unique AS
WITH address_matches AS (
    SELECT
        source1_entity_id,
        candidate_entity_id,
        ROW_NUMBER() OVER (
            PARTITION BY source1_entity_id
            ORDER BY candidate_entity_id
        ) AS rn,
        COUNT(*) OVER (
            PARTITION BY source1_entity_id
        ) AS cnt
    FROM duplicate_exact_candidates
    WHERE source1_clean_address <> ''
      AND candidate_clean_address <> ''
      AND source1_clean_address = candidate_clean_address
)
SELECT
    source1_entity_id,
    candidate_entity_id
FROM address_matches
WHERE cnt = 1
""")

print(
    "Unique exact-address matches:",
    con.execute("SELECT COUNT(*) FROM exact_address_unique").fetchone()[0]
)

In [ ]:
con.execute("""
CREATE OR REPLACE TABLE unresolved_s1 AS
SELECT s.*
FROM remaining_s1 s
WHERE NOT EXISTS (
    SELECT 1
    FROM exact_address_unique a
    WHERE a.source1_entity_id = s.source1_entity_id
)
""")

print(
    "Unresolved Source1 entities:",
    con.execute("SELECT COUNT(*) FROM unresolved_s1").fetchone()[0]
)

In [ ]:
con.execute("""
CREATE OR REPLACE TABLE fuzzy_candidates AS
SELECT
    s.source1_entity_id,
    s.business_name AS source1_name,
    s.business_address AS source1_address,
    s.country AS source1_country,

    c.candidate_entity_id,
    c.business_name AS candidate_name,
    c.business_address AS candidate_address,
    c.country AS candidate_country,

    abs(length(s.clean_name) - length(c.clean_name)) AS len_diff

FROM unresolved_s1 s
JOIN s23_index c
  ON s.country = c.country
 AND left(s.clean_name, 3) = left(c.clean_name, 3)
 AND right(s.clean_name, 3) = right(c.clean_name, 3)
 AND abs(length(s.clean_name) - length(c.clean_name)) <= 2

WHERE length(s.clean_name) >= 6
  AND length(c.clean_name) >= 6
""")

print(
    "Fuzzy candidate rows:",
    con.execute("SELECT COUNT(*) FROM fuzzy_candidates").fetchone()[0]
)

In [ ]:
con.execute("SET memory_limit='10GB'")
con.execute("SET threads=1")
con.execute("SET preserve_insertion_order=false")
con.execute("SET max_temp_directory_size='10GB'")

In [ ]:
con.execute("""
CREATE OR REPLACE TABLE fuzzy_test AS
WITH batch AS (
    SELECT *
    FROM unresolved_s1
    LIMIT 10000
),
candidates AS (
    SELECT
        s.source1_entity_id,
        c.candidate_entity_id,
        abs(length(s.clean_name) - length(c.clean_name)) AS len_diff
    FROM batch s
    JOIN s23_index c
      ON s.country = c.country
     AND left(s.clean_name, 3) = left(c.clean_name, 3)
     AND right(s.clean_name, 3) = right(c.clean_name, 3)
     AND abs(length(s.clean_name) - length(c.clean_name)) <= 2
    WHERE length(s.clean_name) >= 6
      AND length(c.clean_name) >= 6
),
ranked AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY source1_entity_id
               ORDER BY len_diff, candidate_entity_id
           ) AS rn
    FROM candidates
)
SELECT *
FROM ranked
WHERE rn <= 20
""")

print(
    "Test candidates:",
    con.execute("SELECT COUNT(*) FROM fuzzy_test").fetchone()[0]
)

In [ ]:
candidate_df = con.execute("""
SELECT
    f.source1_entity_id,
    s.business_name AS source1_name,
    s.business_address AS source1_address,
    s.country AS source1_country,

    f.candidate_entity_id,
    c.business_name AS candidate_name,
    c.business_address AS candidate_address,
    c.country AS candidate_country

FROM fuzzy_test f

JOIN unresolved_s1 s
  ON f.source1_entity_id = s.source1_entity_id

JOIN s23_index c
  ON f.candidate_entity_id = c.candidate_entity_id
""").fetchdf()

print("Candidate rows:", len(candidate_df))
print("Unique Source1:", candidate_df["source1_entity_id"].nunique())

In [ ]:
import pandas as pd
import numpy as np
from difflib import SequenceMatcher
import re

def similarity(a, b):
    a = "" if pd.isna(a) else str(a)
    b = "" if pd.isna(b) else str(b)
    return SequenceMatcher(None, a, b).ratio()

def token_similarity(a, b):
    a = "" if pd.isna(a) else str(a)
    b = "" if pd.isna(b) else str(b)

    ta = set(a.lower().split())
    tb = set(b.lower().split())

    if not ta or not tb:
        return 0.0

    return len(ta & tb) / len(ta | tb)

def number_overlap(a, b):
    a = "" if pd.isna(a) else str(a)
    b = "" if pd.isna(b) else str(b)

    na = set(re.findall(r'\d+', a))
    nb = set(re.findall(r'\d+', b))

    if not na or not nb:
        return 0.0

    return len(na & nb) / len(na | nb)

In [ ]:
candidate_df["name_similarity"] = [
    similarity(a, b)
    for a, b in zip(
        candidate_df["source1_name"],
        candidate_df["candidate_name"]
    )
]

candidate_df["address_similarity"] = [
    similarity(a, b)
    for a, b in zip(
        candidate_df["source1_address"],
        candidate_df["candidate_address"]
    )
]

candidate_df["name_token_similarity"] = [
    token_similarity(a, b)
    for a, b in zip(
        candidate_df["source1_name"],
        candidate_df["candidate_name"]
    )
]

candidate_df["address_token_similarity"] = [
    token_similarity(a, b)
    for a, b in zip(
        candidate_df["source1_address"],
        candidate_df["candidate_address"]
    )
]

candidate_df["number_overlap"] = [
    number_overlap(a, b)
    for a, b in zip(
        candidate_df["source1_address"],
        candidate_df["candidate_address"]
    )
]

candidate_df["country_match"] = (
    candidate_df["source1_country"]
    == candidate_df["candidate_country"]
).astype(int)

candidate_df["source1_address_missing"] = (
    candidate_df["source1_address"]
    .fillna("")
    .str.strip() == ""
).astype(int)

candidate_df["candidate_address_missing"] = (
    candidate_df["candidate_address"]
    .fillna("")
    .str.strip() == ""
).astype(int)

print("Features calculated.")

In [ ]:
model_features = [
    "name_similarity",
    "address_similarity",
    "name_token_similarity",
    "address_token_similarity",
    "number_overlap",
    "country_match",
    "source1_address_missing",
    "candidate_address_missing"
]

X_candidates = candidate_df[model_features]

candidate_df["match_probability"] = (
    model.predict_proba(X_candidates)[:, 1]
)

print(candidate_df["match_probability"].describe())

In [ ]:
test_rule = candidate_df[
    (candidate_df["match_probability"] >= 0.95) &
    (
        (
            (candidate_df["name_similarity"] >= 0.95) &
            (
                (candidate_df["address_similarity"] >= 0.15) |
                (candidate_df["address_token_similarity"] >= 0.30) |
                (candidate_df["number_overlap"] >= 0.50)
            )
        )
        |
        (
            (candidate_df["name_similarity"] >= 0.90) &
            (
                (candidate_df["address_similarity"] >= 0.40) |
                (candidate_df["address_token_similarity"] >= 0.50) |
                (candidate_df["number_overlap"] >= 0.50)
            )
        )
        |
        (
            (candidate_df["name_similarity"] >= 0.85) &
            (candidate_df["name_similarity"] < 0.90) &
            (
                (candidate_df["address_similarity"] >= 0.70) |
                (candidate_df["address_token_similarity"] >= 0.75) |
                (candidate_df["number_overlap"] >= 0.75)
            )
        )
    )
].copy()

print("Rule candidates:", len(test_rule))
print(
    "Unique Source1:",
    test_rule["source1_entity_id"].nunique()
)

In [ ]:
best_test = (
    test_rule
    .sort_values(
        [
            "source1_entity_id",
            "match_probability",
            "name_similarity",
            "address_similarity",
            "address_token_similarity"
        ],
        ascending=[True, False, False, False, False]
    )
    .drop_duplicates("source1_entity_id")
)

print("Final matches:", len(best_test))
print("Unique Source1:", best_test["source1_entity_id"].nunique())

In [ ]:
print(
    best_test[
        [
            "match_probability",
            "name_similarity",
            "address_similarity",
            "address_token_similarity",
            "number_overlap"
        ]
    ].describe()
)

In [ ]:
print(
    best_test[
        [
            "source1_name",
            "candidate_name",
            "source1_address",
            "candidate_address",
            "match_probability",
            "name_similarity",
            "address_similarity",
            "address_token_similarity",
            "number_overlap"
        ]
    ]
    .sort_values("match_probability", ascending=False)
    .head(20)
    .to_string(index=False)
)

In [ ]:
strict_rule = candidate_df[
    (candidate_df["match_probability"] >= 0.95) &
    (
        # Very strong name + some address evidence
        (
            (candidate_df["name_similarity"] >= 0.95) &
            (
                (candidate_df["address_similarity"] >= 0.35) |
                (candidate_df["address_token_similarity"] >= 0.50) |
                (candidate_df["number_overlap"] >= 0.50)
            )
        )

        |

        # Strong name + stronger address evidence
        (
            (candidate_df["name_similarity"] >= 0.90) &
            (
                (candidate_df["address_similarity"] >= 0.55) |
                (candidate_df["address_token_similarity"] >= 0.65) |
                (candidate_df["number_overlap"] >= 0.75)
            )
        )

        |

        # Slightly lower name similarity requires very strong address
        (
            (candidate_df["name_similarity"] >= 0.85) &
            (candidate_df["name_similarity"] < 0.90) &
            (
                (candidate_df["address_similarity"] >= 0.75) |
                (candidate_df["address_token_similarity"] >= 0.80) |
                (candidate_df["number_overlap"] >= 0.75)
            )
        )
    )
].copy()

print("Strict candidates:", len(strict_rule))
print(
    "Unique Source1:",
    strict_rule["source1_entity_id"].nunique()
)

In [ ]:
strict_best = (
    strict_rule
    .sort_values(
        [
            "source1_entity_id",
            "name_similarity",
            "address_similarity",
            "address_token_similarity",
            "number_overlap",
            "match_probability"
        ],
        ascending=[True, False, False, False, False, False]
    )
    .drop_duplicates("source1_entity_id")
)

print("Final strict matches:", len(strict_best))

In [ ]:
con.execute("""
CREATE OR REPLACE TABLE fuzzy_matches AS
SELECT
    CAST(NULL AS VARCHAR) AS source1_entity_id,
    CAST(NULL AS VARCHAR) AS candidate_entity_id,
    CAST(NULL AS DOUBLE) AS match_probability,
    CAST(NULL AS DOUBLE) AS name_similarity,
    CAST(NULL AS DOUBLE) AS address_similarity,
    CAST(NULL AS DOUBLE) AS address_token_similarity,
    CAST(NULL AS DOUBLE) AS number_overlap
WHERE FALSE
""")

print("fuzzy_matches table created")

In [ ]:
# ===== FUZZY BATCH 1 =====

batch = con.execute("""
SELECT *
FROM unresolved_s1
LIMIT 10000
""").fetchdf()

print("Batch Source1:", len(batch))

In [ ]:
fuzzy_test = con.execute("""
WITH candidates AS (
    SELECT
        s.source1_entity_id,
        c.candidate_entity_id,
        abs(length(s.clean_name) - length(c.clean_name)) AS len_diff
    FROM (
        SELECT *
        FROM unresolved_s1
        LIMIT 10000
    ) s
    JOIN s23_index c
      ON s.country = c.country
     AND left(s.clean_name, 3) = left(c.clean_name, 3)
     AND right(s.clean_name, 3) = right(c.clean_name, 3)
     AND abs(length(s.clean_name) - length(c.clean_name)) <= 2
    WHERE length(s.clean_name) >= 6
      AND length(c.clean_name) >= 6
),
ranked AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY source1_entity_id
               ORDER BY len_diff, candidate_entity_id
           ) AS rn
    FROM candidates
)
SELECT *
FROM ranked
WHERE rn <= 20
""").fetchdf()

print("Candidate rows:", len(fuzzy_test))
print("Source1 covered:", fuzzy_test["source1_entity_id"].nunique())

In [ ]:
candidate_df = con.execute("""
SELECT
    f.source1_entity_id,
    s.business_name AS source1_name,
    s.business_address AS source1_address,
    s.country AS source1_country,

    f.candidate_entity_id,
    c.business_name AS candidate_name,
    c.business_address AS candidate_address,
    c.country AS candidate_country

FROM fuzzy_test f
JOIN unresolved_s1 s
  ON f.source1_entity_id = s.source1_entity_id
JOIN s23_index c
  ON f.candidate_entity_id = c.candidate_entity_id
""").fetchdf()

print("Candidate rows:", len(candidate_df))

In [ ]:
candidate_df["name_similarity"] = [
    similarity(a, b)
    for a, b in zip(candidate_df["source1_name"], candidate_df["candidate_name"])
]

candidate_df["address_similarity"] = [
    similarity(a, b)
    for a, b in zip(candidate_df["source1_address"], candidate_df["candidate_address"])
]

candidate_df["name_token_similarity"] = [
    token_similarity(a, b)
    for a, b in zip(candidate_df["source1_name"], candidate_df["candidate_name"])
]

candidate_df["address_token_similarity"] = [
    token_similarity(a, b)
    for a, b in zip(candidate_df["source1_address"], candidate_df["candidate_address"])
]

candidate_df["number_overlap"] = [
    number_overlap(a, b)
    for a, b in zip(candidate_df["source1_address"], candidate_df["candidate_address"])
]

candidate_df["country_match"] = (
    candidate_df["source1_country"] == candidate_df["candidate_country"]
).astype(int)

candidate_df["source1_address_missing"] = (
    candidate_df["source1_address"].fillna("").str.strip() == ""
).astype(int)

candidate_df["candidate_address_missing"] = (
    candidate_df["candidate_address"].fillna("").str.strip() == ""
).astype(int)

candidate_df["match_probability"] = model.predict_proba(
    candidate_df[model_features]
)[:, 1]

print("Features + model scoring complete")

In [ ]:
strict_rule = candidate_df[
    (candidate_df["match_probability"] >= 0.95) &
    (
        (
            (candidate_df["name_similarity"] >= 0.95) &
            (
                (candidate_df["address_similarity"] >= 0.35) |
                (candidate_df["address_token_similarity"] >= 0.50) |
                (candidate_df["number_overlap"] >= 0.50)
            )
        )
        |
        (
            (candidate_df["name_similarity"] >= 0.90) &
            (
                (candidate_df["address_similarity"] >= 0.55) |
                (candidate_df["address_token_similarity"] >= 0.65) |
                (candidate_df["number_overlap"] >= 0.75)
            )
        )
        |
        (
            (candidate_df["name_similarity"] >= 0.85) &
            (candidate_df["name_similarity"] < 0.90) &
            (
                (candidate_df["address_similarity"] >= 0.75) |
                (candidate_df["address_token_similarity"] >= 0.80) |
                (candidate_df["number_overlap"] >= 0.75)
            )
        )
    )
].copy()

strict_best = (
    strict_rule
    .sort_values(
        [
            "source1_entity_id",
            "name_similarity",
            "address_similarity",
            "address_token_similarity",
            "number_overlap",
            "match_probability"
        ],
        ascending=[True, False, False, False, False, False]
    )
    .drop_duplicates("source1_entity_id")
)

print("Batch 1 final matches:", len(strict_best))

In [ ]:
batch_result = strict_best[
    [
        "source1_entity_id",
        "candidate_entity_id",
        "match_probability",
        "name_similarity",
        "address_similarity",
        "address_token_similarity",
        "number_overlap"
    ]
].copy()

con.register("batch_result_df", batch_result)

con.execute("""
INSERT INTO fuzzy_matches
SELECT
    source1_entity_id,
    candidate_entity_id,
    match_probability,
    name_similarity,
    address_similarity,
    address_token_similarity,
    number_overlap
FROM batch_result_df
""")

print(
    "Saved fuzzy matches:",
    con.execute("SELECT COUNT(*) FROM fuzzy_matches").fetchone()[0]
)

In [ ]:
# ===== BATCH PROCESSOR =====

BATCH_SIZE = 10000
START_OFFSET = 10000
END_OFFSET = 60000

for offset in range(START_OFFSET, END_OFFSET, BATCH_SIZE):

    print(f"\n========== Batch offset {offset} ==========")

    # 1. Get batch
    batch_s1 = con.execute(f"""
        SELECT *
        FROM unresolved_s1
        LIMIT {BATCH_SIZE}
        OFFSET {offset}
    """).fetchdf()

    if len(batch_s1) == 0:
        print("No more rows.")
        break

    # 2. Register batch
    con.register("current_batch", batch_s1)

    # 3. Generate candidates
    fuzzy_test = con.execute("""
        WITH candidates AS (
            SELECT
                s.source1_entity_id,
                c.candidate_entity_id,
                abs(length(s.clean_name) - length(c.clean_name)) AS len_diff
            FROM current_batch s
            JOIN s23_index c
              ON s.country = c.country
             AND left(s.clean_name, 3) = left(c.clean_name, 3)
             AND right(s.clean_name, 3) = right(c.clean_name, 3)
             AND abs(length(s.clean_name) - length(c.clean_name)) <= 2
            WHERE length(s.clean_name) >= 6
              AND length(c.clean_name) >= 6
        ),
        ranked AS (
            SELECT *,
                   ROW_NUMBER() OVER (
                       PARTITION BY source1_entity_id
                       ORDER BY len_diff, candidate_entity_id
                   ) AS rn
            FROM candidates
        )
        SELECT *
        FROM ranked
        WHERE rn <= 20
    """).fetchdf()

    print("Candidate rows:", len(fuzzy_test))

    if len(fuzzy_test) == 0:
        continue

    # 4. Get candidate details
    con.register("current_candidates", fuzzy_test)

    candidate_df = con.execute("""
        SELECT
            f.source1_entity_id,
            s.business_name AS source1_name,
            s.business_address AS source1_address,
            s.country AS source1_country,

            f.candidate_entity_id,
            c.business_name AS candidate_name,
            c.business_address AS candidate_address,
            c.country AS candidate_country

        FROM current_candidates f
        JOIN current_batch s
          ON f.source1_entity_id = s.source1_entity_id
        JOIN s23_index c
          ON f.candidate_entity_id = c.candidate_entity_id
    """).fetchdf()

    # 5. Features
    candidate_df["name_similarity"] = [
        similarity(a, b)
        for a, b in zip(
            candidate_df["source1_name"],
            candidate_df["candidate_name"]
        )
    ]

    candidate_df["address_similarity"] = [
        similarity(a, b)
        for a, b in zip(
            candidate_df["source1_address"],
            candidate_df["candidate_address"]
        )
    ]

    candidate_df["name_token_similarity"] = [
        token_similarity(a, b)
        for a, b in zip(
            candidate_df["source1_name"],
            candidate_df["candidate_name"]
        )
    ]

    candidate_df["address_token_similarity"] = [
        token_similarity(a, b)
        for a, b in zip(
            candidate_df["source1_address"],
            candidate_df["candidate_address"]
        )
    ]

    candidate_df["number_overlap"] = [
        number_overlap(a, b)
        for a, b in zip(
            candidate_df["source1_address"],
            candidate_df["candidate_address"]
        )
    ]

    candidate_df["country_match"] = (
        candidate_df["source1_country"]
        == candidate_df["candidate_country"]
    ).astype(int)

    candidate_df["source1_address_missing"] = (
        candidate_df["source1_address"]
        .fillna("")
        .str.strip() == ""
    ).astype(int)

    candidate_df["candidate_address_missing"] = (
        candidate_df["candidate_address"]
        .fillna("")
        .str.strip() == ""
    ).astype(int)

    # 6. Model
    candidate_df["match_probability"] = model.predict_proba(
        candidate_df[model_features]
    )[:, 1]

    # 7. Strict rule
    strict_rule = candidate_df[
        (candidate_df["match_probability"] >= 0.95) &
        (
            (
                (candidate_df["name_similarity"] >= 0.95) &
                (
                    (candidate_df["address_similarity"] >= 0.35) |
                    (candidate_df["address_token_similarity"] >= 0.50) |
                    (candidate_df["number_overlap"] >= 0.50)
                )
            )
            |
            (
                (candidate_df["name_similarity"] >= 0.90) &
                (
                    (candidate_df["address_similarity"] >= 0.55) |
                    (candidate_df["address_token_similarity"] >= 0.65) |
                    (candidate_df["number_overlap"] >= 0.75)
                )
            )
            |
            (
                (candidate_df["name_similarity"] >= 0.85) &
                (candidate_df["name_similarity"] < 0.90) &
                (
                    (candidate_df["address_similarity"] >= 0.75) |
                    (candidate_df["address_token_similarity"] >= 0.80) |
                    (candidate_df["number_overlap"] >= 0.75)
                )
            )
        )
    ].copy()

    # 8. Best match per Source1
    strict_best = (
        strict_rule
        .sort_values(
            [
                "source1_entity_id",
                "name_similarity",
                "address_similarity",
                "address_token_similarity",
                "number_overlap",
                "match_probability"
            ],
            ascending=[True, False, False, False, False, False]
        )
        .drop_duplicates("source1_entity_id")
    )

    print("Final matches:", len(strict_best))

    # 9. Save
    if len(strict_best) > 0:

        batch_result = strict_best[
            [
                "source1_entity_id",
                "candidate_entity_id",
                "match_probability",
                "name_similarity",
                "address_similarity",
                "address_token_similarity",
                "number_overlap"
            ]
        ].copy()

        con.register("batch_result_df", batch_result)

        con.execute("""
            INSERT INTO fuzzy_matches
            SELECT
                source1_entity_id,
                candidate_entity_id,
                match_probability,
                name_similarity,
                address_similarity,
                address_token_similarity,
                number_overlap
            FROM batch_result_df
        """)

    print(
        "Total saved:",
        con.execute("SELECT COUNT(*) FROM fuzzy_matches").fetchone()[0]
    )

print("\n===== 5 BATCHES COMPLETE =====")

In [ ]:
# Final reliable matches
con.execute("""
CREATE OR REPLACE TABLE final_matches AS

SELECT
    source1_entity_id,
    candidate_entity_id
FROM exact_unique

UNION

SELECT
    source1_entity_id,
    candidate_entity_id
FROM exact_address_unique

UNION

SELECT
    source1_entity_id,
    candidate_entity_id
FROM fuzzy_matches
""")

print("Total final matches:",
      con.execute("SELECT COUNT(*) FROM final_matches").fetchone()[0])

print("Unique Source1 matched:",
      con.execute("""
          SELECT COUNT(DISTINCT source1_entity_id)
          FROM final_matches
      """).fetchone()[0])

In [ ]:
# ===== CREATE matching_results.tsv =====

output_dir = "/kaggle/working/output"

import os
os.makedirs(output_dir, exist_ok=True)

con.execute(f"""
COPY (
    SELECT
        s.source1_entity_id,
        COALESCE(f.candidate_entity_id, '') AS matched_entity_ids
    FROM s1_full s
    LEFT JOIN final_matches f
        ON s.source1_entity_id = f.source1_entity_id
    ORDER BY s.source1_entity_id
)
TO '{output_dir}/matching_results.tsv'
WITH (
    FORMAT CSV,
    DELIMITER '\t',
    HEADER TRUE,
    QUOTE ''
)
""")

print("matching_results.tsv created")

print(
    "Rows:",
    con.execute("""
        SELECT COUNT(*)
        FROM read_csv_auto(
            '/kaggle/working/output/matching_results.tsv',
            delim='\t'
        )
    """).fetchone()[0]
)

In [ ]:
# ===== CREATE candidate_pairs.tsv =====

con.execute(f"""
COPY (
    SELECT
        s.source1_entity_id,
        COALESCE(f.candidate_entity_id, '') AS candidate_entity_ids
    FROM s1_full s
    LEFT JOIN final_matches f
        ON s.source1_entity_id = f.source1_entity_id
    ORDER BY s.source1_entity_id
)
TO '/kaggle/working/output/candidate_pairs.tsv'
WITH (
    FORMAT CSV,
    DELIMITER '\t',
    HEADER TRUE,
    QUOTE ''
)
""")

print("candidate_pairs.tsv created")

print(
    "Rows:",
    con.execute("""
        SELECT COUNT(*)
        FROM read_csv_auto(
            '/kaggle/working/output/candidate_pairs.tsv',
            delim='\t'
        )
    """).fetchone()[0]
)

In [ ]:
!python3 /kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/utils/validate_submission.py \
  --matching /kaggle/working/output/matching_results.tsv \
  --candidate /kaggle/working/output/candidate_pairs.tsv \
  --test-dir /kaggle/input/datasets/harshnagayach1908/business-entity-resolution-problem-2-0/dataset/test

In [ ]:
import os

print("matching exists:", os.path.exists(
    "/kaggle/working/output/matching_results.tsv"
))

print("candidate exists:", os.path.exists(
    "/kaggle/working/output/candidate_pairs.tsv"
))

print("matching size:",
      os.path.getsize("/kaggle/working/output/matching_results.tsv") / (1024**2),
      "MB")

print("candidate size:",
      os.path.getsize("/kaggle/working/output/candidate_pairs.tsv") / (1024**2),
      "MB")

In [ ]:
import pandas as pd

m = pd.read_csv(
    "/kaggle/working/output/matching_results.tsv",
    sep="\t",
    dtype=str
)

c = pd.read_csv(
    "/kaggle/working/output/candidate_pairs.tsv",
    sep="\t",
    dtype=str
)

print("Matching shape:", m.shape)
print("Candidate shape:", c.shape)

print("Matching columns:", list(m.columns))
print("Candidate columns:", list(c.columns))

print("Matching duplicate IDs:",
      m["source1_entity_id"].duplicated().sum())

print("Candidate duplicate IDs:",
      c["source1_entity_id"].duplicated().sum())

In [ ]:
# Fast improvement: resolve duplicate exact-name matches
# using strong address evidence.

con.execute("""
CREATE OR REPLACE TABLE duplicate_address_matches AS
SELECT
    source1_entity_id,
    candidate_entity_id
FROM (
    SELECT
        source1_entity_id,
        candidate_entity_id,
        source1_clean_address,
        candidate_clean_address,
        ROW_NUMBER() OVER (
            PARTITION BY source1_entity_id
            ORDER BY
                CASE
                    WHEN source1_clean_address <> ''
                     AND candidate_clean_address <> ''
                     AND source1_clean_address = candidate_clean_address
                    THEN 0
                    ELSE 1
                END,
                candidate_entity_id
        ) AS rn
    FROM duplicate_exact_candidates
    WHERE source1_clean_address <> ''
      AND candidate_clean_address <> ''
      AND source1_clean_address = candidate_clean_address
)
WHERE source1_clean_address <> ''
  AND candidate_clean_address <> ''
  AND source1_clean_address = candidate_clean_address
""")

print(
    "Exact-name + exact-address matches:",
    con.execute("""
        SELECT COUNT(*) FROM duplicate_address_matches
    """).fetchone()[0]
)

In [ ]:
# Add the 68,801 strong duplicate-name/address matches
# and keep ALL valid matches per Source1.

con.execute("""
CREATE OR REPLACE TABLE improved_matches AS

SELECT
    source1_entity_id,
    candidate_entity_id
FROM final_matches

UNION

SELECT
    source1_entity_id,
    candidate_entity_id
FROM duplicate_address_matches
""")

print(
    "Total match links:",
    con.execute("""
        SELECT COUNT(*) FROM improved_matches
    """).fetchone()[0]
)

print(
    "Unique Source1 matched:",
    con.execute("""
        SELECT COUNT(DISTINCT source1_entity_id)
        FROM improved_matches
    """).fetchone()[0]
)

In [ ]:
# ===== FINAL SUBMISSION FILES =====

output_dir = "/kaggle/working/output"

# 1. Matching results: ALL matches per Source1, comma-separated
con.execute(f"""
COPY (
    SELECT
        s.source1_entity_id,
        COALESCE(
            STRING_AGG(
                im.candidate_entity_id,
                ',' ORDER BY im.candidate_entity_id
            ),
            ''
        ) AS matched_entity_ids
    FROM s1_full s
    LEFT JOIN improved_matches im
        ON s.source1_entity_id = im.source1_entity_id
    GROUP BY s.source1_entity_id
    ORDER BY s.source1_entity_id
)
TO '{output_dir}/matching_results.tsv'
WITH (
    FORMAT CSV,
    DELIMITER '\t',
    HEADER TRUE,
    QUOTE ''
)
""")

# 2. Candidate pairs
# Final matches are guaranteed to be included as candidates.
con.execute(f"""
COPY (
    SELECT
        s.source1_entity_id,
        COALESCE(
            STRING_AGG(
                im.candidate_entity_id,
                ',' ORDER BY im.candidate_entity_id
            ),
            ''
        ) AS candidate_entity_ids
    FROM s1_full s
    LEFT JOIN improved_matches im
        ON s.source1_entity_id = im.source1_entity_id
    GROUP BY s.source1_entity_id
    ORDER BY s.source1_entity_id
)
TO '{output_dir}/candidate_pairs.tsv'
WITH (
    FORMAT CSV,
    DELIMITER '\t',
    HEADER TRUE,
    QUOTE ''
)
""")

print("FINAL FILES CREATED")
print("matching_results.tsv")
print("candidate_pairs.tsv")

In [ ]:
import os

for f in [
    "/kaggle/working/output/matching_results.tsv",
    "/kaggle/working/output/candidate_pairs.tsv"
]:
    print(f, os.path.getsize(f) / (1024**2), "MB")

In [ ]:
print("Exact unique:", con.execute("""
SELECT COUNT(*) FROM exact_unique
""").fetchone()[0])

print("Exact address all:", con.execute("""
SELECT COUNT(*) FROM duplicate_address_matches
""").fetchone()[0])

print("Fuzzy:", con.execute("""
SELECT COUNT(*) FROM fuzzy_matches
""").fetchone()[0])

print("Improved:", con.execute("""
SELECT COUNT(*) FROM improved_matches
""").fetchone()[0])

print("S1 total:", con.execute("""
SELECT COUNT(*) FROM s1_full
""").fetchone()[0])

In [ ]:
# ===== CHECK UNMATCHED S1 =====

con.execute("""
CREATE OR REPLACE TABLE unmatched_s1 AS
SELECT s.*
FROM s1_full s
LEFT JOIN improved_matches m
    ON s.source1_entity_id = m.source1_entity_id
WHERE m.source1_entity_id IS NULL
""")

print("Unmatched S1:",
      con.execute("SELECT COUNT(*) FROM unmatched_s1").fetchone()[0])

print("\nCountry distribution:")
print(con.execute("""
SELECT country, COUNT(*) AS cnt
FROM unmatched_s1
GROUP BY country
ORDER BY cnt DESC
LIMIT 20
""").df())

print("\nName length distribution:")
print(con.execute("""
SELECT
    CASE
        WHEN length(clean_name) < 5 THEN '<5'
        WHEN length(clean_name) BETWEEN 5 AND 7 THEN '5-7'
        WHEN length(clean_name) BETWEEN 8 AND 12 THEN '8-12'
        WHEN length(clean_name) BETWEEN 13 AND 20 THEN '13-20'
        ELSE '20+'
    END AS name_length,
    COUNT(*) AS cnt
FROM unmatched_s1
GROUP BY 1
ORDER BY cnt DESC
""").df())

In [ ]:
# ===== BROADER BLOCKING FOR UNMATCHED S1 =====

con.execute("""
CREATE OR REPLACE TABLE broad_candidates AS
WITH candidates AS (
    SELECT
        s.source1_entity_id,
        s.business_name AS source1_name,
        s.business_address AS source1_address,
        s.country AS source1_country,
        c.candidate_entity_id,
        c.business_name AS candidate_name,
        c.business_address AS candidate_address,
        c.country AS candidate_country,
        abs(length(s.clean_name) - length(c.clean_name)) AS len_diff
    FROM unmatched_s1 s
    JOIN s23_index c
      ON s.country = c.country
     AND left(s.clean_name, 4) = left(c.clean_name, 4)
     AND abs(length(s.clean_name) - length(c.clean_name)) <= 4
    WHERE length(s.clean_name) >= 8
      AND length(c.clean_name) >= 8
),
ranked AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY source1_entity_id
            ORDER BY len_diff, candidate_entity_id
        ) AS rn
    FROM candidates
)
SELECT *
FROM ranked
WHERE rn <= 10
""")

print("Broad candidate rows:",
      con.execute("SELECT COUNT(*) FROM broad_candidates").fetchone()[0])

print("S1 covered:",
      con.execute("""
          SELECT COUNT(DISTINCT source1_entity_id)
          FROM broad_candidates
      """).fetchone()[0])

In [ ]:
con.execute("DROP TABLE IF EXISTS broad_candidates")

In [ ]:
# ===== SMALL BATCH TEST =====

con.execute("DROP TABLE IF EXISTS broad_candidates")

con.execute("""
CREATE OR REPLACE TABLE batch_s1 AS
SELECT *
FROM unmatched_s1
LIMIT 5000
""")

con.execute("""
CREATE OR REPLACE TABLE broad_candidates AS
WITH candidates AS (
    SELECT
        s.source1_entity_id,
        s.business_name AS source1_name,
        s.business_address AS source1_address,
        s.country AS source1_country,
        c.candidate_entity_id,
        c.business_name AS candidate_name,
        c.business_address AS candidate_address,
        c.country AS candidate_country,
        abs(length(s.clean_name) - length(c.clean_name)) AS len_diff
    FROM batch_s1 s
    JOIN s23_index c
      ON s.country = c.country
     AND left(s.clean_name, 3) = left(c.clean_name, 3)
     AND right(s.clean_name, 3) = right(c.clean_name, 3)
     AND abs(length(s.clean_name) - length(c.clean_name)) <= 3
    WHERE length(s.clean_name) >= 6
      AND length(c.clean_name) >= 6
),
ranked AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY source1_entity_id
            ORDER BY len_diff, candidate_entity_id
        ) AS rn
    FROM candidates
)
SELECT *
FROM ranked
WHERE rn <= 10
""")

print(
    "Candidates:",
    con.execute("SELECT COUNT(*) FROM broad_candidates").fetchone()[0]
)

print(
    "S1 covered:",
    con.execute("""
        SELECT COUNT(DISTINCT source1_entity_id)
        FROM broad_candidates
    """).fetchone()[0]
)

In [ ]:
import pandas as pd
import numpy as np

# Candidate data
candidate_df = con.execute("""
    SELECT *
    FROM broad_candidates
""").df()

# ===== FEATURE FUNCTIONS =====

def similarity(a, b):
    a = "" if pd.isna(a) else str(a)
    b = "" if pd.isna(b) else str(b)
    return SequenceMatcher(None, a, b).ratio()

def token_similarity(a, b):
    a = "" if pd.isna(a) else str(a)
    b = "" if pd.isna(b) else str(b)

    ta = set(a.lower().split())
    tb = set(b.lower().split())

    if not ta or not tb:
        return 0.0

    return len(ta & tb) / len(ta | tb)

def number_overlap(a, b):
    a = "" if pd.isna(a) else str(a)
    b = "" if pd.isna(b) else str(b)

    na = set(re.findall(r'\d+', a))
    nb = set(re.findall(r'\d+', b))

    if not na or not nb:
        return 0.0

    return len(na & nb) / len(na | nb)


# ===== FEATURES =====

candidate_df["name_similarity"] = [
    similarity(a, b)
    for a, b in zip(
        candidate_df["source1_name"],
        candidate_df["candidate_name"]
    )
]

candidate_df["address_similarity"] = [
    similarity(a, b)
    for a, b in zip(
        candidate_df["source1_address"],
        candidate_df["candidate_address"]
    )
]

candidate_df["name_token_similarity"] = [
    token_similarity(a, b)
    for a, b in zip(
        candidate_df["source1_name"],
        candidate_df["candidate_name"]
    )
]

candidate_df["address_token_similarity"] = [
    token_similarity(a, b)
    for a, b in zip(
        candidate_df["source1_address"],
        candidate_df["candidate_address"]
    )
]

candidate_df["number_overlap"] = [
    number_overlap(a, b)
    for a, b in zip(
        candidate_df["source1_address"],
        candidate_df["candidate_address"]
    )
]

candidate_df["country_match"] = (
    candidate_df["source1_country"] ==
    candidate_df["candidate_country"]
).astype(int)

candidate_df["source1_address_missing"] = (
    candidate_df["source1_address"].fillna("").str.strip() == ""
).astype(int)

candidate_df["candidate_address_missing"] = (
    candidate_df["candidate_address"].fillna("").str.strip() == ""
).astype(int)


# ===== MODEL =====

feature_cols = [
    "name_similarity",
    "address_similarity",
    "name_token_similarity",
    "address_token_similarity",
    "number_overlap",
    "country_match",
    "source1_address_missing",
    "candidate_address_missing"
]

candidate_df["match_probability"] = model.predict_proba(
    candidate_df[feature_cols]
)[:, 1]

print("Total candidates:", len(candidate_df))

print(
    "Probability >= 0.95:",
    (candidate_df["match_probability"] >= 0.95).sum()
)

print(
    "Probability >= 0.99:",
    (candidate_df["match_probability"] >= 0.99).sum()
)

In [ ]:
# ===== ADD HIGH-CONFIDENCE MATCHES =====

high_conf = candidate_df[
    candidate_df["match_probability"] >= 0.99
].copy()

print("High-confidence matches:", len(high_conf))
print(
    "Unique S1:",
    high_conf["source1_entity_id"].nunique()
)

# Create table in DuckDB
con.register("high_conf_df", high_conf[
    ["source1_entity_id", "candidate_entity_id"]
])

con.execute("""
CREATE OR REPLACE TABLE high_conf_matches AS
SELECT DISTINCT
    source1_entity_id,
    candidate_entity_id
FROM high_conf_df
""")

# Merge with existing matches
con.execute("""
CREATE OR REPLACE TABLE improved_matches_v2 AS
SELECT source1_entity_id, candidate_entity_id
FROM improved_matches

UNION

SELECT source1_entity_id, candidate_entity_id
FROM high_conf_matches
""")

print(
    "Old links:",
    con.execute("""
        SELECT COUNT(*) FROM improved_matches
    """).fetchone()[0]
)

print(
    "New links:",
    con.execute("""
        SELECT COUNT(*) FROM improved_matches_v2
    """).fetchone()[0]
)

print(
    "New matched S1:",
    con.execute("""
        SELECT COUNT(DISTINCT source1_entity_id)
        FROM improved_matches_v2
    """).fetchone()[0]
)

In [ ]:
output_dir = "/kaggle/working/output"

# ===== FINAL MATCHING RESULTS =====

con.execute(f"""
COPY (
    WITH dedup AS (
        SELECT DISTINCT
            source1_entity_id,
            candidate_entity_id
        FROM improved_matches_v2
    ),
    agg AS (
        SELECT
            source1_entity_id,
            STRING_AGG(
                candidate_entity_id,
                ',' ORDER BY candidate_entity_id
            ) AS matched_entity_ids
        FROM dedup
        GROUP BY source1_entity_id
    )
    SELECT
        s.source1_entity_id,
        COALESCE(a.matched_entity_ids, '') AS matched_entity_ids
    FROM s1_full s
    LEFT JOIN agg a
        ON s.source1_entity_id = a.source1_entity_id
    ORDER BY s.source1_entity_id
)
TO '{output_dir}/matching_results_v2.tsv'
WITH (
    FORMAT CSV,
    DELIMITER '\t',
    HEADER TRUE,
    QUOTE ''
)
""")

# ===== CANDIDATE FILE =====

con.execute(f"""
COPY (
    WITH dedup AS (
        SELECT DISTINCT
            source1_entity_id,
            candidate_entity_id
        FROM improved_matches_v2
    ),
    agg AS (
        SELECT
            source1_entity_id,
            STRING_AGG(
                candidate_entity_id,
                ',' ORDER BY candidate_entity_id
            ) AS candidate_entity_ids
        FROM dedup
        GROUP BY source1_entity_id
    )
    SELECT
        s.source1_entity_id,
        COALESCE(a.candidate_entity_ids, '') AS candidate_entity_ids
    FROM s1_full s
    LEFT JOIN agg a
        ON s.source1_entity_id = a.source1_entity_id
    ORDER BY s.source1_entity_id
)
TO '{output_dir}/candidate_pairs_v2.tsv'
WITH (
    FORMAT CSV,
    DELIMITER '\t',
    HEADER TRUE,
    QUOTE ''
)
""")

import os

for f in [
    f"{output_dir}/matching_results_v2.tsv",
    f"{output_dir}/candidate_pairs_v2.tsv"
]:
    print(f)
    print(round(os.path.getsize(f)/(1024**2), 2), "MB")

In [ ]:
# ===== TRAINING: EXACT NAME + COUNTRY PRECISION =====

print("Checking train exact-name quality...")

result = con.execute("""
WITH gt AS (
    SELECT
        source1_entity_id,
        candidate_entity_id
    FROM train_ground_truth
),
pairs AS (
    SELECT
        s1.source1_entity_id,
        s1.clean_name,
        s1.country,
        s2.candidate_entity_id
    FROM train_s1 s1
    JOIN s23_index c
      ON s1.country = c.country
     AND s1.clean_name = c.clean_name
    JOIN gt
      ON gt.source1_entity_id = s1.source1_entity_id
     AND gt.candidate_entity_id = c.candidate_entity_id
)
SELECT COUNT(*) AS exact_name_true_matches
FROM pairs
""").fetchone()

print("Exact-name true matches:", result[0])

In [ ]:
import duckdb

con = duckdb.connect()

con.execute("SET memory_limit='10GB'")
con.execute("SET threads=1")
con.execute("SET preserve_insertion_order=false")
con.execute("SET max_temp_directory_size='10GB'")

print("DuckDB connected:", con)

In [ ]:
print(con.execute("SHOW TABLES").df().to_string(index=False))

In [ ]:
import pandas as pd
import os

match_file = "/kaggle/working/output/matching_results.tsv"
candidate_file = "/kaggle/working/output/candidate_pairs.tsv"

print("Matching file exists:", os.path.exists(match_file))
print("Candidate file exists:", os.path.exists(candidate_file))

m = pd.read_csv(match_file, sep="\t")

print("\nRows:", len(m))
print("Columns:", list(m.columns))
print("Matched S1:", (m["matched_entity_ids"].fillna("") != "").sum())
print("\nSample:")
print(m.head())

In [ ]:
!find /kaggle/working -maxdepth 2 -type f 2>/dev/null | head -50

In [ ]:
!find /kaggle/input -name "student_matching_model_package.pkl" -o -name "matching_results*.tsv" 2>/dev/null | head -20

In [1]:
import os
import shutil

working = "/kaggle/working"

for name in os.listdir(working):
    path = os.path.join(working, name)

    # output folder ko completely remove karega
    if name == "output":
        shutil.rmtree(path, ignore_errors=True)

    # DuckDB temporary files/folders
    elif name.startswith(".tmp") or name.startswith("tmp"):
        if os.path.isdir(path):
            shutil.rmtree(path, ignore_errors=True)
        else:
            try:
                os.remove(path)
            except:
                pass

print("Cleanup complete!")
print(os.listdir(working))

Cleanup complete!
['.virtual_documents']